### ISSUE TITLE
Leaves of boolean type cannot be deleted from the operational store

### ISSUE THREAD

**Issue by deastoe** [sysrepo/sysrepo#2442] opened 2021-05-28 13:42 UTC
In sysrepo 2.0.1, built against libyang2 2.0.7, `sr_delete_item()` fails when attempting to delete a leaf of boolean type in the operational store.

Can be reproduced with the following diff:
```
diff --git a/examples/examples.yang b/examples/examples.yang
index d768ecb0..4eddcf85 100644
--- a/examples/examples.yang
+++ b/examples/examples.yang
@@ -6,6 +6,9 @@ module examples {
         leaf l {
             type string;
         }
+        leaf b {
+            type boolean;
+       }
     }

     container stats {
diff --git a/examples/sr_set_item_example.c b/examples/sr_set_item_example.c
index cbf0a16e..cc2fa940 100644
--- a/examples/sr_set_item_example.c
+++ b/examples/sr_set_item_example.c
@@ -29,14 +29,15 @@ main(int argc, char **argv)
     sr_conn_ctx_t *connection = NULL;
     sr_session_ctx_t *session = NULL;
     int rc = SR_ERR_OK;
-    const char *xpath, *value;
+    const char *ds_str, *xpath, *value;

-    if (argc != 3) {
-        printf("%s <xpath-to-set> <value-to-set>\n", argv[0]);
+    if (argc != 4) {
+        printf("%s <ds> <xpath-to-set> <value-to-set>\n", argv[0]);
         return EXIT_FAILURE;
     }
-    xpath = argv[1];
-    value = argv[2];
+    ds_str = argv[1];
+    xpath = argv[2];
+    value = argv[3];

     printf("Application will set \"%s\" to \"%s\".\n", xpath, value);

@@ -49,8 +50,15 @@ main(int argc, char **argv)
         goto cleanup;
     }

+    sr_datastore_t ds;
+    if (strcmp(ds_str, "operational") == 0) {
+        ds = SR_DS_OPERATIONAL;
+    } else {
+        ds = SR_DS_RUNNING;
+    }
+
     /* start session */
-    rc = sr_session_start(connection, SR_DS_RUNNING, &session);
+    rc = sr_session_start(connection, ds, &session);
     if (rc != SR_ERR_OK) {
         goto cleanup;
     }
@@ -67,7 +75,22 @@ main(int argc, char **argv)
         goto cleanup;
     }

+    /* delete the value */
+    rc = sr_delete_item(session, xpath, 0);
+    if (rc != SR_ERR_OK) {
+        printf("sr_delete_item failed\n");
+        goto cleanup;
+    }
+
+    /* apply the change */
+    rc = sr_apply_changes(session, 0);
+    if (rc != SR_ERR_OK) {
+        goto cleanup;
+    }
+
 cleanup:
     sr_disconnect(connection);
+    if (rc)
+        printf("rc %d\n", rc);
     return rc ? EXIT_FAILURE : EXIT_SUCCESS;
 }
```

Deleting `b` from the operational store fails:
```
$ ./set-delete operational "/examples:cont/b" false  
Application will set "/examples:cont/b" to "false".
[ERR]: Invalid boolean value "".
[ERR]: Invalid datastore edit.
sr_delete_item failed
rc 1
```
but succeeds against the running store:
```
$ ./set-delete running "/examples:cont/b" false
Application will set "/examples:cont/b" to "false".
```

The `l` leaf, of string type, can be set and deleted in either store:
```
$ ./set-delete operational "/examples:cont/l" foo
Application will set "/examples:cont/l" to "foo".
$ ./set-delete running "/examples:cont/l" foo         
Application will set "/examples:cont/l" to "foo".
```

**Comment by deastoe** [comment] 2021-05-28 14:31
I don't observe the issue in libyang1 based versions of sysrepo eg. sysrepo @ f5e981ce7d7758996d9699124b09e2dbfede50d6 and libyang @ 7e2a3b1022c3506c435f1d2aee1da87326b027a3.

**Comment by michalvasko** [comment] 2021-05-31 10:09
Right, you have discovered what is basically a feature of the new stored operational data. Since they are independent of `running`, the complete information must be stored directly in the stored stand-alone operational data tree. And to generate diff for any `operational` change subscriptions, you need to have the value that you are deleting. But `sr_delete_item()` does not have a parameter for that.

So, there are 2 problems:
1) The value of any deleted leaf/leaf-list must be set.
2) There must be API that will actually allow setting the value.

From this example it seems you are fine with 1). If that is so, it is not a problem to add another function to solve 2). But if it was a problem, I do not think there is any solution. This is simply a consequence and minor disadvantage compared to the previous stored oper data mechanism. There are still lots of advantages.

**Comment by Reshad-Rahman** [comment] 2021-05-31 13:53
Thanks Michal. I don't understand why this is an issue for boolean but not for string.

**Comment by michalvasko** [comment] 2021-06-01 07:35
The issue does not manifest for string because, for the particular string, an empty value `""` was valid. It is never for a boolean. In any case, now there is a function `sr_oper_delete_item()` that can be used for this use-case.

**Comment by Reshad-Rahman** [comment] 2021-06-01 12:11
Thanks Michal. I haven't followed the reason why the value has to be provided to delete a leaf node in operational datastore. I understand that operational is independent of running but why wouldn't unique XPath be sufficient? And what if the value provided is not the correct one, e.g. in the boolean example, what would happen if the value is true and we call sr_oper_delete_item(..., false), would the call fail?

**Comment by deastoe** [comment] 2021-06-01 12:18
Thanks for the quick response Michal! Like Reshad I don't follow why a value must be provided to delete an item in the operational store.

I've tried out the new API and it seems that providing any value works (it doesn't need to be what is in the store). Can we depend on this behaviour, or should the value in the store be provided?

If we can depend on it, would another approach, rather than adding the new oper specific API, be to have `sr_delete_item()` pass in a "dummy" value under the covers?

**Comment by michalvasko** [comment] 2021-06-01 12:25
@Reshad-Rahman

> why wouldn't unique XPath be sufficient?

Like I said, now the operational data are completely independent (from `running`). But you can still subscribe for changes in the `operational` datastore. So what change should exactly be reported in the change callback if you remove a boolean node with empty value? In any case, at least some valid value should be presented because operational data edit is essentially "stronger" than edits on conventional datastores.

What you are doing in `running` is "now deleting a node from running". But in `operational` you are "deleting a specific node anytime in future it appears in operational (subscribed running data) datastore, doing nothing if it does not". And this needs to be reported as a specific change at the moment the edit is made, hence the problems.

> And what if the value provided is not the correct one

I think the correct behavior would be to ignore the edit, it would also be consistent with the reported changes. But seeing what @deastoe wrote, it is probably not working this way and I think it is simply because there is unified behavior for all the edits but what I wrote would be specific for `operational`, so I will have to adjust that. So just give me some time (I am stuck on issues right now but need to do some other work as well) and I will write a test for it and fix it.

**Comment by Reshad-Rahman** [comment] 2021-06-01 20:28
`So what change should exactly be reported in the change callback if you remove a boolean node with empty value?`
I really don't know how the operational datastore is now structured. But if an application deletes XPath "/a/b/c" (where c is a leaf node), isn't the value of "c" in the operational datastore and therefore sysrepo knows what value is being deleted? I'm probably missing something basic here.

For oper data which is maintained outside of sysrepo, as per sr_oper_get_items_subscribe(), I don't know how subscriptions (will) work, but in that case I can see why you'd want the app to provide the old value (since sysrepo doesn't have it).

**Comment by michalvasko** [comment] 2021-06-02 05:13
I am not sure we need to go into such details but here goes nothing.

> I really don't know how the operational datastore is now structured.

It is build from pieces. First, enabled (subscribed-to) `running` data are duplicated and then merged with the stored `operational` data and finally `operational` data subscriptions. The stored `operational` data have the form of *edit* (think basically NETCONF edit-config), which you probably know depends on what data it is applied on. The problem is that the data it is applied on are changing so it is impossible to provide accurate change at the moment of storing the data. So, instead the "intentional" change is reported (such as delete on a node that may not be deleted if it does not exist) but for that the value is needed.

Another solution was possible, which is to try to apply the edit at the moment it is stored and report only the actual changes to the datastore. However, I do not think this really improves anything and would obviously have much worse performance because of the need to get enabled `running` data as the base data to apply the edit on.

> For oper data which is maintained outside of sysrepo, as per sr_oper_get_items_subscribe(), I don't know how subscriptions (will) work, but in that case I can see why you'd want the app to provide the old value (since sysrepo doesn't have it).

Like you said, *sysrepo* has no knowledge about how the data are changing so the change subscriptions do not work with `pull` operational data at all.

**Comment by Reshad-Rahman** [comment] 2021-06-02 13:21
I just noticed that the new API sr_oper_delete_item() takes the value as a string. Should this be renamed to sr_oper_delete_item_str() and add a new API sr_oper_delete_item() which takes an sr_val_t?

**Comment by michalvasko** [comment] 2021-06-02 13:28
Oh, right, it should probably be kept unified. I have not added the `_item` variant because I really do not see the point.

**Comment by michalvasko** [comment] 2021-07-22 08:24
> I've tried out the new API and it seems that providing any value works (it doesn't need to be what is in the store). Can we depend on this behaviour, or should the value in the store be provided?

I have updated it and now you must provide the value in the datastore, otherwise it will not do anything.

**Closed** 2022-05-30 10:11 UTC
Labels: is:enhancement, status:completed
