### ISSUE TITLE
sysrepo/src/shm_mod.c:464: void sr_shmmod_unlock(struct sr_mod_lock_s *, int, sr_lock_mode_t, sr_cid_t, sr_sid_t): Assertion `!memcmp(&shm_lock->sid, &sid, sizeof sid)' failed.

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#2304] opened 2021-02-02 10:50 UTC
Hey, we just got this via our CI:
```
sysrepo/src/shm_mod.c:464: void sr_shmmod_unlock(struct sr_mod_lock_s *, int, sr_lock_mode_t, sr_cid_t, sr_sid_t):
 Assertion `!memcmp(&shm_lock->sid, &sid, sizeof sid)' failed.
```

It's triggered by a test which constantly pushes ops data to sysrepo. Unfortunately I don't have a stacktrace for you. It's with commit e7dc2ee4.

**Comment by jktjkt** [comment] 2021-02-02 10:58
Oh, the stack trace is apparently rather simple, here's the relevant part (after removing the TSAN bits and the event loop stack that is huuuuuge):
```
 #8 sr_shmmod_modinfo_unlock sysrepo/src/shm_mod.c:662:13 (libsysrepo.so.5+0x8e251)
 #9 sr_apply_changes sysrepo/src/sysrepo.c:2126:5 (libsysrepo.so.5+0x11288)
 #10 sysrepo::Session::apply_changes(unsigned int, int) sysrepo/bindings/cpp/src/Session.cpp:261:15 (libsysrepo-cpp.so.5+0x2a840)
```

**Comment by pfeige** [comment] 2021-02-02 11:49
I've got a similar assertion in [sr_shmmod_lock()](https://github.adtran.com/opensource/sysrepo/blob/e7dc2ee4321e00e6b4030416bdd664ad9b1b80f0/src/shm_mod.c#L451). This seem to be caused by an shm_lock->sid.user == NULL. The value is not always available as it can be seen in [sr_shmsub_notify_rite_event()](https://github.adtran.com/opensource/sysrepo/blob/e7dc2ee4321e00e6b4030416bdd664ad9b1b80f0/src/shm_sub.c#L333) and in [sr_shmsub_multi_notify_write_event()](https://github.adtran.com/opensource/sysrepo/blob/e7dc2ee4321e00e6b4030416bdd664ad9b1b80f0/src/shm_sub.c#L378).
I guess it would be better to use 
`assert(shm_lock->sid.sr == sid.sr && shm_lock->sid.nc == sid.nc);`
instead of the full memcmp(). There are at leas 4 of these memcmp() shm_mod.c.

**Comment by jktjkt** [comment] 2021-02-02 12:06
@pfeige do you have an e-mail address that I can use to credit you in a commit which tries to fix this? Your commits in sysrepo are marked as `Author: Peter Feige <38519840+pfeige@users.noreply.github.com>`.

**Comment by pfeige** [comment] 2021-02-02 12:10
You can use peter.feige@adtran.com .

**Comment by michalvasko** [comment] 2021-02-04 13:46
Could you please provide a simple way to reproduce it? I may just add sending the username as well. However, the idea is that whoever locked the module, is going to unlock it (hence username can be `NULL`). It is possible that while this being true, SID is not handled the same way (mostly because of multiple read locks, in which case only one SID is stored) so I would like to add such a test case to tests and fix the SID logic.

**Comment by pfeige** [comment] 2021-02-04 14:14
Our test which triggers the assertion does the following:
- lock the running datastore in one session and try to lock it again from a different session
- lock the candidate datastore in one session and try to lock it again from a different session
- lock the startup datastore in one session and try to lock it again from a different session
In the last step the assertion occurs.

**Comment by jktjkt** [comment] 2021-02-04 14:28
I'm afraid I don't have a self-contained reproducer. Our test used two separate sessions (over two connections). One of them was doing constant pushes of ops data, sometimes one leaf, sometimes two leafs, sometimes deletions. The other one was requesting one particular leaf every now and then.

I just run this a few times in a loop, and I have not hit that. But that doesn't surprise me as I've only seen it once or twice I think.

**Comment by michalvasko** [comment] 2021-02-05 08:12
@pfeige Okay, that sounds reproducible, how exactly is the thread setup? Session 1 and session 2 are in separate threads or simply all the steps you wrote executed sequentially?

**Comment by pfeige** [comment] 2021-02-05 08:40
The test executes the steps sequential.

**Comment by michalvasko** [comment] 2021-02-05 10:44
Tried to write such a test (referenced), did not fail on any assert. Can you maybe modify it so that it does?

**Comment by pfeige** [comment] 2021-02-05 11:13
In principle the test seems to work the way I described. But the difference is that our test works with the whole stack. It sends RPCs from a netconf client (python ncclient) to the netopeer2 daemon. But anyway, I will try to reproduce this via the mocka test.

**Comment by jktjkt** [comment] 2021-04-07 13:45
We just started getting *occasional* hits of this assert via sysrepo's own testsuite, and when TSAN is active. Here's the [full log](https://object-store.cloud.muni.cz/swift/v1/ci-logs-public/99/4099/1/check/f33-clang-tsan/ae49c46/job-output.txt), and here's the relevant part:
```
[ RUN       ] test rpc crash
[3727][ERR]: Callback event "rpc" with ID 1 processing timed out.
[3727][WRN]: Event "rpc" with ID 1 priority 0 failed (Timeout expired).
[3727][WRN]: Connection with CID 7 is dead.
[3727][WRN]: Recovering RPC/action "/ops:rpc3" subscription of CID 7.
[3727][INF]: Applying scheduled changes.
[3727][INF]: No scheduled changes.
[3727][INF]: Connection 8 created.
[3727][INF]: Module "iana-if-type" scheduled for deletion.
[3727][INF]: Module "ietf-interfaces" scheduled for deletion.
[3727][INF]: Module "ops" scheduled for deletion.
[3727][INF]: Module "ops-ref" scheduled for deletion.
[3727][INF]: Applying scheduled changes.
[3727][INF]: File "ops.yang" was removed.
[3727][INF]: Module "ops" was removed.
[3727][INF]: File "ops-ref.yang" was removed.
[3727][INF]: Module "ops-ref" was removed.
[3727][INF]: File "iana-if-type@2014-05-08.yang" was removed.
[3727][INF]: Module "iana-if-type" was removed.
[3727][INF]: File "ietf-interfaces@2014-05-08.yang" was removed.
[3727][INF]: Module "ietf-interfaces" was removed.
[3727][INF]: Scheduled changes applied.
[3727][INF]: Connection 9 created.
[3727][INF]: Module "ops-ref" scheduled for installation.
[3727][INF]: Module "ops" scheduled for installation.
[3727][INF]: File "ops-ref.yang" was installed.
[3727][INF]: Module "ietf-interfaces" scheduled for installation.
[3727][INF]: Module "iana-if-type" scheduled for installation.
[3727][INF]: File "ietf-interfaces@2014-05-08.yang" was installed.
[3727][INF]: Applying scheduled changes.
[3727][INF]: Module "ops-ref" will be installed as "ops" module dependency.
[3727][INF]: File "ops.yang" was installed.
[3727][INF]: Module "ops" was installed.
[3727][INF]: Dependency module "ops-ref" was installed.
[3727][INF]: Module "ietf-interfaces" will be installed as "iana-if-type" module dependency.
[3727][INF]: File "iana-if-type@2014-05-08.yang" was installed.
[3727][INF]: Module "iana-if-type" was installed.
[3727][INF]: Dependency module "ietf-interfaces" was installed.
[3727][INF]: Scheduled changes applied.
[3727][INF]: Connection 10 created.
[3727][INF]: Session 6 (user "ci", CID 10) created.
[3727][INF]: There are no subscribers for changes of the module "ietf-interfaces" in running DS.
[3940][INF]: Scheduled changes not applied because of other existing connections.
[3940][INF]: Connection 11 created.
[3940][INF]: Session 7 (user "ci", CID 11) created.
[3940][INF]: Published event "change" "ietf-interfaces" with ID 1 priority 0 for 1 subscribers.
[3727][INF]: Published event "notif" "ops" with ID 1 priority 0 for 1 subscribers.
[3727][INF]: Processing "ietf-interfaces" "change" event with ID 1 priority 0 (remaining 1 subscribers).
[3727][INF]: Successful processing of "change" event with ID 1 priority 0 (remaining 0 subscribers).
[3940][INF]: Event "change" with ID 1 priority 0 succeeded.
[3940][INF]: Published event "done" "ietf-interfaces" with ID 1 priority 0 for 1 subscribers.
[3727][INF]: Processing "notif" "ops" event with ID 1.
[3727][INF]: Successful processing of "notif" event with ID 1 priority 0 (remaining 0 subscribers).
[3727][INF]: Published event "notif" "ops" with ID 2 priority 0 for 1 subscribers.
LLVMSymbolizer: error reading file: The file was not recognized as a valid object file
[3727][INF]: Processing "ietf-interfaces" "done" event with ID 1 priority 0 (remaining 1 subscribers).
[3727][INF]: Successful processing of "done" event with ID 1 priority 0 (remaining 0 subscribers).
[3727][INF]: Processing "notif" "ops" event with ID 2.
[3727][INF]: Successful processing of "notif" event with ID 2 priority 0 (remaining 0 subscribers).
[3727][INF]: Published event "notif" "ops" with ID 3 priority 0 for 1 subscribers.
[3727][INF]: Processing "notif" "ops" event with ID 3.
[3727][INF]: Successful processing of "notif" event with ID 3 priority 0 (remaining 0 subscribers).
[3940][INF]: Published event "change" "ietf-interfaces" with ID 2 priority 0 for 1 subscribers.
[3727][INF]: Published event "notif" "ops" with ID 4 priority 0 for 1 subscribers.
[3727][INF]: Processing "ietf-interfaces" "change" event with ID 2 priority 0 (remaining 1 subscribers).
[3727][INF]: Successful processing of "change" event with ID 2 priority 0 (remaining 0 subscribers).
[3940][INF]: Event "change" with ID 2 priority 0 succeeded.
[3727][INF]: Processing "notif" "ops" event with ID 4.
[3727][INF]: Successful processing of "notif" event with ID 4 priority 0 (remaining 0 subscribers).
[3727][INF]: Published event "notif" "ops" with ID 5 priority 0 for 1 subscribers.
[3727][INF]: Processing "notif" "ops" event with ID 5.
[3727][INF]: Successful processing of "notif" event with ID 5 priority 0 (remaining 0 subscribers).
[3940][INF]: Published event "done" "ietf-interfaces" with ID 2 priority 0 for 1 subscribers.
[3727][INF]: Processing "ietf-interfaces" "done" event with ID 2 priority 0 (remaining 1 subscribers).
[3727][INF]: Successful processing of "done" event with ID 2 priority 0 (remaining 0 subscribers).
[3727][INF]: Published event "notif" "ops" with ID 6 priority 0 for 1 subscribers.
[3727][INF]: Processing "notif" "ops" event with ID 6.
[3727][INF]: Successful processing of "notif" event with ID 6 priority 0 (remaining 0 subscribers).
[3727][INF]: Published event "notif" "ops" with ID 7 priority 0 for 1 subscribers.
[3940][INF]: Published event "change" "ietf-interfaces" with ID 3 priority 0 for 1 subscribers.
[3727][INF]: Processing "ietf-interfaces" "change" event with ID 3 priority 0 (remaining 1 subscribers).
[3727][INF]: Successful processing of "change" event with ID 3 priority 0 (remaining 0 subscribers).
[3940][INF]: Event "change" with ID 3 priority 0 succeeded.
test_process: /home/ci/src/cesnet-gerrit-public/CzechLight/dependencies/sysrepo/src/shm_mod.c:428: sr_error_info_t *sr_shmmod_lock(const struct lys_module *, sr_datastore_t, struct sr_mod_lock_s *, int, sr_lock_mode_t, sr_cid_t, sr_sid_t, int): Assertion `!memcmp(&shm_lock->sid, &sid, sizeof sid)' failed.
```

**Comment by michalvasko** [comment] 2021-04-12 06:08
Okay, I finally had enough time (and will) to look at these messy DS locks, so now it should be fixed.

**Closed** 2022-05-30 09:54 UTC
Labels: is:bug, status:completed
