### ISSUE TITLE
identityref cannot be resolved (when referenced indirectly)

### ISSUE THREAD

**Issue by frimpler** [sysrepo/sysrepo#950] opened 2017-10-06 10:04 UTC
Hi,
please have a look at this commit:
https://github.com/frimpler/sysrepo/commit/f97d2f0043896188c58036661d96772f35e2fb44

It contains a test case which causes a failure in identityref resolution

Problem description:
--------------------------
The module "set_items-mod1" has a leaf which refers to a certain interface instance using the type if:interface-ref of ietf-interfaces. The test case creates an interface having the type iana-if-type:ethernetCsmacd and tries further to add a list instance of "/set_items-mod1:cont/list". This does not work, because the type iana-if-type:ethernetCsmacd cannot be found in resolve_identref().

Reasons:
------------
There are two error scenarios:
1.)
If the module "set_items-mod1" will be used as visible in the commit, the module iana-if-type is not in the module list of ly_ctx, because it has not been imported explicitly by "set_items-mod1", but resolve_identref() iterates through this list.
2.) 
If the module "set_items-mod1" imports iana-if-type (which is IMHO not necessary), the resolution fails anyway - now with the module in the list - because it's not flagged as "implemented".

Btw.: because the resolution fails, we have to deal with crashes when the ident-pointer of lyd_val will be accessed (e.g. in lyv_data_content()). Unfortunately I couldn't catch the crash with my test case, but the root cause of it is addressed, anyway.

Regards,
Frank

**Comment by michalvasko** [comment] 2017-10-06 10:22
Hi Frank,
the hole imported/implemented principle in YANG is definitely not perfect and *libyang* implements it the best way it can, we put considerable effort in trying to find the best solution and not breaking anything. So, the solution for you is to explicitly load `iana-if-type` into *sysrepo* so that it is implemented. Still, I would say it needs to be at least imported somehow, however we look at it, you have used an identity from that module in the data, how else should it be validated if the module is not present in the context?

Regards,
Michal

**Comment by frimpler** [comment] 2017-10-06 10:55
Hi Michal,

thanx for your quick response. I'm not really sure, what you mean with "explicitly load". The test case bases on the sysrepo test suite and there the module iana-if-type has been installed explicitly... However, I have indeed noticed (during debug sessions), that a ly_ctx of a "get_schema-session" which requests e.g. set_items-mod1 adds all needed modules and therefore has not problems with the resolution. But this doesn't really help in "reality", because it works only for this context. The context of e.g. set_item has a different ly_ctx instance...
I had some thoughts about a solution. In my opinion it's only possible if e.g. during ly_ctx_new to parse a given dependency file like sysrepo-module-dependencies.xml, in order to get all indirect dependencies loaded into the list... 

Regards,
Frank

**Comment by michalvasko** [comment] 2017-10-06 12:09
Hi Frank,
you are right, there are actually also other problems (it should not crash no matter what). But, in *libyang* there is already a solution for your issue, it was just not used in this case. I will create a pull request referencing this issue once I fix it.

Regards,
Michal

**Comment by frimpler** [comment] 2017-10-06 12:17
Sounds great. Please consider, too, to take over the module test I have written for it.

Have a nice weekend.

**Comment by michalvasko** [comment] 2017-10-06 12:52
Hi,
it should work if you use the most recent *libyang* (no matter if `devel` or `master`) and pull request #951.

Thanks, have a nice weekend, too!

Regards,
Michal

**Comment by frimpler** [comment] 2017-10-06 13:20
still no weekend... :-)
I have pulled the latest libyang (devel) and added the two changes in data_manager.c of pull request #951. 
The test case crashes now at this point:
data_manager.c:5303:
5303	            rc = dm_report_error(session, errors[0].message, errors[0].xpath, SR_ERR_VALIDATION_FAILED);
..because "errors" is NULL.
(just for information)

**Comment by michalvasko** [comment] 2017-10-09 07:14
Hi,
I forgot to tell you that we can put your test into the test suite but there is no need for it to be a separate test, it can be one of `cl_test` tests. So, please create such a pull request and then we can merge it.

Regarding this error, can you please post the output before the crash? Your test passes on my machine, so you could first try to make sure you have the latest *libyang* installed and actually linked (`# ldconfig -p | grep libyang`).

Regards,
Michal

**Comment by frimpler** [comment] 2017-10-09 09:37
Hi Michal,

here's the libyang version:
[git.cesnet.devel]:/usr/lib/x86_64-linux-gnu # ldconfig -p | grep libyang
	libyang.so.0.14 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libyang.so.0.14
	libyang.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libyang.so
[git.cesnet.devel]:/usr/lib/x86_64-linux-gnu # ll /usr/lib/x86_64-linux-gnu/libyang*
lrwxrwxrwx 1 root root      15 Oct  9 09:14 /usr/lib/x86_64-linux-gnu/libyang.so -> libyang.so.0.14
lrwxrwxrwx 1 root root      18 Oct  9 09:14 /usr/lib/x86_64-linux-gnu/libyang.so.0.14 -> libyang.so.0.14.13
-rw-r--r-- 1 root root 1916576 Oct  9 09:14 /usr/lib/x86_64-linux-gnu/libyang.so.0.14.13

..."git pull upstream devel" tells me that my workspace is up-to-date. The only difference to "lastest" I have is the change in sysrepo's data_manger.c from your pending pull request. Is there something else I should have added?

Concerning the testcase: I can create a pull request, but I think, it won't go through (I mean, nobody will pull it), as long as the test does not succeed...or am I wrong?

In the meantime, I will try to find out why the crash happens.

**Comment by michalvasko** [comment] 2017-10-09 09:57
Hi,
your *libyang* seems good. The crash happens because the validation fails (`rc` is non-NULL) but no errors are returned, which should never happen. The log should tell you why the validation fails and based on that it should be possible to determine where the function returns and why without filling errors.

Regards,
Michal

**Comment by frimpler** [comment] 2017-10-09 10:07
it is - as it seems - related to the new lines from the pull request:

[DBG] (cl_sm_notif_process:651) Received a notification for subscription id=347616690 (source address='/tmp/sysrepo-local-16283.sock').
[DBG] (cl_sm_notif_process:721) HELLO notification received on subscription id=347616690.
[DBG] (dm_load_data_tree_file:1158) Usage count ietf-interfaces incremented (value=2)
[INF] (dm_load_data_tree_file:1164) Data file /bld/sysrepo/repository/data/ietf-interfaces.running loaded successfully
[DBG] (dm_get_data_info_internal:2701) Module ietf-interfaces has been loaded
[ERR] (dm_append_data_tree:1838) Failed to duplicate ietf-interfaces data tree into another context
[ERR] (dm_load_dependant_data:1920) Failed to append data tree ietf-interfaces
[ERR] (dm_validate_data_info:2537) Loading dependant modules failed for set_items-mod1
[WRN] (dm_get_data_info_internal:2682) Validation of module with instance_id or cross-module deps set_items-mod1 failed
[DBG] (dm_get_data_info_internal:2701) Module set_items-mod1 has been loaded
[DBG] (dm_copy_subtree_startup_running:5609) Remove previous content of running configuration under /set_items-mod1:cont/list.
[DBG] (dm_get_data_info_internal:2654) Module set_items-mod1 already loaded
[DBG] (dm_copy_subtree_startup_running:5616) Subtree /set_items-mod1:cont/list of enabled configuration is empty
[DBG] (dm_get_data_info_internal:2654) Module ietf-interfaces already loaded
_**[ERR] (dm_append_data_tree:1838) Failed to duplicate ietf-interfaces data tree into another context**_
[ERR] (dm_load_dependant_data:1920) Failed to append data tree ietf-interfaces
[ERR] (dm_validate_data_info:2537) Loading dependant modules failed for set_items-mod1


1832	    if (NULL != di->node) {
1833	
1834	        ly_ctx_set_module_data_clb(data_info->schema->ly_ctx, dm_module_clb, dm_ctx);
1835	
1836	        if (NULL == data_info->node) {
1837	            if (NULL == data_info->node) {
1838	                **_SR_LOG_ERR("Failed to duplicate %s data tree into another context", di->schema->module->name);_**
1839	                return SR_ERR_INTERNAL;
1840	            }
1841	            data_info->node = sr_dup_datatree_to_ctx(di->node, data_info->schema->ly_ctx);
1842	        } else {
1843	            ret = lyd_merge_to_ctx(&data_info->node, di->node, LYD_OPT_EXPLICIT, data_info->schema->ly_ctx);
1844	            CHECK_ZERO_LOG_RETURN(ret, SR_ERR_INTERNAL, "Failed to merge %s data tree", di->schema->module->name);
1845	        }
1846	    } else {

**Comment by michalvasko** [comment] 2017-10-09 13:04
Hi,
so I added a commit that will hopefully fix the crash but I am no closer to learning what exactly is the problem in your case. I do not think the previous changes added this bug, just exposed an existing one. Best would be if I could reproduce it, so try to build and install everything from scratch and then post commands that produce the crash, thanks.

Regards,
Michal

**Comment by frimpler** [comment] 2017-10-09 13:23
I have tracked it a bit down, so I can tell you some details: The error code you were looking for has been created in lyd_dup_common() after calling lys_get_import_module() which returns 0. This happens because main_module = ly_ctx_get_module(module->ctx, str, NULL, 0); initializes main_module with 0 at tree_schema.c:2607 for ietf-ip, because this module cannot be found in the ctx. Any ideas why this happens? (btw. I have not yet sync'ed to your commit)
Would it be helpful for you, if you update my fork and you pull my versions?
What I do, is building+installing libyang and sysrepo and invoke afterwards set_items_test directly or with gdb. No mystery at all...

**Comment by frimpler** [comment] 2017-10-09 13:30
my forks https://github.com/frimpler/libyang and https://github.com/frimpler/sysrepo have been updated, a few minutes ago. Just for the case you want to pull my versions...

**Comment by michalvasko** [comment] 2017-10-10 11:45
Hi,
I have just tried your *sysrepo* fork (incidentally, on another machine so I installed everything from scratch, I have used our current *libyang* `devel`), then simply executed `set_items_test` and it passed, so that is the mystery :) I will try to understand what is happening for you and hopefully suggest a solution.

Regards,
Michal

**Comment by frimpler** [comment] 2017-10-10 12:40
Hi Michal,

this is really strange. I can tell you that I use docker as development environment. So I'm not at a real machine. Thus, whenever I start, all starts from the scratch. I can reproduce this crash every time I want. However, in the hope to bring some light in it, I have attached a issue.txt.gz, which contains the whole build/installation process, the execution of the test case from command line and at last the execution with gdb. The desired backtrace and sysrepoctl -l is at the end of the file. And for "completeness" I have also attached the sysrepo repository (issue.tar.gz). 
[issue.tar.gz](https://github.com/sysrepo/sysrepo/files/1371866/issue.tar.gz)
[issue.txt.gz](https://github.com/sysrepo/sysrepo/files/1371867/issue.txt.gz)

**Comment by michalvasko** [comment] 2017-10-11 12:15
Hi,
just to let you know I managed to reproduce the bug in *docker* (after I learnt its basics) and know what to fix. It should be done tomorrow, I will also try to find out why it works locally for me.

Regards,
Michal

**Comment by frimpler** [comment] 2017-10-11 12:21
I'm lucky to hear this. Docker is great, isn't it? :-)

**Comment by michalvasko** [comment] 2017-10-12 09:40
Hi Frank,
I guess, once you learn its basics. Anyway, the pull request should now work and it worked fine for me previously because I was starting your test without previous `make install` which caused that there were no `ietf-ip` data in the testing datastore of `ietf-interfaces`. So, if you want your test to be merged into the repository, please also fix this, make sure you fully set up your testing datastore in the test setup.

Regards,
Michal

**Closed** 2017-12-07 09:00 UTC
