### ISSUE TITLE
sr_shmmod_conn_lock_update: Assertion failed

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#2047] opened 2020-07-09 10:03 UTC
Hi,
I have an application writing to and reading from _ietf-hardware_ yang module simultaneously on multiple threads.
Sometimes I experience assert failure:

```
test: /opt/dev/sysrepo/src/shm_mod.c:382: sr_shmmod_conn_lock_update: Assertion `mod_locks[shm_mod_idx][ds].rcount && (mod_locks[shm_mod_idx][ds].mode != SR_LOCK_NONE)' failed.

Thread 2 "test" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff46d2700 (LWP 4021)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7594801 in __GI_abort () at abort.c:79
#2  0x00007ffff758439a in __assert_fail_base (fmt=0x7ffff770b7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7ffff7bb8b00 "mod_locks[shm_mod_idx][ds].rcount && (mod_locks[shm_mod_idx][ds].mode != SR_LOCK_NONE)", file=file@entry=0x7ffff7bb88c0 "/opt/dev/sysrepo/src/shm_mod.c", 
    line=line@entry=382, function=function@entry=0x7ffff7bb8ce0 <__PRETTY_FUNCTION__.8320> "sr_shmmod_conn_lock_update") at assert.c:92
#3  0x00007ffff7584412 in __GI___assert_fail (assertion=0x7ffff7bb8b00 "mod_locks[shm_mod_idx][ds].rcount && (mod_locks[shm_mod_idx][ds].mode != SR_LOCK_NONE)", 
    file=0x7ffff7bb88c0 "/opt/dev/sysrepo/src/shm_mod.c", line=382, function=0x7ffff7bb8ce0 <__PRETTY_FUNCTION__.8320> "sr_shmmod_conn_lock_update") at assert.c:101
#4  0x00007ffff7ba465d in sr_shmmod_conn_lock_update (conn=0x5555557572f0, shm_mod=0x7ffff7ff04c8, ds=SR_DS_RUNNING, mode=SR_LOCK_READ, lock=0) at /opt/dev/sysrepo/src/shm_mod.c:382
#5  0x00007ffff7ba50cd in sr_shmmod_modinfo_unlock (mod_info=0x7ffff46d1e60, upgradable=0) at /opt/dev/sysrepo/src/shm_mod.c:625
#6  0x00007ffff7b6dbe4 in sr_get_items (session=0x7fffec000b20, xpath=0x55555555548a "/ietf-hardware:*//.", timeout_ms=60000, opts=0, values=0x7ffff46d1ed8, value_cnt=0x7ffff46d1ee0)
    at /opt/dev/sysrepo/src/sysrepo.c:1718
#7  0x0000555555554cfd in read_data (ptr=0x0) at test.c:46
#8  0x00007ffff794c6db in start_thread (arg=0x7ffff46d2700) at pthread_create.c:463
#9  0x00007ffff767588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```
I attached a simple stress test application which can be used to reproduce the issue.
[test_c.txt](https://github.com/sysrepo/sysrepo/files/4895997/test_c.txt)

libyang version: 1.0.184
sysrepo version: 1.4.69

Both of them are built with _CMAKE_BUILD_TYPE:String="Debug" on x86_64 platform.

Thanks!

**Comment by michalvasko** [comment] 2020-07-14 13:39
Hi,
thanks for the nice example, reproduced the problem quite fast. However, the problem was partly due to not using atomic variables, partly due to missing locks, and partly due to asserts themselves. I have fixed the first problem and the third problem by commenting out the asserts. Your example then seemed to have worked fine.

As for the missing locks, I think it may not even be a real problem (it was problem for the asserts). But in any case, it will be fixed when I get to refactoring the whole recovery SHM.

Regards,
Michal

**Closed** 2020-07-21 10:52 UTC
