### ISSUE TITLE
sysrepo build with swig err

### ISSUE THREAD

**Issue by nic1225** [sysrepo/sysrepo#1383] opened 2018-12-14 07:55 UTC
hi
    **when i build sysrepo  in openWrt , Come across a problem**    

    Applying ./patches/006-update-generated-protobufc-files using plaintext: 
    patching file src/common/sysrepo.pb-c.c
    patching file src/common/sysrepo.pb-c.h
    touch /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/.prepared_7c45a10880a749eb8253c735f5f54ce9_6664517399ebbbc92a37c5bb081b5c53
    rm -f /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/.configured_*
    rm -f /home/nick/zz/openwrt/staging_dir/target-x86_64_musl/stamp/.sysrepo_installed
    mkdir -p /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7
    (cd /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7; CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7:sysrepo-0.7.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7:sysrepo-0.7.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " LDFLAGS="-L/home/nick/zz/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/nick/zz/openwrt/staging_dir/target-x86_64_musl/lib -L/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/usr/lib -L/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/lib -znow -zrelro " cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=x86_64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_C_COMPILER="/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc" -DCMAKE_C_COMPILER_ARG1="" -DCMAKE_CXX_COMPILER="/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-g++" -DCMAKE_CXX_COMPILER_ARG1="" -DCMAKE_ASM_COMPILER="/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc" -DCMAKE_ASM_COMPILER_ARG1="" -DCMAKE_EXE_LINKER_FLAGS:STRING="-L/home/nick/zz/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/nick/zz/openwrt/staging_dir/target-x86_64_musl/lib -L/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/usr/lib -L/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/lib -znow -zrelro" -DCMAKE_MODULE_LINKER_FLAGS:STRING="-L/home/nick/zz/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/nick/zz/openwrt/staging_dir/target-x86_64_musl/lib -L/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/usr/lib -L/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/lib -znow -zrelro -Wl,-Bsymbolic-functions" -DCMAKE_SHARED_LINKER_FLAGS:STRING="-L/home/nick/zz/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/nick/zz/openwrt/staging_dir/target-x86_64_musl/lib -L/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/usr/lib -L/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/lib -znow -zrelro -Wl,-Bsymbolic-functions" -DCMAKE_AR="/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc-ar" -DCMAKE_NM="/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc-nm" -DCMAKE_RANLIB="/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc-ranlib" -DCMAKE_FIND_ROOT_PATH="/home/nick/zz/openwrt/staging_dir/target-x86_64_musl/usr;/home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl" -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_STRIP=: -DCMAKE_INSTALL_PREFIX=/usr -DDL_LIBRARY=/home/nick/zz/openwrt/staging_dir/target-x86_64_musl -DCMAKE_PREFIX_PATH=/home/nick/zz/openwrt/staging_dir/target-x86_64_musl -DCMAKE_SKIP_RPATH=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DUSE_AVL_LIB:BOOL=FALSE -DENABLE_TESTS:BOOL=FALSE  /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7 )
    -- The C compiler identification is GNU 7.3.0
    -- The CXX compiler identification is GNU 7.3.0
    -- Check for working C compiler: /home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc
    -- Check for working C compiler: /home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-g++
    -- Check for working CXX compiler: /home/nick/zz/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-g++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Preparing systemwide build of sysrepo v. 0.7.7
    -- sysrepo repository location: /etc/sysrepo
    -- Found ev: /home/nick/zz/openwrt/staging_dir/target-x86_64_musl/usr/lib/libev.so  
    -- Found yang: /home/nick/zz/openwrt/staging_dir/target-x86_64_musl/usr/lib/libyang.so  
    -- Found protobuf-c: /home/nick/zz/openwrt/staging_dir/target-x86_64_musl/usr/lib/libprotobuf-c.so  
    -- Could NOT find avl (missing: AVL_LIBRARY AVL_INCLUDE_DIR) 
    -- Found redblack: /home/nick/zz/openwrt/staging_dir/target-x86_64_musl/usr/lib/libredblack.so  
    -- libredblack will be used for binary tree manipulations.
    -- Looking for pthread_rwlockattr_setkind_np
    -- Looking for pthread_rwlockattr_setkind_np - not found
    -- Looking for getpeereid
    -- Looking for getpeereid - not found
    -- Looking for getpeerucred
    -- Looking for getpeerucred - not found
    CMake Warning (dev) at /home/nick/zz/openwrt/staging_dir/host/share/cmake-3.12/Modules/CheckIncludeFiles.cmake:110 (message):
      Policy CMP0075 is not set: Include file check macros honor
      CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
      details.  Use the cmake_policy command to set the policy and suppress this
      warning.
    
      CMAKE_REQUIRED_LIBRARIES is set to:
    
        pthread
    
      For compatibility with CMake 3.11 and below this check is ignoring it.
    Call Stack (most recent call first):
      CMakeLists.txt:146 (CHECK_INCLUDE_FILES)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Looking for include file ucred.h
    -- Looking for include file ucred.h - not found
    -- Looking for pthread_mutex_timedlock
    -- Looking for pthread_mutex_timedlock - found
    -- Looking for setfsuid
    -- Looking for setfsuid - found
    -- Looking for fsetxattr
    -- Looking for fsetxattr - found
    -- Looking for mkstemps
    -- Looking for mkstemps - found
    -- Performing Test HAVE_STAT_ST_MTIM
    -- Performing Test HAVE_STAT_ST_MTIM - Success
    -- Example code and YANG models will be built and installed.
    -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
    CMake Error at /home/nick/zz/openwrt/staging_dir/host/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
      Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at
      least version "3.0.12")
    Call Stack (most recent call first):
      /home/nick/zz/openwrt/staging_dir/host/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
      /home/nick/zz/openwrt/staging_dir/host/share/cmake-3.12/Modules/FindSWIG.cmake:63 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      swig/CMakeLists.txt:9 (find_package)
    
    
    -- Configuring incomplete, errors occurred!

**than i install swig uses command "apt-get install swig=3.0.12-1", above problem disappear and new err as flowing**  

    Scanning dependencies of target Sysrepo_Lua
    make[6]: Leaving directory '/home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7'
    make[6]: Entering directory '/home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7'
    [ 91%] Building CXX object swig/lua/CMakeFiles/Sysrepo_Lua.dir/__/cpp/src/Sysrepo.cpp.o
    In file included from /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Sysrepo.cpp:26:0:
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:50:42: error: 'S_Deleter' has not been declared
         Data(sr_data_t data, sr_type_t type, S_Deleter deleter);
                                              ^~~~~~~~~
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:88:5: error: 'S_Deleter' does not name a type; did you mean 'Deleter'?
         S_Deleter _deleter;
         ^~~~~~~~~
         Deleter
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:101:24: error: 'S_Deleter' has not been declared
         Val(sr_val_t *val, S_Deleter deleter);
                            ^~~~~~~~~
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:175:5: error: 'S_Deleter' does not name a type; did you mean 'Deleter'?
         S_Deleter _deleter;
         ^~~~~~~~~
         Deleter
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp: In member function 'sysrepo::Data* sysrepo::Val::data()':
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:162:65: error: '_deleter' was not declared in this scope
         S_Data data() {S_Data data(new Data(_val->data, _val->type, _deleter)); return data;};
                                                                     ^~~~~~~~
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:162:65: note: suggested alternative: 'Deleter'
         S_Data data() {S_Data data(new Data(_val->data, _val->type, _deleter)); return data;};
                                                                     ^~~~~~~~
                                                                     Deleter
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp: At global scope:
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:186:50: error: 'S_Deleter' has not been declared
         Vals(const sr_val_t *vals, const size_t cnt, S_Deleter deleter = nullptr);
                                                      ^~~~~~~~~
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:188:40: error: 'S_Deleter' has not been declared
         Vals(sr_val_t **vals, size_t *cnt, S_Deleter deleter = nullptr);
                                            ^~~~~~~~~
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:207:5: error: 'S_Deleter' does not name a type; did you mean 'Deleter'?
         S_Deleter _deleter;
         ^~~~~~~~~
         Deleter
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:186:70: error: could not convert 'nullptr' from 'std::nullptr_t' to 'int'
         Vals(const sr_val_t *vals, const size_t cnt, S_Deleter deleter = nullptr);
                                                                          ^~~~~~~
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:188:60: error: could not convert 'nullptr' from 'std::nullptr_t' to 'int'
         Vals(sr_val_t **vals, size_t *cnt, S_Deleter deleter = nullptr);
                                                                ^~~~~~~
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:337:46: error: 'S_Deleter' has not been declared
         Schema_Submodule(sr_sch_submodule_t sub, S_Deleter deleter);
                                                  ^~~~~~~~~
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:346:5: error: 'S_Deleter' does not name a type; did you mean 'Deleter'?
         S_Deleter _deleter;
         ^~~~~~~~~
         Deleter
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:357:35: error: 'S_Deleter' has not been declared
         Yang_Schema(sr_schema_t *sch, S_Deleter deleter);
                                       ^~~~~~~~~
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:382:5: error: 'S_Deleter' does not name a type; did you mean 'Deleter'?
         S_Deleter _deleter;
         ^~~~~~~~~
         Deleter
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:405:5: error: 'S_Deleter' does not name a type; did you mean 'Deleter'?
         S_Deleter _deleter;
         ^~~~~~~~~
         Deleter
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:508:5: error: 'S_Deleter' does not name a type; did you mean 'Deleter'?
         S_Deleter _deleter_new;
         ^~~~~~~~~
         Deleter
    /home/nick/zz/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.7/swig/cpp/src/Struct.hpp:509:5: error: 'S_Deleter' does not name a type; did you mean 'Deleter'?
         S_Deleter _deleter_old;
         ^~~~~~~~~
         Deleter
    swig/lua/CMakeFiles/Sysrepo_Lua.dir/build.make:62: recipe for target 'swig/lua/CMakeFiles/Sysrepo_Lua.dir/__/cpp/src/Sysrepo.cpp.o' failed

thanks!

**Comment by mislavn** [comment] 2018-12-14 08:37
Hi,

I'm actually working on this. Just need to update the Lua unit tests. I'll make a PR next week.

Regards,
Mislav

**Comment by nic1225** [comment] 2018-12-15 09:44
Hi,
Is there any other way to avoid this error compilation. take [this](https://github.com/sysrepo/sysrepo/issues/1331) advice , i just edit /feeds/packages/net/sysrepo/Makefile as following with -DGEN_LUA_BINDINGS=OFF, then build openWrt, error  is still there.

    CMAKE_OPTIONS += \
    	-DCMAKE_BUILD_TYPE:STRING=Release \
    	-DUSE_AVL_LIB:BOOL=FALSE \
    	-DENABLE_TESTS:BOOL=FALSE \
    	#-DBUILD_EXAMPLES:BOOL=FALSE \
    	-DCMAKE_DISABLE_FIND_PACKAGE_SWIG=TRUE \
    	-DGEN_LANGUAGE_BINDINGS:BOOL=FALSE \
    	-DGEN_PYTHON_BINDINGS=0 \
    	-DGEN_LUA_BINDINGS=0 \
    	-DREPOSITORY_LOC:PATH=/etc/sysrepo \
    	-DCMAKE_INSTALL_PREFIX:PATH=/usr \
    	-DENABLE_NACM:BOOL=FALSE \
    	-DREQUEST_TIMEOUT=6 \
    	-DLONG_REQUEST_TIMEOUT=30 \
    	-DCOMMIT_VERIFY_TIMEOUT=20 \
    	-DOPER_DATA_PROVIDE_TIMEOUT=4 \
    	-DNOTIF_AGE_TIMEOUT=120 \
    	-DNOTIF_TIME_WINDOW=20 \
    	-DUSE_SR_MEM_MGMT=0 \
    	-DFILE_FORMAT_EXT:STRING=xml
    
    ifeq ($(CONFIG_SYSREPO_LUA),y)
    CMAKE_OPTIONS += \
    	-DGEN_LUA_BINDINGS:BOOL=FALSE \
    	-DGEN_LUA_VERSION=5.1
    endif

thanks!

**Comment by mislavn** [comment] 2018-12-17 10:01
If you want to build the C examples and ignore the language bindings you can add to the Makefile:
```
-DGEN_LANGUAGE_BINDINGS=0
```

**Comment by feldi59** [comment] 2019-02-05 14:46
Hi,
I have exact same problem.
I used -DGEN_LANGUAGE_BINDINGS=0 and the problem is fixed.
But why is it not running with the language bindings ?

Can i use the cpp wrapper classes for sysrepo in spite of that issue ?

**Comment by mislavn** [comment] 2019-02-05 14:51
Hi,

there was an issue with the bindings, it's fixed now in the devel branch.

If you want to use the cpp wrapper you can use the latest devel branch or build sysrepo with the flags:
```
-DGEN_LANGUAGE_BINDINGS=1
-DGEN_LUA_BINDINGS=0
```

**Closed** 2019-03-19 07:19 UTC
