### ISSUE TITLE
subscription conn closed when cl_sm_conn_in_buff_process() excute failed

### ISSUE THREAD

**Issue by chunlovemail** [sysrepo/sysrepo#1207] opened 2018-07-04 08:22 UTC
### Things you may try first
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description

1. Process1 use sr_dp_get_items_subscribe() function to subscribe some state value
2. Process2 use sr_get_item() to  get the state data. Occasionally, the following problem arise in Process1.

```
sysrepo-CSManager[1661]: [ERR] (cl_sm_conn_msg_process:1061) Unable to unpack the message (conn=0x7fcd3c001370).
sysrepo-CSManager[1661]: [ERR] (cl_sm_conn_in_buff_process:1132) Error by processing of the message.
sysrepo-CSManager[1661]: [WRN] (cl_sm_fd_read_data:1216) Error by processing of the input buffer of fd=13, closing the connection.
```
3. In sysrepo/src/clientlib/cl_subscription_manager.c file, cl_sm_fd_read_data() function.
It seems that Process1 has close the subscription conn between Process1 and sysrepo. 
```
if (SR_ERR_OK == rc) {
        rc = cl_sm_conn_in_buff_process(sm_ctx, conn);
        if (SR_ERR_OK != rc) {
            SR_LOG_WRN("Error by processing of the input buffer of fd=%d, closing the connection.", conn->fd);
            conn->close_requested = true;
        }
    }

    /* close the connection if requested */
    if (conn->close_requested) {
        cl_sm_conn_close(sm_ctx, conn);
        rc = SR_ERR_DISCONNECT;
    }
```
4. As a result, the Process1 won't recv any message from sysrepo when Process2 get state data.
Finally, In Process2, sr_get_item() returns "Timeout has expired"

**Expected behavior:**
1. When this problem arise, how can Process1 to check the subscription is normal? For the  subscription conn  is a internal implementation mechanism, Process1 doesn't know the conn is closed.
2. When "Unable to unpack the message" occurs, can we did not call function cl_sm_conn_close(sm_ctx, conn)? 

### Versions
Sysrepo version: `sysrepo daemon, version 0.7.4`.
libyang version: `yanglint 0.15.131`

Thanks!

**Comment by chunlovemail** [comment] 2018-07-11 06:10
Hi Michal,
    The output is as shown below:
```
APPS[1857]: [OPT][command][cmd_control.c:389] Get pd power +++++
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_fd_read_data:1213) recv+++++++++++++++++++
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1113) size: 2247
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1150) exit -----------------
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_fd_read_data:1213) recv+++++++++++++++++++
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1113) size: 51969
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1150) exit -----------------
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_fd_read_data:1213) recv+++++++++++++++++++
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1113) size: 70788
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1150) exit -----------------
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_fd_read_data:1213) recv+++++++++++++++++++
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1113) size: 618
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1150) exit -----------------
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_fd_read_data:1213) recv+++++++++++++++++++
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1113) size: 618
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1150) exit -----------------
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_fd_read_data:1213) recv+++++++++++++++++++
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1113) size: 561
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1150) exit -----------------
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_fd_read_data:1213) recv+++++++++++++++++++
sysrepo-CSManager[1661]: [INF] [140519666857728] (cl_sm_conn_in_buff_process:1113) size: 88471
sysrepo-CSManager[1661]: [ERR] [140519666857728] (cl_sm_conn_msg_process:1061) Unable to unpack the message (conn=0x7fcd3c001370).
sysrepo-CSManager[1661]: [ERR] [140519666857728] (cl_sm_conn_in_buff_process:1132) Error by processing of the message.
sysrepo-CSManager[1661]: [WRN] [140519666857728] (cl_sm_fd_read_data:1216) Error by processing of the input buffer of fd=13, closing the connection.
```
And When "Unable to unpack the message" occurs, can we did not call function cl_sm_conn_close(sm_ctx, conn)?

**Comment by michalvasko** [comment] 2018-07-11 07:14
Hi,
not very helpful, unfortunately. This is the first time I am seeing such an error so I would have to reproduce it to fix it. Can you describe what you are doing so that I can? Also, closing the connection is probably the right thing to do, because this is a fatal error.

Regards,
Michal

**Comment by jjin62** [comment] 2019-02-22 04:19
Michal,
In this case, should libsysrepo somehow to notify the client application (Process1) when fd is closed? Right now, application is not aware of the fd is closed. sr_session_check seems can not find out that fd is closed as well.

**Comment by michalvasko** [comment] 2019-02-22 07:28
Hi,
I suppose it should but this is a fatal error that should not ever happen so I would rather fix the cause than handle all the consequences. Do you have any new information regarding this issue, maybe a way to reproduce it?

Regards,
Michal

**Comment by sun5** [comment] 2019-09-26 07:13
Hi Michal,
   In my test environment, It can be reproduced very easily.
   Process1: create more than 1024 logic interface,eg:ipsec,vxlan
   Process2: use sr_dp_get_items_subscribe() function to subscribe the interface state.
   Process3:  use netopeer2-cli to get the all interface state, I will arise this problem in 10 times.
    sysrepod log below:

    [INF] Refresh session request running datastore
    [INF] No operation has been performed on this session so far
    [INF] Refresh session request running datastore
    [INF] No operation has been performed on this session so far
    [INF] Get items request running datastore, xpath: /ietf-interfaces:interfaces-state/interface//., offset: 0, limit: 100
    [ERR] Unable to unpack the message (conn=0x14f3a60).
    [ERR] Error by processing of the message.
    [WRN] Error by processing of the input buffer of fd=9, closing the connection.
    [INF] Closing the connection 0x14f3a60.
    [ERR] Time out waiting for operational data expired before all responses have been received, session id = 1770948395, req = 2389
    [INF] Get items request running datastore, xpath: /ietf-interfaces:interfaces-state/interface//., offset: 0, limit: 100

Versions
Sysrepo version:  version 0.7.7.
netopeer2-server 0.7.0
   
Best

**Comment by michalvasko** [comment] 2019-09-26 10:15
Hi,
that is quite a specific setup. The error
```
[ERR] Unable to unpack the message (conn=0x14f3a60).
```
seems like one that is non-trivial to fix, something with the protocol buffers. Since we now have new *sysrepo* in `devel` and are fairly close to it being officially released, I do not think it is worth it for me to spend possibly hours on trying to fix this problem. Sorry.

Regards,
Michal

**Comment by GuoyouZhang** [comment] 2020-01-07 13:14
Hi,
i have same issue.
is this issue fixed on version 1.3x?
BR,
guoyou

**Comment by michalvasko** [comment] 2020-01-07 13:19
Hi,
I hope it works fine there but even if it does not, I would make the effort to fix it.

Regards,
Michal

**Closed** 2020-01-08 13:40 UTC

**Comment by gunterw** [comment] 2020-07-27 11:17
Here's the change to fix this bug
```
diff --git a/sysrepo/src/clientlib/cl_subscription_manager.c b/sysrepo/src/clientlib/cl_subscription_manager.c
index 51f0c70..5005dcf 100644
--- a/sysrepo/src/clientlib/cl_subscription_manager.c
+++ b/sysrepo/src/clientlib/cl_subscription_manager.c
@@ -1134,7 +1134,7 @@ cl_sm_conn_in_buff_process(cl_sm_ctx_t *sm_ctx, cl_sm_conn_ctx_t *conn)
             /* invalid message size */
             SR_LOG_ERR("Invalid message size in the message preamble (%zu).", msg_size);
             return SR_ERR_MALFORMED_MSG;
-        } else if ((buff_size - buff_pos) >= msg_size) {
+        } else if ((buff_size - SR_MSG_PREAM_SIZE - buff_pos) >= msg_size) {
             /* the message is completely retrieved, parse it */
             SR_LOG_DBG("New message of size %zu bytes received.", msg_size);
             rc = cl_sm_conn_msg_process(sm_ctx, conn,
```

**Comment by michalvasko** [comment] 2020-07-27 11:31
Hi,
okay, could you provide a pull request? For the `legacy` branch.

Regards,
Michal
