### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1743] opened 2020-01-09 06:56 UTC
Hi Michal,

Do find a lot of changes that have been done in the new sysrepo code.
Would you please let me know what would be the best way to know all the changes?

Thank you in advance.

Regards,
Rosy

**Comment by michalvasko** [comment] 2020-01-09 07:50
Hi Rosy,
most important changes should be mentioned [here](https://github.com/sysrepo/sysrepo/blob/master/CHANGES). However, even I do not know all the changes anymore, there are way too many and I have lost track of all the things that did not work properly in the old *sysrepo*. 

Generally, it is best to read the whole documentation and docs for each function used. Also, if you have some existing applications, they should work after the referenced API changes are incorporated, they just may not be as efficient and coherent as intended.

Regards,
Michal

**Comment by andrei-pavel** [comment] 2020-01-09 10:54
Hello,

Could you add a link to your generated documentation in the README for those who are too lazy to generate it themselves? I always have a hard time finding it. I don't know how to reach it even from sysrepo.org main page.

I think it's this one: http://www.sysrepo.org/static/doc/html/index.html. Found it in an older issue. :man_shrugging: 

Best Regards,
Andrei

**Comment by michalvasko** [comment] 2020-01-09 11:01
Hi,
right, actually, it was already referenced in `devel` but I have merged it into `master` now.

Regards,
Michal

**Closed** 2022-05-27 13:05 UTC
