### ISSUE TITLE
Getting error during registration of sr_dp_get_items subscribe for ietf-system

### ISSUE THREAD

**Issue by rajnkamr** [sysrepo/sysrepo#437] opened 2016-10-19 07:07 UTC
I have ietf-system modules installed in sysrepo 
Any idea why this could happen

[DBG] Persist data successfully loaded from file '/etc/sysrepo/data/ietf-system.persist'.
[DBG] Persist data tree for given module is empty (xpath=/sysrepo-persistent-data:module[name='ietf-system']/subscriptions/subscription[type='dp-get-items'][destination-address='/var/run/sysrepo-subscriptions/ietf-system/27899.VQYnNs.sock'][destination-id='1733557809']).
[ERR] Unable to modify persist data tree.

**Comment by milanlenco** [comment] 2016-10-20 11:32
Hi Rajnish,
is this error causing your application to fail, i.e. is it a fatal error? Because I believe this actually happens in the call to unsubscribe, so it shouldn't be critical. Anyway, there is a chance that it was fixed in the latest set of commits to master. Could you please update your local copy of the master branch, re-compile and re-try if the issue still exist?
If it is still present, could you please provide full log?

Thank you,
Milan

**Comment by lukasmacko** [comment] 2016-10-31 08:35
@rajnkamr can you reproduce this with the latest master branch?

**Closed** 2016-11-02 07:05 UTC
Labels: unreproducible
