### ISSUE TITLE
How to solve the problem  List key not found or on incorrect position when using sr_rpc_subscribe

### ISSUE THREAD

**Issue by Elijah123-a** [sysrepo/sysrepo#2222] opened 2020-11-18 10:15 UTC
Hi,
Michal Vasko
  Recently, I encountered some problems about using the SR function. This container has a key and eight leaf nodes. When I use sr_rpc_subscribe This error occurs when subscribing to the function。

[ERR]: List key not found or on incorrect position ("alarm-serial-no='1']/object-type").

Look forward to your reply！
by-Elijah

**Comment by michalvasko** [comment] 2020-11-18 10:57
Please provide the code snippet of you subscribing and the YANG module.

**Comment by Elijah123-a** [comment] 2020-11-18 12:02
`yang`

` 
grouping data {
        description
            "common parameters for an data.";
        leaf object-name {
            mandatory true;
            type string {
                length "1..64";
            }
            description "data object-name";
        }
        leaf object-type {
            mandatory true;
            type string {
                length "1..64";
            }
            description "data object-type";
        }
        leaf alarm-code {
            mandatory true;
            type string {
                length "1..64";
            }
            description "data alarm-code";
        }
        leaf alarm-serial-no {
            mandatory true;
            type uint64;
            description "data alarm-serial-no";
        }
    }
grouping datas {
        list data {
            key 'alarm-serial-no';
            config false;
            uses data;
            description "datas list";
        }
        description "datas";
    }
container datas {
        uses datas;
        description "datas container";
    }   
rpc get-datas {
        description "get-datas";
        input {
            leaf start-time {
                type yang:date-and-time;
                description "start-time";
            }
            leaf end-time {
                type yang:date-and-time;
                description "end-time";
            }
        }
        output {
            container datas {
                uses datas;
                description "output datas";
            }
        }
    }

`

**Comment by Elijah123-a** [comment] 2020-11-18 12:14
c
static int
rpc_cb_get_rpc_data(sr_session_ctx_t *session, const char *path, const sr_val_t *input, const size_t input_cnt,
        sr_event_t event, uint32_t request_id, sr_val_t **output, size_t *output_cnt, void *private_data)
{
    size_t i;

    (void)session;
    (void)event;
    (void)request_id;
    (void)private_data;

    printf("\n\n ========== RPC \"%s\" RECEIVED: =======================\n\n", path);
    for (i = 0; i < input_cnt; ++i) {
        print_val(&input[i]);
    }

    if (!strcmp(path, "/rpc-test-module:get-rpc-data")) {
        /* generate some output */
    *output_cnt = 3;
    *output = calloc(3, sizeof **output);
    printf("========================start\n");

	(*output)[0].xpath = strdup("data:get-datas/datas/data[alarm-serial-no='1']/alarm-serial-no");
    (*output)[0].type = SR_UINT64_T;
    (*output)[0].dflt = 0;
    (*output)[0].data.uint64_val = 1;

	(*output)[1].xpath = strdup(""data:get-datas/datas/data[alarm-serial-no='1']/object-name");
 (*output)[1].type = SR_STRING_T;
    (*output)[1].dflt = 0;
    (*output)[1].data.string_val = strdup("A");

(*output)[2].xpath = strdup(""data:get-datas/datas/data[alarm-serial-no='1']/object-type");
 (*output)[2].type = SR_STRING_T;
    (*output)[2].dflt = 0;
    (*output)[2].data.string_val = strdup("B");

	


	printf("========================end\n");
    }

    return SR_ERR_OK;
}``

**Comment by michalvasko** [comment] 2020-11-18 13:38
Please post the `sr_rpc_subscribe` call code, not the callback.

**Comment by Elijah123-a** [comment] 2020-11-18 13:53
My fault，Here is my code
`int
main(int argc, char **argv)
{
    sr_conn_ctx_t *connection = NULL;
    sr_session_ctx_t *session = NULL;
    sr_subscription_ctx_t *subscription = NULL;
    int rc = SR_ERR_OK;

    /* turn logging on */
    sr_log_stderr(SR_LL_WRN);

    /* connect to sysrepo */
    rc = sr_connect(0, &connection);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* start session */
    rc = sr_session_start(connection, SR_DS_RUNNING, &session);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* subscribe for the RPC */
    rc = sr_rpc_subscribe(session, "/data:get-datas", rpc_cb_get_rpc_data, NULL, 0, 0, &subscription);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    printf("\n\n ========== LISTENING FOR RPC ==========\n\n");

    
    printf("Application exit requested, exiting.\n");

cleanup:
    sr_disconnect(connection);
    return rc ? EXIT_FAILURE : EXIT_SUCCESS;
}`

**Comment by Elijah123-a** [comment] 2020-11-18 14:15
To facilitate the discussion, I simplified the Yang file node

**Comment by Elijah123-a** [comment] 2020-11-18 14:17
Now the problem is that the third output node has this problem

**Comment by michalvasko** [comment] 2020-11-19 09:02
Okay, can you please at least paste the updated message? Since the module is different now.

**Comment by Elijah123-a** [comment] 2020-11-19 11:33
Here are the errors that occurred
[ERR]: List key not found or on incorrect position ("D='1']/B").

**Comment by michalvasko** [comment] 2020-11-20 14:52
I did not manage to reproduce the problem but I encountered a similar one, with the same cause, I think. That lies in the key `D` not being the first node in the schema (grouping `data`), which confuses *libyang*. If you can, then adjust the YANG so that it is. If not, you should be able to get around this by using positional predicates instead of list keys when creating the nodes. For example, instead of
```
/test:get-datas/datas/data[D='1']/D
```
use
```
/test:get-datas/datas/data[1]/D
```
and it should work, for all the xpaths. Also, this problem should be correctly fixed in the almost finished *libyang* version 2 so we will not be fixing it in the current version.

**Comment by Elijah123-a** [comment] 2020-11-21 07:04
According to your suggestion, I modified the location of D and output it according to Yang file location, but it has other problems as follows

my output
`(*output)[0].xpath = strdup("/data:get-datas/datas/data[1]/A");
     (*output)[1].type = SR_STRING_T;
    (*output)[0].dflt = 0;
    (*output)[1].data.string_val = strdup("A");

	(*output)[1].xpath = strdup(""/data:get-datas/datas/data[1]/B");
 (*output)[1].type = SR_STRING_T;
    (*output)[1].dflt = 0;
    (*output)[1].data.string_val = strdup("B");

(*output)[2].xpath = strdup(""/data:get-datas/datas/data[1]/C");
 (*output)[2].type = SR_STRING_T;
    (*output)[2].dflt = 0;
    (*output)[2].data.string_val = strdup("C");`

then Something went wrong
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        path:     /data:get-datas/datas/data
        message:  Missing required element "B" in "data".

        type:     application
        tag:      operation-failed
        severity: error
        message:  RPC output validation failed.

**Comment by michalvasko** [comment] 2020-11-21 08:35
If you move the key `D` to be the first node in the grouping, this code works fine:
```C
        (*output)[0].xpath = strdup("/test:get-datas/datas/data[D='1']/A");
        (*output)[0].type = SR_STRING_T;
        (*output)[0].dflt = 0;
        (*output)[0].data.string_val = strdup("A");

        (*output)[1].xpath = strdup("/test:get-datas/datas/data[D='1']/B");
        (*output)[1].type = SR_STRING_T;
        (*output)[1].dflt = 0;
        (*output)[1].data.string_val = strdup("B");

        (*output)[2].xpath = strdup("/test:get-datas/datas/data[D='1']/C");
        (*output)[2].type = SR_STRING_T;
        (*output)[2].dflt = 0;
        (*output)[2].data.string_val = strdup("C");
```

**Comment by Elijah123-a** [comment] 2020-11-21 09:10
Thank you very much for your help. Now I can get the output I want successfully

**Closed** 2020-11-21 10:19 UTC
