### ISSUE TITLE
Notification failing with leaf of type leafref to operational data, even after setting operational data value

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2419] opened 2021-05-17 07:57 UTC
Hi,

While sending a notification with two leafs, one of them with type leafref to an operational data leaf, getting below error, after setting the operational data for leafref.

Operational data write : 
/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers[name='TX-Ca0']/name
/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers[name='TX-Ca0']/state 
 
Notification : 
/o-ran-uplane-conf:tx-array-carriers-state-change/tx-array-carriers-notif[name='TX-Ca0']/name
/o-ran-uplane-conf:tx-array-carriers-state-change/tx-array-carriers-notif[name='TX-Ca0']/state

Error : 
sysrepo/src/edit_diff.c:2692: sr_diff_apply_r: 
Assertion `((diff_node->schema->nodetype & (LYS_LIST | LYS_LEAFLIST)) && (diff_node->schema->flags & 0x02)) || (!sr_edit_find(*first_node, diff_node, op, 0, ((void *)0), 0, &match, ((void *)0)) && !match)' failed.
 
 
 Please suggest if we are doing something wrong.

**Comment by michalvasko** [comment] 2021-05-17 08:49
Please provide all the YANG modules, data, and exact steps to reproduce this. A failed assert is always a problem in the code.

**Comment by ankit7gup** [comment] 2021-05-17 09:07
Hi Michal,

Attached are the yang modules being used and the sequence to load them is present in module_load.sh

Steps to reproduce:
1. ru_specific_models\operations\o-ran-uplane-conf.yang has got notification with below details:


grouping tx-array-notification-group {
    description
      "Grouping for tx-array for notification";

    list tx-array-carriers-notif{
      key name;
      max-elements 1;
      description "notification of state change for tx-array-carriers";

      leaf name{
        type leafref{
          path "/user-plane-configuration/tx-array-carriers/name";
        }
        description
          "name of tx-array-carriers is notified at state change";
      }
      leaf state{
        type leafref{
          path "/user-plane-configuration/tx-array-carriers/state";
        }
      description
        "state of tx-array-carriers is notified at state change";
      }
    }
  }



 notification tx-array-carriers-state-change {
    description
      "Notification used to inform about state change of tx-array-carriers";
    uses tx-array-notification-group;
  }


2. Set the leafref operational data in DB, using modified version of sr_set_item_example. 
Modifications done:
a. Write data in operational DB. 
b. Application should not exit for the operational data to remain in DB.

3.  Send notification for the specified data using notif_send_example

./notif_send_example /o-ran-uplane-conf:tx-array-carriers-state-change /o-ran-uplane-conf:tx-array-carriers-state-change/tx-array-carriers-notif[name='TX-Ca0']/state BUSY

**Comment by ankit7gup** [comment] 2021-05-18 12:09
Hi Michal,

Any update on this?

Thanks!

**Comment by michalvasko** [comment] 2021-05-18 15:06
I am quite busy, you must be patient. But I tried it now with *libyang*/*sysrepo* `devel` and it worked fine, the notification was sent and even received. So either it was fixed (depends on what version are you using) or there is something else affecting this.

**Comment by ankit7gup** [comment] 2021-05-19 07:28
Hi Michal,

I had taken the latest devel branch changes for libyang and sysrepo and tested again. Seems like the notification works sometimes and sometimes it fails.

I ran 10 iterations, Out of that it failed once with below error.

 /home/ankit/sysrepo/src/edit_diff.c:2703: sr_diff_apply_r: Assertion `((diff_node->schema->nodetype & (LYS_LIST | LYS_LEAFLIST)) && (diff_node->schema->flags & 0x02)) || (!sr_edit_find(*first_node, diff_node, op, 0, ((void *)0), 0, &match, ((void *)0)) && !match)' failed.
 
 
 Some additional info that might help here is, we are writing to operational db the respective data before sending this notification. Also getting below mentioned logs in that process.
 
[INF]: Recovering module "o-ran-uplane-conf" stored operational data of CID 241.
[INF]: Recovering module "o-ran-uplane-conf" stored operational data of CID 241.

 Thanks!

**Comment by michalvasko** [comment] 2021-05-19 10:38
I see. That will make it much more difficult to fix and you will simply have to provide the use-case with more details before I can reproduce it. Best is a simple stand-alone example. As for the recovery messages, it is most likely the result of previous crashes (failed asserts).

**Comment by michalvasko** [comment] 2021-05-20 09:20
It did provide more information but mostly added to my confusion. You have cut the backtrace at the most interesting point, where exactly is `sr_event_notif_send()` called? Is it perhaps in another *sysrepo* callback?

**Comment by ankit7gup** [comment] 2021-05-20 11:31
I am calling sr_event_notif_send() from my application which is further getting called after getting passed from multiple function calls.
Sharing the complete backtrace details this time. Hope this helps.

[bt_full_logs_updated.txt](https://github.com/sysrepo/sysrepo/files/6515499/bt_full_logs_updated.txt)

**Comment by michalvasko** [comment] 2021-05-20 14:47
Okay, so that was not it. Then I have another idea. It seems you have one process that is sending the notification and another that is changing the stored operational data. Are there other processes running simultaneously and calling some *sysrepo* functions? Such as changing the running configuration? Or subscribing/unsubscribing to running data changes?

**Comment by michalvasko** [comment] 2021-05-21 07:57
Then it is most likely caused by some missing locks on running or operational datastore. This is also supported by the fact that you do not reproduce it every time. I think that fixing this would not be trivial and so I would prefer to leave it the way it is, sorry. Reason being that the whole principle on which push operational data work is a bit unfortunate and have caused several problems already. And I have changed it in the new `libyang2` versions, which are almost ready to be released.

So, my advice would be to either add the locks yourself, which should be quite trivial. Just synchronize subscribing for `running` changes and changing stored `operational` data. Or, you can already switch to using the new `libyang2` branches of all the projects.

**Comment by ankit7gup** [comment] 2021-05-21 08:29
Hi Michal, Going by your advice, I want to try with libyang2 branch.
However getting below error while cmake for libyang using libyang2 branch.


You have called ADD_LIBRARY for library plugin_invalid without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at tests/plugins/CMakeLists.txt:11 (target_sources):
  Unknown CMake command "target_sources".
Call Stack (most recent call first):
  tests/plugins/CMakeLists.txt:17 (ly_add_plugin)


-- Configuring incomplete, errors occurred!

**Comment by michalvasko** [comment] 2021-05-21 08:32
> Hi Michal, Going by your advice, I want to try with libyang2 branch.

Great, some more testing before the release is appreciated (and is needed as you can see).

As for the error, what `cmake` version are you using? I have seen the warning before, which is harmless, but not the error.

**Comment by ankit7gup** [comment] 2021-05-21 08:35
[root@romulus build]# cmake --version
cmake version 2.8.12.2

**Comment by michalvasko** [comment] 2021-05-21 08:56
Okay, should be fixed now. Please create separate *libyang* issues if you encounter any more problems.

**Comment by ankit7gup** [comment] 2021-05-21 08:57
Sure, Thanks!

**Comment by ankit7gup** [comment] 2021-05-21 09:00
Got another problem now, Created new issue under libyang for the same.

**Closed** 2021-06-04 05:38 UTC
Labels: is:bug, status:wontfix
