### ISSUE TITLE
Fix python3 example

### ISSUE THREAD

**Issue by plajjan** [sysrepo/sysrepo#391] opened 2016-10-07 09:24 UTC
The documentation on http://www.sysrepo.org/bindings/python3 shows how one can build the py3 libs but trying to do that on devel_20161005 doesn't work;

I followed the steps precisely. I am using a later docker image since I need the datastore-lock-fix.

relevant part from `cmake -DGEN_PYTHON_VERSION=3 ..`:
```
...
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6")
-- Lua version 5.1 was selected
-- Found Lua51: /usr/lib/x86_64-linux-gnu/liblua5.1.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.1.5")
-- Python version 3 was selected
-- Could NOT find PythonLibs: Found unsuitable version "2.7.6", but required is at least "3" (found /usr/lib/x86_64-linux-gnu/libpython2.7.so)
CMake Warning at swig/CMakeLists.txt:50 (message):
  Did not found Python version 3.x
```

**Comment by rastislavszabo** [comment] 2016-10-07 11:22
@mislavn Can you please take a look? It seems like the python3 is not actually installed in the docker image.

**Comment by plajjan** [comment] 2016-10-07 11:44
I'm trying to use python2 in the meantime but it doesn't seem to work either. The example does an import https://github.com/sysrepo/sysrepo/blob/master/swig/python2/examples/pytho2_application_changes_example.py#L29 which won't work because it's not installed. There's a SysrepoWrappers library - is that the one that should be used?

I suppose the same would eventually become an issue for py3 as well since the py libs need to be installed in the right places.

**Comment by plajjan** [comment] 2016-10-07 11:48
I see some examples, like https://github.com/sysrepo/sysrepo/blob/7a8ec67d2bcde48eec2b098f6f16dda1e7eb34a6/tests/python/SubscriptionTest.py, that use SysrepoWrappers instead. Is this a newer, better and shinier python lib? Without having looked much at it, it does appear a bit more pythonic and more high level.

**Comment by plajjan** [comment] 2016-10-07 12:24
make install in the build_python dir does this:
```
Install the project...
-- Install configuration: "debug"
-- Up-to-date: /opt/dev/sysrepo/build_python2/repository
-- Up-to-date: /opt/dev/sysrepo/build_python2/repository/yang/
-- Up-to-date: /opt/dev/sysrepo/build_python2/repository/data/
-- Up-to-date: /opt/dev/sysrepo/build_python2/repository/data/internal/
-- Up-to-date: /tmp/sysrepo-subscriptions
-- Up-to-date: /usr/local/lib/sysrepo/plugins
-- Installing: /opt/dev/sysrepo/build_python2/repository/yang/internal/sysrepo-persistent-data.yang
-- Installing: /opt/dev/sysrepo/build_python2/repository/yang/internal/sysrepo-module-dependencies.yang
-- Up-to-date: /usr/local/lib/python2.7/dist-packages/_sysrepoPy.so
-- Up-to-date: /usr/local/lib/python2.7/dist-packages/sysrepoPy.py
-- Up-to-date: /usr/local/lib/python2.7/dist-packages/SysrepoWrappers
-- Up-to-date: /usr/local/lib/python2.7/dist-packages/SysrepoWrappers/Sysrepo.py
-- Up-to-date: /usr/local/lib/python2.7/dist-packages/SysrepoWrappers/Session.py
-- Up-to-date: /usr/local/lib/python2.7/dist-packages/SysrepoWrappers/Value.py
-- Up-to-date: /usr/local/lib/python2.7/dist-packages/SysrepoWrappers/__init__.py
-- Up-to-date: /usr/local/lib/python2.7/dist-packages/SysrepoWrappers/Iter.py
-- Up-to-date: /usr/local/lib/pkgconfig/libsysrepo.pc
-- Up-to-date: /usr/local/share/man/man1/sysrepoctl.1
-- Up-to-date: /usr/local/share/man/man1/sysrepocfg.1
-- Up-to-date: /usr/local/lib/libsysrepo.so
-- Up-to-date: /usr/local/lib/libsysrepo.a
-- Up-to-date: /usr/local/lib/libsysrepo-engine.so
-- Up-to-date: /usr/local/lib/libsysrepo-engine.a
-- Up-to-date: /usr/local/bin/sysrepod
-- Up-to-date: /usr/local/bin/sysrepo-plugind
-- Up-to-date: /usr/local/bin/sysrepoctl
-- Up-to-date: /usr/local/bin/sysrepocfg
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/sysrepo
-- Up-to-date: /usr/local/include/sysrepo/xpath.h
-- Up-to-date: /usr/local/include/sysrepo/trees.h
-- Up-to-date: /usr/local/include/sysrepo/values.h
-- Up-to-date: /usr/local/include/sysrepo/plugins.h
-- Up-to-date: /usr/local/include/sysrepo.h
-- Exec: /opt/dev/sysrepo/build_python2/src/sysrepoctl --install --yang=/opt/dev/sysrepo/examples/yang/turing-machine.yang --permissions=666
-- Exec: /opt/dev/sysrepo/build_python2/src/sysrepocfg --import=/opt/dev/sysrepo/examples/yang/turing-machine.data.xml --datastore=startup --format=xml --level=0 turing-machine
-- Exec: /opt/dev/sysrepo/build_python2/src/sysrepoctl --install --yang=/opt/dev/sysrepo/examples/yang/iana-if-type.yang --permissions=666
-- Exec: /opt/dev/sysrepo/build_python2/src/sysrepoctl --install --yang=/opt/dev/sysrepo/examples/yang/ietf-ip@2014-06-16.yang --permissions=666
-- Exec: /opt/dev/sysrepo/build_python2/src/sysrepoctl --install --yang=/opt/dev/sysrepo/examples/yang/ietf-interfaces@2014-05-08.yang --permissions=666
-- Exec: /opt/dev/sysrepo/build_python2/src/sysrepocfg --import=/opt/dev/sysrepo/examples/yang/ietf-interfaces.data.xml --datastore=startup --format=xml --level=0 ietf-interfaces
-- Up-to-date: /usr/local/lib/sysrepo/plugins/libturing-machine.so
-- Up-to-date: /usr/local/lib/libSysrepo-cpp.so
-- Up-to-date: /usr/local/bin/libSysrepo_Lua.so
```
so sysrepoPy is installed but not libsysrepoPython2. Should it be?

It also installs yang models that I don't want.. since the makefile is auto-generated it's difficult understanding what make targets I have available to me.

**Comment by lukasmacko** [comment] 2016-10-07 12:57
Hi,

actualy the SysrepoWrappers is small "library" build on older bindings generated `swig/python directory`. The older bindings were intended to be used only for internal [test](https://github.com/sysrepo/sysrepo/tree/7a8ec67d2bcde48eec2b098f6f16dda1e7eb34a6/tests/python) purposes. The main drawback of these binding is that callbacks are not supported. 

@mislavn has created new python bindings `swig/python2` and `swig/python3` generated from cpp where the callbacks works and we plan to use them in the future and remove the old ones.

Regards,
Lukas

**Comment by plajjan** [comment] 2016-10-07 13:01
Ok, so I should forget about SysrepoWrappers then.. I actually hacked together so I use libsysrepoPython2 now by just copying the files to the correct place in /usr/lib/python.... like I mentioned, I think there should be a make target that does that for me :)

**Comment by lukasmacko** [comment] 2016-10-07 13:34
two more things the install target is missing for python2 bindings @mislavn please add it
if you do not want to have those example yang installed [turn off the examples](https://github.com/sysrepo/sysrepo/blob/master/INSTALL.md#building-with--without-examples)

**Comment by mislavn** [comment] 2016-10-07 16:19
Hi,

Python3 is actually installed:

```
Python 3.4.3 (default, Sep 14 2016, 12:36:27) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

The problem is in the cmake file and only in Ubuntu, it is similar to:

https://bugs.launchpad.net/ubuntu/+source/cmake/+bug/1323559

I had a temporary fix by adding to the docker cmake file findpython from Arch Linux.
I did not yet managed to find a proper solution without manually copying the cmake file. I would like to have a singular docker file without additional files in the github repository.

If I do not manage to fix this next week, in the worst case I will add the cmake file with the docker command "COPY".

Regards,
Mislav

**Comment by mislavn** [comment] 2016-10-07 16:42
Hi,

I add the targets to python bindings.

Because of conflict with the pull requuest:
https://github.com/sysrepo/sysrepo/pull/383

I add the patch to that pull request.

Regards,
Mislav

**Comment by rastislavszabo** [comment] 2016-10-10 12:31
> The problem is in the cmake file and only in Ubuntu, it is similar to: https://bugs.launchpad.net/ubuntu/+source/cmake/+bug/1323559

Maybe basing the docker image on ubuntu:16.04 instead of 14.04 would solve the issue?

**Comment by mislavn** [comment] 2016-10-10 12:35
I fixed this in:

https://github.com/sysrepo/sysrepo/pull/399

**Comment by rastislavszabo** [comment] 2016-10-11 11:37
@mislavn Is there anything else that needs to be fixed within this bug report, or can we close this?

**Comment by mislavn** [comment] 2016-10-11 11:47
We can close it.

**Closed** 2016-10-11 11:48 UTC
Labels: bug

**Comment by plajjan** [comment] 2016-10-14 09:28
I'm confused by how this should now work. What steps do I need to take to get libsysrepoPython2 in my PYTHONPATH ? When I now look at the output of my build directory I have this:
```
root@c3ff54f4e84f:/opt/dev/sysrepo/build_python2# find swig
swig
swig/python
swig/python/_sysrepoPy.so
swig/python/sysrepoPyPYTHON_wrap.c
swig/python/sysrepoPy.py
swig/lua
swig/lua/sysrepoLuaLUA_wrap.c
```

did the lib just change name from "libsysrepoPython2" to "sysrepoPy" ? Am I missing options to cmake (it now complains over GEN_PYTHON_VERSION).

**Comment by plajjan** [comment] 2016-10-14 09:28
And shouldn't this mean http://www.sysrepo.org/bindings/python3 needs an update?

**Comment by mislavn** [comment] 2016-10-14 09:46
> And shouldn't this mean http://www.sysrepo.org/bindings/python3 needs an update?

I have updated the example on sysrepo.org, the asciinema video I will update later.

> I'm confused by how this should now work. What steps do I need to take to get libsysrepoPython2 in my PYTHONPATH ? When I now look at the output of my build directory I have this:

> root@c3ff54f4e84f:/opt/dev/sysrepo/build_python2# find swig
> swig
> swig/python
> swig/python/_sysrepoPy.so
> swig/python/sysrepoPyPYTHON_wrap.c
> swig/python/sysrepoPy.py
> swig/lua
> swig/lua/sysrepoLuaLUA_wrap.c

> did the lib just change name from "libsysrepoPython2" to "sysrepoPy" ? Am I missing options to cmake (it now complains over GEN_PYTHON_VERSION).

That is the output of the old python2 bindnigs, we are curretly migrating the python2 unit tests from the old python2 bindings to the new ones. Once that is finished we will delete the old bindings.

In order to use the python bindings simply execute the command:

`make install`

For python2 the most important files that get copied are:

```
-- Installing: /usr/lib/python2.7/dist-packages/_libsysrepoPython2.so
-- Installing: /usr/lib/python2.7/dist-packages/libsysrepoPython2.py
-- Installing: /usr/lib/libSysrepo-cpp.so
```

and for python3 they are:
```
-- Installing: /usr/lib/python3/dist-packages/_libsysrepoPython3.so
-- Installing: /usr/lib/python3/dist-packages/libsysrepoPython3.py
-- Installing: /usr/lib/libSysrepo-cpp.so
```

I hope this answers your question.

**Comment by plajjan** [comment] 2016-10-14 10:00
I think the docker tag refers to the wrong tag on the wiki page, right?

With devel_20161012 it seems to work correctly! :)

**Comment by mislavn** [comment] 2016-10-14 10:04
> I think the docker tag refers to the wrong tag on the wiki page, right?

With devel_20161012 it seems to work correctly! :)

Great that it works now.
I will fix the docker tag too when the asciinema video is finished.
