### ISSUE TITLE
Delete operation on operational on a leaf-list element in a module container tagged with config false does nothing

### ISSUE THREAD

**Issue by LeandreBl** [sysrepo/sysrepo#3174] opened 2023-10-04 12:33 UTC
Hi,

I've been running in a problem, whenever I have a `leaf-list` (of `string` for the example) inside a `container` tagged with `config false;`, any delete operation on a leaf-list element ends up doing absolutely nothing.

- libyang 2.40.4 (branch devel)
- libsysrepo 7.19.12 (branch devel)

### How to reproduce
- Install libyang
  * git clone https://github.com/CESNET/libyang.git
  * cd libyang
  * mkdir build
  * cd build
  * cmake ..
  * make install -j
- Install sysrepo/libsysrepo
  * git clone https://github.com/sysrepo/sysrepo.git
  * cd sysrepo
  * mkdir build
  * cd build
  * cmake ..
  * make install -j
> (For this example I'll use sysrepo-python, so you need to install it `pip install sysrepo`)
- Create a `test.yang` file with:
```yang
module test-module {
  yang-version 1.1;
  namespace "http://example.com/test-module";
  prefix test;

  container container {
    config false;
    leaf-list string-list {
        type string;
        description "a dummy string";
    }
  }
}
```
- Install the `test.yang` module
  * `sysrepoctl -i test.yang`

- Create a little python script to manipulate the operational datastore
  * manage_operational.py
```py
#!/usr/bin/env python3

import sysrepo
import sys
import os

conn = sysrepo.connection.SysrepoConnection()
ds = 'operational'
session = conn.start_session(ds)
print("connected")

while True:
    try:
        s = input("'action xpath': ")
    except:
        break
    try:
        command = s.split(' ')
        while len(command) != 3:
            command.append('')
        action, xpath, value = command
        if action == 'get':
            values = session.get_items(xpath, no_subs=True)
            for value in values:
                print(value)
        elif action == 'delete':
            session.delete_item(xpath)
            session.apply_changes()
        elif action == 'set':
            session.set_item(xpath, value)
            session.apply_changes()
        elif action == 'quit':
            break
    except Exception as e:
        print(f'{s}: {e}')
```
```
This script gives 3 commands:
- get <xpath>
- delete <xpath>
- set <xpath> <value>
```

- Run the `manage_operational.py` script
  * `python3 manage_operational.py`

- Create leaf-list elements from `manage_operational.py` CLI
  * `> set /test-module:container/string-list test_value1`
  * `> set /test-module:container/string-list test_value2`
  * `> set /test-module:container/string-list test_value3`

- See if elements are created
  * `> get /test-module:container/string-list` or `sysrepocfg --export -d operational`

- We can see 3 elements now, `test_value1`, `test_value2` and `test_value3`

- Delete one of them from `manage_operational.py` CLI
  * `> delete /test-module:container/string-list[.='test_value1']`

- See if element is deleted
  * `> get /test-module:container/string-list` or `sysrepocfg --export -d operational`
 
- It's still there :'(

> Note that THIS EXACT same deletion works if `config false;` is not present in the `test.yang` file.

### Origin of the behavior
In `sr_delete_item` the deletion node `operation`:`remove` is added correctly in the edit tree.
In `sr_apply_changes`, in `sr_edit_merge_r`, the function tries to find the `trg_node` with `sr_edit_find_match`.
In `sr_edit_find_match`, sysrepo uses the macro `lysc_is_dup_inst_list`
```c
#define lysc_is_dup_inst_list(lysc_node) \
    ((lysc_node && (((lysc_node->nodetype == LYS_LIST) && (lysc_node->flags & LYS_KEYLESS)) || \
            ((lysc_node->nodetype == LYS_LEAFLIST) && !(lysc_node->flags & LYS_CONFIG_W)))) ? 1 : 0)
```
As you can see, this define does not return 1 if the leaf-list is not in a container flagged with `LYS_CONFIG_W`
This flag is set with `config true;`.

This behavior seems pretty strange, it might be me not understanding the correct behavior of `config false;` on `operational` but we do not want to change it in our yang file.

What do you think ?

**Comment by michalvasko** [comment] 2023-10-09 07:58
I believe this behaves as intended, read more about the [push operational data](https://netopeer.liberouter.org/doc/sysrepo/devel/html/index.html#oper_data) to understand.

**Comment by LeandreBl** [comment] 2023-10-09 08:38
It's quite strange as it is written that the "remove" operation is handled, I can remove a node, or anything else, but not a leaf-list element, the goal of the operational state is to be updated upon change, and only update what changed, instead of pushing the whole tree again, but here the only workaround is to delete the entire leaf-list and then push a whole new one, isn't that what we don't want to do ?

**Comment by michalvasko** [comment] 2023-10-10 07:31
Okay, I thought that Python works differently and misunderstood the behavior. Anyway, while the API is almost identical when editing `running` and `operational` datastores, internally it works completely differently and your leaf-list removal never did anything. Without going into much details, you cannot use values to identify state leaf-list instances because there can be duplicates, you must use absolute instance positions. Sysrepo should now correctly print an error if you do not.

**Comment by LeandreBl** [comment] 2023-10-10 08:20
I can totally remove a leaf-list element by value, it's what I'm doing on running and on operational with `config true;`
The deletion with `xpath/list[.='value']` works on operational on a node with `config = true`. That's why the behavior seems strange for config: false.

**Comment by michalvasko** [comment] 2023-10-10 11:55
Like I said, state leaf-lists can have duplicate instances which is the exact reason you cannot use values for identifying them, you have to use the absolute position instead. More general information in the [docs](https://netopeer.liberouter.org/doc/sysrepo/devel/html/index.html#oper_data).

It works, I have added an explicit test for it (but you may have an old version of *sysrepo*, use the current `devel`). However, I believe you are using the wrong function and should be using [`sr_discard_items()`](https://netopeer.liberouter.org/doc/sysrepo/devel/html/group__edit__data__api.html#ga3c93aa25830a13af79add17e3269f9d4) instead. It removes previous edits from the push oper data, which is what you most likely want to do.

**Comment by LeandreBl** [comment] 2023-10-10 16:01
It's absolutely possible as we use the python binding and it does not seem to me that there is the discard_item wrapper. If we need it we'll probably make a pull request accordingly.

**Comment by LeandreBl** [comment] 2023-10-11 13:36
I'm putting it here, but i'm investigating too, On branch devel, I can only delete one leaf-list item per session, and even if I delete with `xpath/leaf-list[2]` it deletes the first element.
It's not on the given example, but on our project one, I'm trying to follow the code path.

**Comment by LeandreBl** [comment] 2023-10-11 14:52
The `sr_discard_items` does not work either on our tree (I tried in C without the bindings to be sure), I'll dig a bit.

**Comment by michalvasko** [comment] 2023-10-12 07:21
What exactly is your use-case? `sr_discard_items()` works only for push oper data that were previously set by your connection. If they appear in the `operational` datastore from another source (another connection (application), copied from `running`), you cannot use this function and must use `sr_delete_item()`. You have chosen pretty much the most complex use-case of deleting state leaf-lists using push oper data and, frankly, it is best to be avoided because it is difficult to get right.

But if you think it really does not work as it should, you need to provide the **exact** use-case (not some Python examples) for me to reproduce, all the details matter for this issue.

**Comment by samuel-gauthier** [comment] 2023-10-12 08:03
Hi Michal,

We were initially using only the pull state versioning our management daemon. To improve the performance and avoid putting too much stress on this management daemon, we have started to use push state for the data that does not change often, or that is known to change on events (systemd services, network interfaces mostly).

We maintain a cache of the state. On one side, we have a loop waiting on an event, that will, when unlocked, create a session in the operational datastore and push the state cache. As you know, the 'replace' operation is not supported anymore by the sr_edit_batch function, but it is what we need to do.
So we mimic the 'replace' operation by querying the current datastore state, diffing with our cached state, applying the diff to remove the elements that are in the datastore but not in our cache, and using the 'merge' operation for the rest.

I followed your advice from issue #2891 where things are explained maybe more clearly. This works very well, expect that when we have leaflists to remove in the changes, it doesn't. Léandre is in charge of resolving this problem.

Here is the code doing this replace (sorry, it is python).
A new session is allocated for each call to this function, and the sessions are originated from the same connections.
 ```
       with session.get_ly_ctx() as ctx:
            module = ctx.get_module('vrouter')
        with session.get_data_ly(
                '/vrouter:state',
                no_config=True,
                no_subs=True,
                timeout_ms=60000,
        ) as data:
            state_data = module.parse_data_dict(
                state_cache,
                no_state=False,
                strict=self.strict_state,
                validate=False)
            diffs = None
            try:
                diffs = data.diff(state_data)
                if diffs:
                    for diff in diffs.iter_tree():
                        if diff.meta().get('operation', 'unknown') != 'delete':
                            continue
                        value = None
                        if diff.schema().nodetype() in (
                                SNode.LEAF,
                                SNode.LEAFLIST,
                                SNode.ANYXML,
                                SNode.ANYDATA
                        ):
                            value = diff.value()
                        session.delete_oper_item(diff.path(), value)
                    session.apply_changes()
            finally:
                if diffs:
                    diffs.free()
                state_data.free()
        session.edit_batch(
            state_cache, 'vrouter',
            strict=self.strict_state, default_operation='merge')
        session.apply_changes()
```

Regards,
Samuel

**Comment by michalvasko** [comment] 2023-10-12 11:29
> So we mimic the 'replace' operation by querying the current datastore state, diffing with our cached state, applying the diff to remove the elements that are in the datastore but not in our cache, and using the 'merge' operation for the rest.

I do not like this, the application should know what its previous state was and not having to query it and make a diff. But, without much trouble, you should be fine with **discarding** all the previous state and simply setting the new state, saves you making the diff, which is then made internally in *sysrepo*. Still, this only works if the same application keeps updating some data, if there are more of them that affect the same operational data then it is not supported and a wrong design, an application should report its own state.

**Comment by samuel-gauthier** [comment] 2023-10-12 12:29
Well, that's perfect, we have an equivalent of the 'replace' that we needed in our initial use case.
We will test it more thoroughly, but it looks promising.

As a side note, calling sr_discard_items before sr_edit_batch does not seem to work (I get this error: There are already some session changes.: Operation not supported). It has to be sr_edit_batch first, and then sr_discard_items. But we can leave with that.

I agree, that it should be one application taking care of one tree, and it is our use case.

Thanks a lot for your guidance, Michal!

**Comment by michalvasko** [comment] 2023-10-12 12:36
> As a side note, calling sr_discard_items before sr_edit_batch does not seem to work (I get this error: There are already some session changes.: Operation not supported). It has to be sr_edit_batch first, and then sr_discard_items. But we can leave with that.

Read the docs for [the function](https://netopeer.liberouter.org/doc/sysrepo/devel/html/group__edit__data__api.html#ga3c93aa25830a13af79add17e3269f9d4), you can technically combine these 2 functions into a single one if you just add some data manually to the edit (support for this was requested by @jktjkt).

**Closed** 2023-10-12 13:37 UTC
Labels: is:enhancement, status:completed
