### ISSUE TITLE
potential race in sr_open

### ISSUE THREAD

**Issue by irfanHaslanded** [sysrepo/sysrepo#2736] opened 2022-02-24 16:51 UTC
There seems to be a potential race in sr_open which results in permissions not being set correctly.

the umask_set, open, umask_restore sequence is not atomic, and in a multi-threaded environment, if umask_restore is called from one thread after one thread calls umask_set, the open call will not do what we intend it to do here.

I think we should switch to a logic of 
open(path.tmp), **fchmod**(perms), rename(path.tmp, path) which will work correctly in all cases.

[gnu man page Setting Permissions](http://www.gnu.org/software/libc/manual/html_node/Setting-Permissions.html)

Can you please check this.

```c
int
sr_open(const char *pathname, int flags, mode_t mode)
{
    mode_t um;
    int fd;

    /* O_NOFOLLOW enforces that files are not symlinks -- all opened
     *   files are created by sysrepo so there cannot be any symlinks.
     * O_CLOEXEC enforces that forking with an open sysrepo connection
     *   is forbidden.
     */
    flags |= O_NOFOLLOW | O_CLOEXEC;

    /* set umask so that the correct permissions are really set */
    um = umask(SR_UMASK);

    /* open the file */
    fd = open(pathname, flags, mode);

    /* restore umask (should not modify errno) */
    umask(um);
```

**Comment by irfanHaslanded** [comment] 2022-02-28 18:11
@michalvasko Do you have any insights?

**Comment by michalvasko** [comment] 2022-03-01 07:18
Not really, I am working on other things because this does not seem like a critical problem and I must do some development as well. The problem is there and what you are suggesting would solve it but make `SR_UMASK` unused. But it probably was not used much anyway, not sure, I will see later.

**Comment by irfanHaslanded** [comment] 2022-03-01 07:45
I would like to add that intermittently, we are observing issues where the permissions are not set to `#define SR_SUB_SHM_PERM 00666`, and lead to processes not being able to read the shared memory, and fail.

**Comment by michalvasko** [comment] 2022-03-01 13:17
Fine, it should be fixed. It should not be needed to create temp files and then rename them, all such creation should be protected by locks.

**Comment by irfanHaslanded** [comment] 2022-03-01 13:33
Thank you very much, I would request it to be also applied to libyang1 branch

**Comment by irfanHaslanded** [comment] 2022-03-03 08:16
This needs to be patched to libyang1 as well.

**Comment by michalvasko** [comment] 2022-03-03 08:19
I was working on it... Should be fine now.

**Closed** 2022-03-15 11:09 UTC
Labels: is:bug, status:completed
