### ISSUE TITLE
implemented modules w/o datastore

### ISSUE THREAD

**Issue by pfeige** [sysrepo/sysrepo#2042] opened 2020-07-01 05:36 UTC
Hi,

there is a problem when an imported module is set to implemented by libyang after sysrepo has already created the startup datastores for the implemented modules. When applying scheduled changes sysrepo tries to load the startup data for all implemented modules for verification reasons. In the described case no such datastore exists and the apply fails. The issue can be reproduced with the test https://github.com/ADTRAN/sysrepo/commit/5d3e1f9dd38bb581b111974db7b4596220d7d8bc.

The proposed solution https://github.com/ADTRAN/sysrepo/commit/bd0d2297dbaf2b4c236d2b5a690fdd8744c507c0 checks whether the module really has data before trying to load them.

BR,
Peter

**Comment by michalvasko** [comment] 2020-07-01 14:13
Hi Peter,
actually, in this case a *libyang* bug has manifested that is causing the problem in *sysrepo*. The problem being that when you parse `impl-wo-ds` with all its dependencies, `impl-wo-ds-idy` is not implemented but when you first parse `impl-wo-ds-cnt` (which makes `impl-wo-ds-idy` implemented) and then `impl-wo-ds`, it will work correctly. The cause of this is resolution hell in the current *libyang* and this being one of the main reasons for us writing *libyang* version 2, so that problems like these do not occur.

Now, without rewriting a lot of *libyang* code and not decreasing the efficiency of schema parsing, I am not able to fix it. Is this a critical issue and the workaround I mentioned cannot be applied in your case? If it could, I would prefer to keep it the way it is and it will get fixed once *sysrepo* uses the new *libyang* (a few months).

Regards,
Michal

**Comment by pfeige** [comment] 2020-07-02 09:11
Hi Michal,

I'm fine with a later solution in the new libyang. For the time being I will apply my workaround as a patch in our software.

Thanks and BR,
Peter

**Comment by michalvasko** [comment] 2020-07-02 09:15
Okay, just note that the test case will not work then because if default identityref values are found in a non-implemented modules, these modules will no longer get implemented automatically but an error will be printed instead. And if you manually install `impl-wo-ds-idy` first and then the rest of the modules, it should actually work both in the current and the new *libyang*.

Regards,
Michal

**Closed** 2022-05-27 13:20 UTC
