### ISSUE TITLE
shm_sub error on callback failure

### ISSUE THREAD

**Issue by sinill57** [sysrepo/sysrepo#1927] opened 2020-04-17 13:40 UTC
Hi,

I get an error in sysrepo after my python callback returns an error code different from `SR_ERR_OK` when validating changes. After this no further edit-config rpc's are processed because of a timeout.
Here are some logs from the sysrepo:

- first rpc:
`change_bad.xml` is meant to fail on validation from my callback

```
user@host:~/netconf/scripts$ netconf-console  --edit-config change_bad.xml
<nc:rpc-error xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <nc:error-type>application</nc:error-type>
  <nc:error-tag>operation-failed</nc:error-tag>
  <nc:error-severity>error</nc:error-severity>
  <nc:error-message xml:lang="en">Internal error (/home/user/netconf/sysrepo/src/shm_sub.c:1108).</nc:error-message>
</nc:rpc-error>
```

```
[INF]: SR: Published event "rpc" with ID 3 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 3 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: SR: Published event "change" with ID 3 priority 1 for 1 subscribers.
[ERR]: SR: Validation failed
[WRN]: SR: Event "change" with ID 3 priority 1 failed (Validation failed).
[INF]: SR: Published event "abort" with ID 3 priority 2 for 1 subscribers.
[ERR]: SR: Internal error (/home/user/netconf/sysrepo/src/shm_sub.c:1108).
[INF]: SR: Finished processing "rpc" event (callback fail) with ID 3 priority 0 (remaining 1 subscribers).
[ERR]: SR: Internal error (/home/user/netconf/sysrepo/src/shm_sub.c:1108).
[WRN]: SR: Event "rpc" with ID 3 priority 0 failed (User callback failed).
[ERR]: NP: Failed to send an RPC (User callback failed).
```

- second rpc:
```
user@host:~/netconf/scripts$ netconf-console --edit-config change.xml
<nc:rpc-error xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <nc:error-type>application</nc:error-type>
  <nc:error-tag>operation-failed</nc:error-tag>
  <nc:error-severity>error</nc:error-severity>
  <nc:error-message xml:lang="en">Callback event "rpc" with ID 4 processing timed out.</nc:error-message>
</nc:rpc-error>
```

```
[ERR]: SR: Callback event "rpc" with ID 4 processing timed out.
[WRN]: SR: Event "rpc" with ID 4 priority 0 failed (Timeout expired).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 6: thread 4 event new RPC.
[INF]: NP: Session 6: thread 4 event reply error.
[INF]: NP: Session 6: thread 4 event new RPC.
[INF]: NP: Session 6: thread 4 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
[ERR]: SR: Locking subscription of "my_module" failed, previous event "abort" with ID 3 was not processed.
[ERR]: SR: Unable to finish processing event "rpc" with ID 4 priority 0 (timeout probably).
```

However if I apply only  `change.xml` is is accepted and ok status returned.

**Comment by michalvasko** [comment] 2020-04-17 13:47
Hi,
what *sysrepo* version are you using? If it is the latest release (`master`) then please switch to `devel` and try again. The next release should happen next week, I hope.

Regards,
Michal

**Comment by IvanAguiar95** [comment] 2020-04-17 20:41
I'm having the same error.

**Comment by michalvasko** [comment] 2020-04-20 07:46
And you are using sysrepo `devel`? Because the lines in the first post do not match lines in the current code in `devel`.

Regards,
Michal

**Comment by IvanAguiar95** [comment] 2020-04-20 17:20
Hi Michal, to use the sysrepo in devel, could you send the compatible versions for the dependencies?

**Comment by sinill57** [comment] 2020-04-20 18:14
Hi Michal,

This occurred in the master branch.  So it happens the error is here:
```
/* unreachable unless the failed subscription was not found */
SR_ERRINFO_INT(&err_info);
```

**Comment by michalvasko** [comment] 2020-04-21 09:59
Okay, please someone try it again having the latest `devel` branches installed. You need these branches of *libyang*, *sysrepo*, *libnetconf2*, and *netopeer2* (actually it is `devel-server` here).

Regards,
Michal

**Comment by maksimvuleta** [comment] 2020-04-27 11:52
I got the same errors with devel branches.
I installed fresh libyang, sysrepo, libnetconf2, and netopeer2 from devel branches few days ago (on Friday morning).

**Comment by michalvasko** [comment] 2020-04-27 13:28
Hi,
can you please provide the steps/data for me to be able to reproduce it, please? As simple as possible.

Regards,
Michal

**Comment by maksimvuleta** [comment] 2020-04-28 07:15
1. Connect with netopeer2-cli
2. Do edit-config 
3. my callback is triggered and SR_ERR_OPERATION_FAILED should be returned from callback with proper message to the client.
4. On the netopeer2-cli client-side message:
_Callback for '/ieee802-dot1q-bridge:bridges/bridge/component' failed._
5. sysrepo-plugind side message:
_[INF]: Processing "ieee802-dot1q-bridge" "change" event with ID 1 priority 7 (remaining 3 subscribers).
[INF]: Processing "ieee802-dot1q-bridge" "change" event with ID 1 priority 7 (remaining 3 subscribers).
[ERR]: Internal error (/path/to/sysrepo/src/shm_sub.c:1990).
[INF]: Finished processing "change" event (callback fail) with ID 1 priority 7 (remaining 3 subscribers).
[ERR]: Unable to finish processing event "change" with ID 1 priority 7 (timeout probably)._

6. netopeer2-server side:
_[INF]: SR: Published event "change" "ieee802-dot1q-bridge" with ID 1 priority 7 for 3 subscribers.
[ERR]: SR: Callback for '/ieee802-dot1q-bridge:bridges/bridge/component' failed.
[WRN]: SR: Event "change" with ID 1 priority 7 failed (Operation failed).
[INF]: SR: Finished processing "rpc" event (callback fail) with ID 1 priority 0 (remaining 1 subscribers).
[ERR]: SR: Callback for '/ieee802-dot1q-bridge:bridges/bridge/component' failed.
[WRN]: SR: Event "rpc" with ID 1 priority 0 failed (User callback failed).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 1: thread 3 event new RPC.
[INF]: NP: Session 1: thread 3 event reply error._

NOTE:
It looks like this internal error is there only for leaf which is defined inside the list.
For the leaf defined in the container, I got the proper message without any errors if callback is failed. Maybe I just have luck but it looks like that for now.

**Comment by michalvasko** [comment] 2020-04-28 07:32
Hi,
this seems like a candidate for a new test but I will really need more details to create it. Most importantly, what exact subscriptions (with their XPath, if any) for `ieee802-dot1q-bridge` module do you have (there should be 3)? What `edit-config` are you sending to the server? What data are there in the server prior to the edit-config? Which callback (on what subscription) should fail? Please also attach your `repository/yang` directory so that I do not have to download all the modules manually.

Regards,
Michal

**Comment by maksimvuleta** [comment] 2020-04-28 07:58
Please look at https://github.com/sysrepo/sysrepo/issues/1949#issuecomment-620443618 
There are steps to reporoduce it. 

Regards,
Maksim.

**Comment by michalvasko** [comment] 2020-04-28 09:12
Marking this as a duplicate of #1949

**Closed by michalvasko** 2020-04-28 09:12 UTC
