### ISSUE TITLE
if we do not config data ,we can not get any data by get-config  with "report-all" operation?

### ISSUE THREAD

**Issue by ostack** [sysrepo/sysrepo#626] opened 2016-12-13 06:13 UTC
if we do not config data ,we can not get any data by get-config with "report-all" operation?

**Comment by lukasmacko** [comment] 2016-12-13 07:12
I am not sure what you meant exactely but it seems to me like https://github.com/sysrepo/sysrepo/issues/335

**Comment by ostack** [comment] 2016-12-13 08:04
yes, my concern is same with the issue #335, if the model  has the mandatory leaf and the node data not config, and the query will return nothing

**Comment by rastislavszabo** [comment] 2016-12-13 13:09
duplicate of #335

**Closed by rastislavszabo** 2016-12-13 13:09 UTC
Labels: duplicate
