### ISSUE TITLE
Sysrepo in-memory storage

### ISSUE THREAD

**Issue by fxie00** [sysrepo/sysrepo#2024] opened 2020-06-15 16:36 UTC
Hi,

I have some questions with respect to Sysrepo in-memory storage. Any feedback would be appreciated.

1. Is configuration information shared by operational data store and running data store? Or each data store has a separate copy?

2.  Is it true that a pending configuration will be removed from candidate data store to operational/running data store at the end of the commit? Will it also be written to the startup data store? Is it possible to skip writing to the startup data store by using the cache only mode?

3.  I noticed that there are some API changes from pre-release to formal releases, e.g., sr_dp_get_items_subscribe . Is there an one-to-one replacement for these deprecated ones? If so, are these changes backward compatible? 

4. I noticed that libyang structures, such as lyd_set/node/attr, are used in sysrepo storage. Is it true that every leaf entity in a data tree is represented by lyd_attr in the Sysrepo internal storage? If so, are there any concerns about the storage overhead in lyd_attr? For example, an uint32_t leaf entity may require ~50 bytes or more if it is stored in lyd_attr?

Thanks.

Feng

**Comment by michalvasko** [comment] 2020-06-16 06:19
Hi,
1. I suppose the answer is they share it but `operational` datastore does not have any configuration data, generally speaking. It is always constructed ad-hoc and for that `running` configuration data are also used.
2. I think the answer is yes. In other words, `candidate` is reset back to `running` after its contents were successfully committed. Commit is defined as `copy-config` from `candidate` to `running`, has nothing to do with `startup` so it is not modified.
3. Any changes should be mentioned in [CHANGES](https://github.com/sysrepo/sysrepo/blob/master/CHANGES). We tried to keep the API as similar as possible but it was not always possible. Still, the principle of how the API works is the same. Also, as the 1.x version is a complete rewrite compared to the 0.7.x versions, it is best to read the whole documentation and try to focus on the new version only, internally it works differently.
4. No, `struct lyd_attr` is used only for `edit` operations, the values and nodes are represented normally as `struct lyd_node`.

Regards,
Michal

**Comment by fxie00** [comment] 2020-06-16 14:37
Hi Michal,

Thanks a lot for the quick and detailed response. I still have some further questions for question 4 with respect to how sysrepo stores data information internally. Assume that I have a C structure called interface with many attributes such as name, link metric, admin status, etc.. The structure should be represented by a lyd_node in sysrepo running data store, right? If so, each attribute will be represented by a lyd_attr in sysrepo running store. My understanding results from the fact that lyd_node contains a list of lyd_attr. Only lyd_attr contains the actual value (in both binary and string format).

If the above understanding is correct, is it true that lyd_node and lyd_attr are used to build up a tree for running data store inside Sysrepo? The concern for this is the overhead in lyd_attr and ldy_node. On the other hand, it may be possible that sysrepo converts lyd_attr /lyd_node to some more efficient binary such as LYB for internal storage purposes. Unfortunately, I could not find any definition/implementation for internal data stores. Can you please provide some hints?

Best regards,
Feng

**Comment by michalvasko** [comment] 2020-06-17 06:30
Hi Feng,
all that we are now talking about is implemented in *libyang*, so that is where you will find any details. What I said before is true, `lyd_attr` is not used much, not at all in data. Values are stored in `lyd_node_leaf_list` and `lyd_node_any`. To learn what structure it actually is you look at `node->schema->nodetype`. LYB is also implemented in *libyang*.

Regards,
Michal

**Comment by fxie00** [comment] 2020-06-28 21:58
Hi Michael,

Thanks a lot for the help. You mentioned that a commit does not update startup datastore. If so, will a configuration change be lost if the system reboot after the commit? Further, you mentioned that "operational datastore is always constructed ad-hoc and for that running configuration data are also used”. When is the operational datastore constructed? I used to think that both running and operational datastores exist simultaneously.

Best regards,
Feng

**Comment by michalvasko** [comment] 2020-06-30 12:09
Hi,
yes, unless you perform `copy-config` from `running` to `startup`, any `<commit>` will be lost (as was intended). Operational datastore is constructed whenever it is needed because it may change quite rapidly. They do exist simultaneously but it would not really be efficient to keep the whole `operational` datastore in memory and keep updating it. Moreover, it can be changed by operational subscriptions meaning it cannot be cached at all. You can read about all that in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/).

Regards,
Michal

**Closed** 2020-09-13 21:59 UTC
