### ISSUE TITLE
 rp_dt_send_request_to_dp_subscription issue

### ISSUE THREAD

**Issue by morganzhh** [sysrepo/sysrepo#654] opened 2016-12-22 09:34 UTC
Hi,
I got an error when get operational data from sysrepo on ``devel`` branch

My operational path is

```
/a:cards/card/state
```

In rp_dt_send_request_to_dp_subscription, after getting instance from libyang, the code change the xpath to

```
/a:cards/card[1]/card/state
```

The ``card`` shouldn't be there, it should be

```
/a:cards/card[1]/state
```

I did a temp fix to move on, it works, could you fix this issue, thanks a lot.

```diff
--- a/src/rp_dt_get.c
+++ b/src/rp_dt_get.c
@@ -967,6 +967,24 @@ rp_dt_send_request_to_dp_subscription(rp_ctx_t *rp_ctx, rp_session_t *rp_session
             ptr--;
         }

+        /* remove list node */
+        int rest = strlen(ptr);
+        char* tmp = ptr;
+        while ( rest > 0)
+        {
+            if ('/' == *tmp) {
+                tmp++;
+                break;
+            }
+            tmp++;
+            rest--;
+        }
+
+        if (0 != rest)
+        {
+            ptr = tmp;
+        }
+
```

**Comment by rastislavszabo** [comment] 2016-12-22 11:28
Please provide the YANG model related to the issue.

**Comment by morganzhh** [comment] 2016-12-23 02:00
```yang
module a {
    namespace "http://www.test.com/a";
    prefix "ma";

    container cards {

      list card {
        key "dn";
  
        leaf dn {
            type string;
        }

        container config {
            leaf c_name {
                type string;
            }
        }

        container state {
            config false;
            leaf c_state {
                type string;
            }
        }
        
      } // card
      
    } // cards
}
```

**Comment by lukasmacko** [comment] 2016-12-23 15:34
I tried to reproduce the issue with the modified [oper_data_example.c](https://github.com/sysrepo/sysrepo/blob/devel/examples/oper_data_example.c) using your model and I received requests for correct xpath
```
 ========== SUBSCRIBED FOR PROVIDING OPER DATA ==========

Data for '/a:cards/card[dn='a']/state' requested.
Data for '/a:cards/card[dn='b']/state' requested.
```

I am not sure if I understand correctly. Does your data provider receive invalid xpath?
The xpath looks weird since it uses position index instead of key predicates.

**Comment by morganzhh** [comment] 2016-12-24 05:34
Hi, 
Data  provider get called and set the right value, then sysrepo call libyang for data validation, that where error happens

**Comment by morganzhh** [comment] 2017-01-03 07:57
We use C++, the setting code list below

```c

    S_Session sess = getSession();
    auto values = sess->get_items("/a:cards/card");
    auto out_vals = holder->allocate(CARD_NUMBER_OF_LEAFS * values->val_cnt());
    EM_LOG_ERROR("Card States Data Get there are: " << values->val_cnt() << "elements");

    for (unsigned int i = 0; i < values->val_cnt(); i++) {
        unsigned int pos = CARD_NUMBER_OF_LEAFS * i;
        unsigned int cnt = 0;
        string posPath = string(values->val(i)->xpath());
        string path = posPath + "/state/c-state";
        EM_LOG_DEBUG("Setting path: " << path);
        out_vals->val(pos + cnt++)->set(path.c_str(), "OK", SR_STRING_T);
    }

```

Those are logs, as you can see, application set the right xpath, when ``Sysrepo`` call ``Libyang'' for validation, it was wrong xpath.

```log
server[1]: [0.E]: [EM]================ Data Getting==================START
server[1]: [0.E]: [EM]Xpath: /a:cards/card[dn='ne=1,chassis=1,card=2']/card/state
server[1]: [0.D]: [SR]get-items response received, processing.
server[1]: [0.E]: [EM]Card States Data Get there are: 1elements
server[1]: [0.D]: [EM]Setting path: /a:cards/card[dn='ne=1,chassis=1,card=2']/state/c-state
server[1]: [0.E]: [EM]============ Data Getting========rc[0]====END
server[1]: [0.D]: [SR]Circular buffer dequeue, new buffer head=3, count=0.
server[1]: [0.D]: [SR]Data provide response received, waiting for 0 more data providers.
server[1]: [0.D]: [LY]XPATH: expression "/a:cards/card[dn='ne=1,chassis=1,card=2']/card/state":
server[1]: [0.D]: [LY]XPATH:	Token Operator(Path), in expression "/"
server[1]: [0.D]: [LY]XPATH:	Token NameTest, in expression "a:cards"
server[1]: [0.D]: [LY]XPATH:	Token Operator(Path), in expression "/"
server[1]: [0.D]: [LY]XPATH:	Token NameTest, in expression "card"
server[1]: [0.D]: [LY]XPATH:	Token [, in expression "["
server[1]: [0.D]: [LY]XPATH:	Token NameTest, in expression "dn" (repeat 6)
server[1]: [0.D]: [LY]XPATH:	Token Operator(Comparison), in expression "="
server[1]: [0.D]: [LY]XPATH:	Token Literal, in expression "'ne=1,chassis=1,card=2'"
server[1]: [0.D]: [LY]XPATH:	Token ], in expression "]"
server[1]: [0.D]: [LY]XPATH:	Token Operator(Path), in expression "/"
server[1]: [0.D]: [LY]XPATH:	Token NameTest, in expression "card"
server[1]: [0.D]: [LY]XPATH:	Token Operator(Path), in expression "/"
server[1]: [0.D]: [LY]XPATH:	Token NameTest, in expression "state"
server[1]: [0.D]: [LY]XPATH: eval_absolute_location_path parsed Operator(Path)[0]
server[1]: [0.D]: [LY]DICT: inserting (refcount) "cards"
server[1]: [0.D]: [LY]XPATH: eval_node_test              parsed NameTest[1]
server[1]: [0.D]: [LY]XPATH: eval_relative_location_path parsed Operator(Path)[29]
server[1]: [0.D]: [LY]DICT: inserting (refcount) "card"
server[1]: [0.D]: [LY]XPATH: eval_node_test              parsed NameTest[30]
server[1]: [0.D]: [LY]XPATH: eval_predicate              parsed [[34]
server[1]: [0.D]: [LY]DICT: inserting (refcount) "dn"
server[1]: [0.D]: [LY]XPATH: eval_node_test              parsed NameTest[35]
server[1]: [0.D]: [LY]XPATH: eval_equality_expr          parsed Operator(Comparison)[37]
server[1]: [0.D]: [LY]XPATH: eval_literal                skipped Literal[38]
server[1]: [0.D]: [LY]XPATH: eval_predicate              parsed ][61]
server[1]: [0.D]: [LY]XPATH: eval_relative_location_path parsed Operator(Path)[62]
server[1]: [0.D]: [LY]DICT: inserting (refcount) "card"
server[1]: [0.E]: [LY]Schema node "card" not found (/a:cards/card[dn='ne=1,chassis=1,card=2']/card).
server[1]: [0.E]: [LY]Resolving XPath expression "/a:cards/card[dn='ne=1,chassis=1,card=2']/card/state" failed.
server[1]: [0.E]: [SR]Schema node not found for /a:cards/card[dn='ne=1,chassis=1,card=2']/card/state
server[1]: [0.E]: [SR]Data validation failed.
server[1]: [0.D]: [SR]All data from data providers has been received session id = 1965099991, reenque the request
```

**Comment by rastislavszabo** [comment] 2017-01-03 08:18
What prints this line? (2nd one)
```
server[1]: [0.E]: [EM]Xpath: /a:cards/card[dn='ne=1,chassis=1,card=2']/card/state
```

I don't see it in the code excerpt you provided. It seems that this is actually the xpath that Sysrepo is handling. Anyway, this is the first time where invalid xpath appears in the log, so let's start debugging from there.

**Comment by rastislavszabo** [comment] 2017-01-03 08:19
Also it would be helpful if you provided the code of whole callback function, not just an excerpt.

**Comment by morganzhh** [comment] 2017-01-03 08:43
I would love to put all the code, however we have a c++ wrapper upon ``Sysrepo`` c++ interface, I am trying to, :)

So the log you mentioned was printer here:
```
int ServerCallback::dp_get_items(const char *xpath, S_Vals_Holder vals, void *ctx) {
    DataGetCallback *callback = static_cast<DataGetCallback *>(ctx);
    EM_LOG_ERROR("================ Data Getting==================START");
    EM_LOG_ERROR(" Xpath: " << std::string(xpath));
    callback->getSession()->refresh();
    int rc = callback->onGet(std::string(xpath), vals);
    EM_LOG_ERROR_FMT("============ Data Getting========rc[%d]====END", rc);
    return rc;
}
```

``callback->onGet(std::string(xpath), vals);``  has the code we put ``state`` data in

**Comment by morganzhh** [comment] 2017-01-03 08:47
Sorry to mention ServerCallback is the real callback we subscribe from sysrepo

```
void DataGetSubscriber::do_subscribe() {
    return getSysrepoSubs()->dp_get_items_subscribe(
        g_xpath.c_str(), S_Callback(new ServerCallback(g_xpath)), g_callback.get());
}
```

**Comment by rastislavszabo** [comment] 2017-01-04 12:47
You are right, the amount of abstractions above Sysrepo API that you have in your implementation is too much for me to identify the root-cause. Could you possibly try to isolate the issue into a small fragment of C code (e.g. by modifying [oper_data_example.c](https://github.com/sysrepo/sysrepo/blob/devel/examples/oper_data_example.c))?

**Comment by morganzhh** [comment] 2017-01-05 03:34
Hi, 
I was able to reproduce this issue with modified oper_data_example.c. 
Turns out it relates the 'grouping' in the yang file, I removed the 'grouping' from the yang because I was trying to provide a minimum yang file, sorry about this.

```yang
module a {
    namespace "http://www.test.com/a";
    prefix "ma";

    grouping card-c {
        leaf c_name {
            type string;
        }
    }

    grouping card-s {
        leaf c_state {
            type string;
        }
    }

    grouping  card-g {
        container config {
            uses card-c;
        }
        container state {
            config false;
            uses card-s;
        }
    }
    grouping cards-g {
        container cards {
            list card {
                key "dn";
  
                leaf dn {
                    type string;
                }
                uses card-g;
            }
        }
    }   
    uses cards-g;
}
```

Data provider

```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <string.h>
#include <inttypes.h>

#include "sysrepo.h"
#include "sysrepo/values.h"
#include "sysrepo/xpath.h"

volatile int exit_application = 0;

static int
data_provider_cb(const char *xpath, sr_val_t **values, size_t *values_cnt, void *ctx)
{
    sr_val_t *v = NULL;
    int rc = SR_ERR_OK;

    (void)ctx;
    printf("Data for '%s' requested.\n", xpath);

    /* allocate space for data to return */
    rc = sr_new_values(1, &v);
    if (SR_ERR_OK != rc) {
        return rc;
    }

    sr_val_build_xpath(&v[0], "%s/%s", xpath, "c_state");
    sr_val_set_str_data(&v[0], SR_STRING_T, "OK");

    *values = v;
    *values_cnt = 1;

    return SR_ERR_OK;
}

static void
sigint_handler(int sig)
{
    (void)sig;
    exit_application = 1;
}

static int
data_provider(sr_session_ctx_t *session)
{
    sr_subscription_ctx_t *subscription = NULL;
    int rc = SR_ERR_OK;

    /* subscribe for providing operational data */
    rc = sr_dp_get_items_subscribe(session, "/a:cards/card/state", data_provider_cb, NULL,
            SR_SUBSCR_DEFAULT, &subscription);
    if (SR_ERR_OK != rc) {
        fprintf(stderr, "Error by sr_dp_get_items_subscribe: %s\n", sr_strerror(rc));
        goto cleanup;
    }

    printf("\n\n ========== SUBSCRIBED FOR PROVIDING OPER DATA ==========\n\n");

    /* loop until ctrl-c is pressed / SIGINT is received */
    signal(SIGINT, sigint_handler);
    signal(SIGPIPE, SIG_IGN);
    while (!exit_application) {
        sleep(1000);  /* or do some more useful work... */
    }

    printf("Application exit requested, exiting.\n");

cleanup:
    if (NULL != subscription) {
        sr_unsubscribe(session, subscription);
    }
    return rc;
}

int
main(int argc, char **argv)
{
    sr_conn_ctx_t *connection = NULL;
    sr_session_ctx_t *session = NULL;
    int rc = SR_ERR_OK;

    (void)argc;(void)argv;
    /* connect to sysrepo */
    rc = sr_connect("example_application", SR_CONN_DEFAULT, &connection);
    if (SR_ERR_OK != rc) {
        fprintf(stderr, "Error by sr_connect: %s\n", sr_strerror(rc));
        goto cleanup;
    }

    /* start session */
    rc = sr_session_start(connection, SR_DS_RUNNING, SR_SESS_DEFAULT, &session);
    if (SR_ERR_OK != rc) {
        fprintf(stderr, "Error by sr_session_start: %s\n", sr_strerror(rc));
        goto cleanup;
    }

    /* run as a data provider */
    printf("This application will be a data provider for state data of ietf-interfaces.\n");
    printf("Run the same executable with one (any) argument to request some data.\n");
    rc = data_provider(session);

cleanup:
    if (NULL != session) {
        sr_session_stop(session);
    }
    if (NULL != connection) {
        sr_disconnect(connection);
    }
    return rc;
}
```

Server Log

```
01-05T03:28:39.540:[0.E.emulator]:Logging.cc:92: [LY]Schema node "card" not found (/a:cards/card[dn='1']/card).
01-05T03:28:39.540:[0.E.emulator]:Logging.cc:92: [LY]Resolving XPath expression "/a:cards/card[dn='1']/card/state" failed.
01-05T03:28:39.540:[0.E.emulator]:Logging.cc:116: [SR]Schema node not found for /a:cards/card[dn='1']/card/state
01-05T03:28:39.540:[0.E.emulator]:Logging.cc:116: [SR]Data validation failed.
01-05T03:28:39.540:[0.W.emulator]:Logging.cc:119: [SR]Error by processing of the message: Invalid argument.
```

Application Log

```

This application will be a data provider for state data of ietf-interfaces.
Run the same executable with one (any) argument to request some data.


 ========== SUBSCRIBED FOR PROVIDING OPER DATA ==========

Data for '/a:cards/card[dn='1']/card/state' requested.
```

**Comment by rastislavszabo** [comment] 2017-01-05 13:17
Thanks, this helped a lot. We will address this bug.

**Comment by rastislavszabo** [comment] 2017-01-09 15:41
fixed in the devel branch

**Closed by rastislavszabo** 2017-01-09 15:41 UTC
Labels: bug
