### ISSUE TITLE
Error in modifying operational data store for a module for which another application has subscribed to its running data tree

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#2426] opened 2021-05-21 07:29 UTC
Hi,

We have an application (say application_1) that has subscribed for changes in a module on running data store at a specific xpath (say X). Also ,we have another application (say application_2, creating separate connection and session object) that is modifying operational data store for the same module but different xpath (say Y). The issue we are observing is, if application_1 is running in background and if application_2 is try to modify the operational data store (using sr_set_item()) at xpath Y we are getting below error while sr_apply_change() :-

[ERR]: Internal error (/root/netopeer-install-latest/sysrepo-1.4.122/src/edit_diff.c:2107).
[ERR]: Applying operation "create" failed.

What could be the reason for this issue?

**Comment by michalvasko** [comment] 2021-05-21 08:24
This could be a duplicate of #2419. And my advice would probably be similar (except synchronizing 2 processes is more difficult). But if you are able to reliably reproduce the problem and will provide all the data and steps, I may try to fix it.

**Comment by ChinmayaAgarwal** [comment] 2021-05-21 10:12
Do you suggest picking libyang2 from this path and try it : -

https://github.com/CESNET/libyang/tree/devel

Will be sharing data and steps in a while.

**Comment by ChinmayaAgarwal** [comment] 2021-05-21 11:21
We have two applications, application_1 is using ietf-sr-policy yang model and application_2 uses ietf-sr-service-programming yang model. Both these yang model augments ietf-routing at the top level. In application_1 we are subscribing on running data tree change for ietf-routing. In application_2, we are setting the value of oper-status (state data) leaf and service-program (or name, which is the key) in operational data store. We then generate the notification for the modification in operational data store. Below is the snippet of the data tree that we are modifying in operational data store and corresponding notification structure we are using to send the notification.
 
State data tree we are modifying in operational data store

   module: ietf-sr-service-programming
     augment /rt:routing/sr:segment-routing:
       +--rw service-programming
          +--rw service-program* [name]
             +--ro oper-status?        identityref
             
				
		
Corresponding notification structure that refers to the state data
		
	module: ietf-sr-service-programming
     notifications:
       +---n service-program-oper-status
          +--ro name           -> /rt:routing/sr:segment-routing/
                                  sr-svc-pgm:service-programming/
                                  service-program/name
          +--ro oper-status    -> /rt:routing/sr:segment-routing/
                                  sr-svc-pgm:service-programming/
                                  service-program/oper-status	


Below are the details of the sequence of sysrepo calls used in application_1 and application_2 : -

1. Application_1

    sr_conn_ctx_t *p_connection = NULL;
    sr_session_ctx_t *p_session = NULL;
    sr_subscription_ctx_t *p_subscription = NULL;
    

    sr_connect( SR_CONN_DEFAULT, &p_connection);
    
    sr_session_start(p_connection,SR_DS_RUNNING , &p_session);
        
    sr_module_change_subscribe(p_session, "ietf-routing", NULL, srv6_agent_routing_conf_change_cb, NULL,
            0, 0, &p_subscription);	
			
				
    XPaths we are listening to : -

    a) /ietf-routing:routing/ietf-sr-policy:segment-routing/ietf-sr-policy:traffic-engineering/ietf-sr-policy:attributes/ietf-sr-policy:segment-lists
    b) /ietf-routing:routing/ietf-sr-policy:segment-routing/ietf-sr-policy:traffic-engineering/ietf-sr-policy:policies
			
			
2. Application_2 			

    sr_conn_ctx_t *p_connection = NULL;
    sr_session_ctx_t *p_session = NULL;
	
    sr_connect(SR_CONN_DEFAULT, &p_connection);
	
    sr_session_start(p_connection, SR_DS_OPERATIONAL, &p_session);
	
    sr_set_item(p_session, p_xpath, p_value, SR_EDIT_DEFAULT);
	
    sr_apply_changes(p_session, 10000, 1);

    XPath we are writing to : -
    
    /ietf-routing:routing/ietf-segment-routing:segment-routing/ietf-sr-service-programming:service-programming/service-program[name='<service-program-name>']/oper-status
	
    We are getting error in sr_apply_changes() function : -
	
	[ERR]: Internal error (/root/netopeer-install-latest/sysrepo-1.4.122/src/edit_diff.c:2107).
	[ERR]: Applying operation "create" failed.

**Comment by michalvasko** [comment] 2021-05-24 10:29
Could you please provide all the YANG modules? I see that they are only in drafts so it will save me some work and make sure we are using the same revisions.

**Comment by ashishsaxenahsc** [comment] 2021-05-24 13:39
Hi Michal,

I am sharing the yang model files along with this mail.
[yang models.zip](https://github.com/sysrepo/sysrepo/files/6532723/yang.models.zip)

As per the link referred by you , we have tried compiling libyang2 branch for all the packages. After migrating to libyang2 branch, We are no longer getting the earlier error , but now , I am getting the following error logs at netopeer2-cli while connecting  :
# netopeer2-cli
> connect netconf --port 830
Interactive SSH Authentication
Type your password:
Password:
ly WARNING: Missing explicit "obsolete" status that was already specified in parent, inheriting.

And following error is observed while subscribing for changes : 

> subscribe
ly ERROR: Inner node (not a list) "subscribe" not found.
cli_send_recv: Failed to receive a reply.

**Closed** 2022-05-30 10:08 UTC
Labels: is:bug
