### ISSUE TITLE
Notification failed([ERR]: Invalid leafref value "true" - XPath evaluation error) when node is leaf-ref to operational data

### ISSUE THREAD

**Issue by biranchi1186** [sysrepo/sysrepo#2528] opened 2021-08-04 08:44 UTC
HI Michal,
We are facing an issue while sending notification where notification has a leafref to a leaf which is operational data.
Please find the below error which we are facing.

Steps to reproduce : 
1. We used  "oper_data_push_example" to write the operational data  in DB.
    _./oper_data_push_example /o-ran-ald-port:ald-ports-io/ald-port[name=\'ALD_PORT\']/dc-enabled-status true
    Application will set "/o-ran-ald-port:ald-ports-io/ald-port[name='ALD_PORT']/dc-enabled-status" to value "true"._
    
2. using "notif_send_example" we send notification.
  _./notif_send_example /o-ran-ald-port:dc-enabled-status-change ald-port[name=\'ALD_PORT\']/dc-enabled-status true
  Application will send notification "/o-ran-ald-port:dc-enabled-status-change"
  **[ERR]: Invalid leafref value "true

   " - XPath evaluation error.
  [ERR]: Notification validation failed._**
3. We got the below errors, while operational data is present in Operational DB already and same has been verified using the netopeer2-cli 

Attaching the used yang modules. 

[YANG_MODULE.zip](https://github.com/sysrepo/sysrepo/files/6929866/YANG_MODULE.zip)
common_models/interfaces/o-ran-ald-port.yang

Thanks!

Regards,
Biranchi

**Comment by michalvasko** [comment] 2021-08-05 08:46
The attachment is empty, please include the modules again.

**Comment by biranchi1186** [comment] 2021-08-05 09:40
Hi Michal,
Please find the attached modules

[YANG_MODULE.tar.gz](https://github.com/sysrepo/sysrepo/files/6937567/YANG_MODULE.tar.gz)

Thanks!

Regards,
Biranchi

**Comment by michalvasko** [comment] 2021-08-05 09:48
Just looking at the modules it seems you will need another instance of `oper_data_push_example` running because you can set the `dc-enabled-status` leaf only if another leaf `dc-control-support` is set to `true`.

**Comment by biranchi1186** [comment] 2021-08-05 10:36
Hi Michal,
Our application does set all dependency parameter in sysrepo.

Here is the data available already in sysrepo .
===============================
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ald-ports-io xmlns="urn:o-ran:ald-port:1.0">
    <over-current-supported>true</over-current-supported>
    <ald-port>
      <name>ALD_PORT</name>
      <port-id>1</port-id>
      <dc-control-support>true</dc-control-support>
      <dc-enabled-status>true</dc-enabled-status>
      <supported-connector>ANTENNA_CONNECTOR</supported-connector>
    </ald-port>
  </ald-ports-io>
</data>
==============================

Now application tried to write notification which is throwing the error which I have already mentioned.
==============================
path : /o-ran-ald-port:dc-enabled-status-change/ald-port[name='ALD_PORT']/dc-enabled-status,  value :  true 
path : /o-ran-ald-port:dc-enabled-status-change/ald-port[name='ALD_PORT']/name , value : ALD_PORT

[ERR]: Invalid leafref value "false" - XPath evaluation error.
[ERR]: Notification validation failed.
==============================

**Comment by biranchi1186** [comment] 2021-08-05 10:41
Hi Michal,
Our application does set all dependency parameter in sysrepo.

Here is the data available already in sysrepo .

===============================

<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ald-ports-io xmlns="urn:o-ran:ald-port:1.0">
    <over-current-supported>true</over-current-supported>
    <ald-port>
      <name>ALD_PORT</name>
      <port-id>1</port-id>
      <dc-control-support>true</dc-control-support>
      <dc-enabled-status>true</dc-enabled-status>
      <supported-connector>ANTENNA_CONNECTOR</supported-connector>
    </ald-port>
  </ald-ports-io>
</data>

==============================

Now application tried to write notification which is throwing the error which I have already mentioned.

==============================

path : /o-ran-ald-port:dc-enabled-status-change/ald-port[name='ALD_PORT']/dc-enabled-status,  value :  true 
path : /o-ran-ald-port:dc-enabled-status-change/ald-port[name='ALD_PORT']/name , value : ALD_PORT

[ERR]: Invalid leafref value "false" - XPath evaluation error.
[ERR]: Notification validation failed.

==============================

Thanks!

Regards,
Biranchi

**Comment by michalvasko** [comment] 2021-08-05 11:51
Could you paste the output of `sysrepocfg -X -d operational` before sending the notification?

**Comment by biranchi1186** [comment] 2021-08-05 12:33
HI Michal,
I am getting bellow error while running the mentioned command
==========================================
- sysrepocfg -X -d operational -v3
<img width="488" alt="sysrepocfg_ald_port_err" src="https://user-images.githubusercontent.com/75461703/128350291-1de6d3cf-69eb-4b6d-a86b-96e27d4a372e.PNG">

But If I give xpath then below output I am getting
===============================
- sysrepocfg -X -d operational -x /o-ran-ald-port:*
<img width="307" alt="sysrepocfg_ald_port" src="https://user-images.githubusercontent.com/75461703/128350338-3402de53-146b-453b-9dad-afb93451b273.PNG">

**Comment by michalvasko** [comment] 2021-08-06 06:02
Okay, except for the error the data look fine. I have not asked yet, what *sysrepo* version are you using?

**Comment by biranchi1186** [comment] 2021-08-06 06:16
Hi Michal,
We have used the latest pull from devel branch

Thanks!

Regards,
Biranchi

**Comment by michalvasko** [comment] 2021-08-06 06:24
I see, what version exactly (output of `sysrepoctl -V`, for example)? Because it is not the current `devel`.

**Comment by biranchi1186** [comment] 2021-08-06 06:52
sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.0.32 (SO v6.3.2)

**Comment by michalvasko** [comment] 2021-08-06 06:57
Then you have several *sysrepo* installations or some incompatibility like that. Based on the internal error in a few posts back, there should be an error on [this line](https://github.com/sysrepo/sysrepo/blob/f6f25ae284a1bd20f2627ff5cca7473f3812d382/src/common.c#L4169) but is not.

**Comment by biranchi1186** [comment] 2021-08-09 03:40
Hi Michal,
We have only latest devel version of sysrepo installed where we tried these notification.
We also tried to install sysrepo on a new machine and tested these notification.

We are getting same error 

===========================

path :  /o-ran-ald-port:dc-enabled-status-change/ald-port[name='ALD_PORT']/dc-enabled-status
value : true
path : /o-ran-ald-port:dc-enabled-status-change/ald-port[name='ALD_PORT']/name
value : ALD_PORT

[ERR]: Invalid leafref value "false" - XPath evaluation error.
[ERR]: Notification validation failed.

Thanks!

Regards,
Biranchi

**Comment by biranchi1186** [comment] 2021-08-10 22:03
Hi Michal,
Kindly update any resolution procedure for this notification issue.

Thanks!

Regard,
Biranchi

**Comment by biranchi1186** [comment] 2021-08-23 09:59
Hi Michal,
Kindly update any resolution procedure for this notification issue.

Thanks!

Regard,
Biranchi

**Comment by michalvasko** [comment] 2021-08-24 09:09
Try the latest *libyang*, should now be fixed.

**Comment by biranchi1186** [comment] 2021-09-01 12:36
Hi Michal,
We have tested with latest libyang  , still we are getting same notification error.

Name: libyang
Description: libyang is YANG data modelling language parser and toolkit written (and providing API) in C.
Version: 2.0.81

Error : 
path : /o-ran-ald-port:dc-enabled-status-change/ald-port[name='ALD_PORT']/dc-enabled-status
value : true
path : /o-ran-ald-port:dc-enabled-status-change/ald-port[name='ALD_PORT']/name
value : ALD_PORT

[ERR]: Invalid leafref value "false" - XPath evaluation error.
[ERR]: Notification validation failed.

Please let us know your feedback.

Thanks!

Regards,
Biranchi

**Comment by michalvasko** [comment] 2021-09-01 12:59
Are you sure you are really using the latest version, it is best to remove any older ones. The steps I did:
```
# sysrepoctl -a -s YANG_MODULE/ -i YANG_MODULE/common_models/interfaces/o-ran-ald-port.yang
# oper_data_push_example "/o-ran-ald-port:ald-ports-io/ald-port[name='ALD_PORT']/dc-enabled-status" true
Application will set "/o-ran-ald-port:ald-ports-io/ald-port[name='ALD_PORT']/dc-enabled-status" to value "true".



 ========== WAITING AS OWNER OF SET DATA ==========
```
and in another terminal
```
notif_send_example /o-ran-ald-port:dc-enabled-status-change "ald-port[name='ALD_PORT']/dc-enabled-status" true
Application will send notification "/o-ran-ald-port:dc-enabled-status-change".

```
The notification was sent successfully. I reproduced the problem before and can no longer so it really should be fixed.

**Comment by ankit7gup** [comment] 2021-09-16 10:59
Hi Michal, Taking the latest code base, tried my own application with following steps:

Some analysis:

1. Using the steps mentioned by you, works fine. Notification is send successfully.
2. Difference between my application and example code is the use of APIs.
a. Example uses **sr_event_notif_send_tree()** while our application uses **sr_event_notif_send()**

Below is the test performed:

1. Create a connection towards Sysrepo.=>SUCCESS
2. Started a session towards Operational DB.=>SUCCESS
3. Write data into DB and went into sleep in application.=>SUCCESS
4. Check if data is written using netopeer2-cli.=>SUCCESS


> get --filter-xpath /o-ran-ald-port:ald-ports-io/ald-port/dc-enabled-status
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ald-ports-io xmlns="urn:o-ran:ald-port:1.0">
    <ald-port>
      <name>ALD_PORT</name>
      <dc-enabled-status>true</dc-enabled-status>
    </ald-port>
  </ald-ports-io>
</data>

>

5. Check the same data using sr_get_items() example application.=>FAILURE NO DATA IN GET

(Added some debug logs to the example..)

 ./sr_get_items_example /o-ran-ald-port:* operational  
  
 Application will get "/o-ran-ald-port:*" from "operational" datastore.

After connect
After session
**After get count: 1**
/o-ran-ald-port:ald-ports-io (container)


6. Tried calling sr_get_items() in my own application before calling sr_event_notif_send(), to get the data.=>FAILURE
**Output same as above.**

7. Call sr_event_notif_send() to send notification.=>FAILURE
**Same error for leafref. But when calling send notification using example code, it is a success.**

Now replaced the sr_event_notif_send() with sr_event_notif_send_tree() and creating the nodes as per done in notification example code.=>SUCCESS


**Code Added in Application:**
                struct lyd_node *notif = NULL;
                const struct ly_ctx *ctx;
                 ctx = sr_get_context(connection);


                const char *node_path = NULL, *node_val, *path;
                node_path = "ald-port[name=\'ALD_PORT\']/dc-enabled-status";
                node_val = "true";
                path = "/o-ran-ald-port:dc-enabled-status-change";
                
                  /* create the notification */
                    if (lyd_new_path(NULL, ctx, path, NULL, 0, &notif)) {
                        printf("Creating notification \"%s\" failed.\n", path);
                    }
                
                    /* add the input value */
                    if (node_path) {
                        if (lyd_new_path(notif, NULL, node_path, node_val, 0, NULL)) {
                            printf("Creating value \"%s\" failed.\n", node_path);
                        }
                    }


                if (SR_ERR_OK != sr_event_notif_send_tree(session, notif, 0, 0))
                      {
                      std::cout << "In notification_send_handler(): sr_event_notif_send() returned Error" << std::endl;
                
                      }

   So, my final analysis says, The notification logic works using the libyang based tree API, but not works if used the other API. 
   Even the same data if not getting fetched via the sr_get_items() API. 
    
   Request you to check the behavior once.
   Thanks!

**Comment by michalvasko** [comment] 2021-09-17 07:46
I have tried it again, still no success in reproducing any problems.
```
# sysrepoctl -a -s YANG_MODULE/ -i YANG_MODULE/common_models/interfaces/o-ran-ald-port.yang
# oper_data_push_example "/o-ran-ald-port:ald-ports-io/ald-port[name='ALD_PORT']/dc-enabled-status" true
Application will set "/o-ran-ald-port:ald-ports-io/ald-port[name='ALD_PORT']/dc-enabled-status" to value "true".



 ========== WAITING AS OWNER OF SET DATA ==========
```
and in another terminal I have executed the [test.c.txt](https://github.com/sysrepo/sysrepo/files/7183678/test.c.txt), which uses `sr_event_notif_send()`, successfully. `sr_get_items()` does "not work" for you because it selects specific nodes, not subtrees like `sr_get_data()`. So if you use XPath `/o-ran-ald-port:*//.`, you will get all the data.

**Comment by ankit7gup** [comment] 2021-09-21 05:24
Hi Michal, We got the problem in our code as well, for the boolean the structure was not getting filled correctly. It was getting value "true" instead of true.
The fix works fine. Thanks!

**Closed** 2021-09-24 07:11 UTC
Labels: is:bug, status:completed
