### ISSUE TITLE
Error importing data in to ietf-interfaces -  Failed to append data tree bbf-fastdsl

### ISSUE THREAD

**Issue by darshana-jk** [sysrepo/sysrepo#798] opened 2017-04-20 07:56 UTC
I'm running the devel branches of all packages (sysrepo, netopeer2, libyang and libnetconf2) and the source is up-to-date.

Initially I can load the bbf-vdsl modules  [bbf-vdsl YANG](https://github.com/BroadbandForum/yang/blob/master/standard/interface/bbf-vdsl.yang) and they are loaded and initialized successfully (I had to do a minor patch to load it: [bbf-vdsl-pointers.yang.patch.txt](https://github.com/sysrepo/sysrepo/files/941162/bbf-vdsl-pointers.yang.patch.txt)). 
```
sudo sysrepoctl -l
Sysrepo schema directory: /usr/local/etc/sysrepo/yang/
Sysrepo data directory:   /usr/local/etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                   | Revision   | Data Owner          | Permissions | Submodules                    | Enabled Features
---------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-acm              | 2012-02-22 | root:root           | 666         |                               |
ietf-netconf-notifications    | 2012-02-06 | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | root:root           | 666         |                               |
nc-notifications              | 2008-07-14 | root:root           | 666         |                               |
notifications                 | 2008-07-14 | root:root           | 666         |                               |
iana-if-type                  | 2014-05-08 |                     |             |                               |
ietf-interfaces               | 2014-05-08 | root:root           | 666         |                               |
ietf-yang-types               | 2013-07-15 |                     |             |                               |
bbf-yang-types                | 2016-07-18 |                     |             |                               |
bbf-fastdsl                   | 2016-07-18 |                     |             |                               |
bbf-vdsl                      | 2016-07-18 | root:root           | 666         |  bbf-vdsl-base-body bbf-vdsl-test-mode-body bbf-vdsl-channel-body bbf-vdsl-base bbf-vdsl-line bbf-vdsl-inventory-body bbf-vdsl-xtu bbf-vdsl-data-rate-profile-body bbf-vdsl-service-profiles bbf-vdsl-line-spectrum-profile-body bbf-vdsl-mode-specific-psd-profile-body bbf-vdsl-upstream-power-back-off-profile-body bbf-vdsl-downstream-power-back-off-profile-body bbf-vdsl-radio-frequency-interference-profile-body bbf-vdsl-spectrum-profiles bbf-vdsl-noise-margin-profile-body bbf-vdsl-impulse-noise-protection-delay-profile-body bbf-vdsl-virtual-noise-profile-body bbf-vdsl-sos-profile-body bbf-vdsl-impulse-noise-monitoring-profile-body bbf-vdsl-re-initialization-policy-profile-body bbf-vdsl-vectoring-profile-body bbf-vdsl-data-gathering-profile-body bbf-vdsl-quality-profiles bbf-vdsl-line-status-body bbf-vdsl-xtu-line-status-body bbf-vdsl-xtu-band-status-body bbf-vdsl-xtu-annex-c-status-body bbf-vdsl-xtu-channel-status-body bbf-vdsl-status-monitoring bbf-vdsl-xtu-line-performance-body bbf-vdsl-xtu-channel-performance-body bbf-vdsl-performance-management bbf-vdsl-xtu-line-threshold-profile-body bbf-vdsl-xtu-channel-threshold-profile-body bbf-vdsl-threshold-management bbf-vdsl-xtu-sub-carrier-status-body bbf-vdsl-xtu-data-gathering-report-body bbf-vdsl-test-diagnostics bbf-vdsl-pointers|
```
Some background:
The bbf-vdsl modules depends on ietf-interfaces, bbf-fastdsl, iana-if-type, bbf-yang-types  and they are loaded automatically by sysrepoctl as dependencies. The modules bbf-vdsl and bbf-fastdsl augments ietf-interfaces, also bbf-fastdsl, iana-if-type, bbf-yang-types are not data carrying modules.
  
My final objective is to load the startup config for the  bbf-vdsl module, however starting small I first tried to load the sysrepo/examples/yang/ietf-interfaces.data.xml to the sysrepo (just to test it out, also I still don't have an acceptable startup config for  bbf-vdsl). 

I can see two errors:
```
$ sudo sysrepocfg --import=/PMA/sysrepo/examples/yang/ietf-interfaces.data.xml --datastore=startup --format=xml ietf-interfaces
[ERR] (rp_dt_get_values_wrapper_with_opts:1392) Validation of xpath /iana-if-type:*//. failed.
[ERR] (rp_get_items_req_process:821) Get items failed for '/iana-if-type:*//.', session id=19634643.
[ERR] (cl_request_process:490) Error by processing of the get-items request (session id=19634643): Resolving XPath expression "/iana-if-type:*//." failed..
[ERR] (sr_get_items_iter:1030) Sending get_items request failed '/iana-if-type:*//.'
[ERR] (srcfg_get_module_data:247) Error by sr_get_items_iter: Request contains unknown element
[ERR] (dm_append_data_tree:1859) Failed to merge bbf-fastdsl data tree
[ERR] (dm_load_dependant_data:1935) Failed to append data tree bbf-fastdsl
[ERR] (dm_validate_data_info:2533) Loading dependant modules failed for ietf-interfaces
[ERR] (rp_dt_commit:819) Data validation failed: (no error)
[ERR] (sr_commit:2082) Commit operation failed with 0 error(s).
[ERR] (srcfg_import_datastore:895) Error returned from sr_commit: Validation of the changes failed.
[ERR] (srcfg_import_datastore:898) (null) : Validation of the changes failed
Errors were encountered during importing. Cancelling the operation.
```
1. Validation of xpath /iana-if-type:*//. failed
2. 
[ERR] (dm_append_data_tree:1859) Failed to merge bbf-fastdsl data tree
[ERR] (dm_load_dependant_data:1935) Failed to append data tree bbf-fastdsl
[ERR] (dm_validate_data_info:2533) Loading dependant modules failed for ietf-interfaces
[ERR] (rp_dt_commit:819) Data validation failed: (no error)

For the second error, as the  bbf-fastdsl augments ietf-interfaces, it looks like the data manager tries to append the data tree of the  bbf-fastdsl module to the data tree of ietf-interfaces (is it?)and fails.

**Comment by michalvasko** [comment] 2017-04-20 08:13
Hi,
could you please attach your `repository/data/internal/sysrepo-module-dependencies.xml`? Thanks.

Regards,
Michal

**Comment by darshana-jk** [comment] 2017-04-20 08:20
Please see the attached:
[sysrepo-module-dependencies.xml.txt](https://github.com/sysrepo/sysrepo/files/941531/sysrepo-module-dependencies.xml.txt)

**Comment by michalvasko** [comment] 2017-04-20 10:33
Hi,
this may actually be caused by wrong `implemented` flag (`iana-if-type` should not be implemented). I was trying to fix this in #795, but am still struggling with failing tests, so you can try merging my pull request and to be safe, clearing your `repository` and `build` directories and try to install it all again.

Regards,
Michal

**Comment by darshana-jk** [comment] 2017-04-20 13:51
Hi,
I tried the #795 pull request. It doesn't fully work for me. The bbf-vdsl module installation fails with a "The module is already installed, exiting" error for an included submodule of the bbf-vdsl.

```
[/WORK/PMA/bbf-yang/standard/interface]$ sudo sysrepoctl -i -g bbf-vdsl.yang --owner=root:root --permissions=666 -S -s /usr/local/etc/sysrepo/yang -L 4
[DBG] (sr_log_stderr:141) Setting log level for stderr logs to 4.
Installing a new module from file 'bbf-vdsl.yang'...
Installing the YANG file to '/usr/local/etc/sysrepo/yang/bbf-vdsl@2016-07-18.yang'...
Resolving dependency: 'bbf-vdsl' includes 'bbf-vdsl-base-body'...
Installing the YANG file to '/usr/local/etc/sysrepo/yang//submodules/bbf-vdsl-base-body@2016-07-18.yang'...
Resolving dependency: 'bbf-vdsl' includes 'bbf-vdsl-test-mode-body'...
...
...
Resolving dependency: 'iana-if-type' imports 'ietf-interfaces'...
Installing the YANG file to '/usr/local/etc/sysrepo/yang/ietf-interfaces@2014-05-08.yang'...
Resolving dependency: 'bbf-vdsl-pointers' imports 'bbf-yang-types'...
Installing the YANG file to '/usr/local/etc/sysrepo/yang/bbf-yang-types@2016-07-18.yang'...
Installing data files for module 'bbf-vdsl'...
[WRN] (md_insert_lys_module:1841) Module 'bbf-vdsl-base-body@2016-07-18' is already installed.
The module is already installed, exiting...
```

The bbf-vdsl-base-body is the first submodule included by bbf-vdsl module. This is  probably because the md_insert_lys_module() is getting called for bbf-vdsl-base-body (recursively I guess) the flag  implemented=true and we jump to the "Module '%s' is already installed." block.
Please find a gdb back-trace attached.
[gdb1.txt](https://github.com/sysrepo/sysrepo/files/943261/gdb1.txt)

**Comment by michalvasko** [comment] 2017-04-20 14:08
Hi,
you are right, I fixed this situation for imports, but not for includes. Please try to pull again, it should install now.

Regards,
Michal

**Comment by michalvasko** [comment] 2017-04-21 07:48
Hi,
you can try to merge also #803 as I think your problem is exactly the same. Hopefully, all these pull requests will be merged into *sysrepo* soon.

Regards,
Michal

**Comment by fabioantonini** [comment] 2017-04-21 08:21
Hi Michal
I pulled the #803 patch and re-built everything. I continue to have some problems with 'includes'. Does #803 patch provide a fix for 'includes' or not?
Regards
fabio

**Comment by darshana-jk** [comment] 2017-04-21 08:35
Hi Michal,

It looks like for me the issue is solved.
I can successfully load the module, startup data and also dump the loaded data.
I'm not closing the issue here, as @fabioantonini 's asked a question.
Please close the issue when you can.

**Comment by fabioantonini** [comment] 2017-04-21 08:40
Hi Darshana and Michal
I pulled up #803 but not #795. So let me pull also #795 and give a try to verify. 
regards
fabio

**Comment by fabioantonini** [comment] 2017-04-21 08:58
Hi
I have pulled up also #795.
Anyway I get the same error. Let me explain the sequence of the installation commands I have

I want to install on my board all the modules required to run some sysrepo's test.

Here below the installation messages

sysrepoctl -i -g /etc/configs/sysrepo/repo/tests/module-b@2016-02-05.yang
Installing a new module from file '/etc/configs/sysrepo/repo/tests/module-b@2016-02-05.yang'...
Installing the YANG file to '/etc/configs/sysrepo/current/yang/module-b@2016-02-05.yang'...
Resolving dependency: 'module-b' imports 'module-a'...
Installing the YANG file to '/etc/configs/sysrepo/current/yang/module-a@2016-02-02.yang'...
Resolving dependency: 'module-a' includes 'sub-a-one'...
Installing the YANG file to '/etc/configs/sysrepo/current/yang//submodules/sub-a-one@2016-02-02.yang'...
Resolving dependency: 'module-a' includes 'sub-a-two'...
Installing the YANG file to '/etc/configs/sysrepo/current/yang//submodules/sub-a-two@2016-02-02.yang'...
Installing data files for module 'module-b'...
Resolving dependency: 'module-b' imports 'module-a'...
Installing data files for module 'module-a'...
Notifying sysrepo about the change...
Install operation completed successfully.
~ # sysrepoctl -i -g /etc/configs/sysrepo/repo/tests/module-a@2016-02-10.yang
Installing a new module from file '/etc/configs/sysrepo/repo/tests/module-a@2016-02-10.yang'...
Installing the YANG file to '/etc/configs/sysrepo/current/yang/module-a@2016-02-10.yang'...
Resolving dependency: 'module-a' includes 'sub-a-one'...
Installing the YANG file to '/etc/configs/sysrepo/current/yang//submodules/sub-a-one@2016-02-10.yang'...
Resolving dependency: 'module-a' includes 'sub-a-two'...
Installing the YANG file to '/etc/configs/sysrepo/current/yang//submodules/sub-a-two@2016-02-02.yang'...
Installing data files for module 'module-a'...
Notifying sysrepo about the change...
Install operation completed successfully.
~ # sysrepoctl -i -g /etc/configs/sysrepo/repo/tests/module-a@2016-02-02.yang
Installing a new module from file '/etc/configs/sysrepo/repo/tests/module-a@2016-02-02.yang'...
Installing the YANG file to '/etc/configs/sysrepo/current/yang/module-a@2016-02-02.yang'...
Resolving dependency: 'module-a' includes 'sub-a-one'...
Installing the YANG file to '/etc/configs/sysrepo/current/yang//submodules/sub-a-one@2016-02-02.yang'...
Resolving dependency: 'module-a' includes 'sub-a-two'...
Installing the YANG file to '/etc/configs/sysrepo/current/yang//submodules/sub-a-two@2016-02-02.yang'...
Installing data files for module 'module-a'...
Notifying sysrepo about the change...
Install operation completed successfully.
~ # sysrepoctl -i -g /etc/configs/sysrepo/repo/tests/info-module.yang        
Installing a new module from file '/etc/configs/sysrepo/repo/tests/info-module.yang'...
[ERR] Unable to insert instance of (md_module_t *) into a balanced tree.
Error: Failed to initialize module dependencies context.
Install operation failed.

At this point I cannot install/uninstall anything else and have the same error message
I think the issue can be reproduced easily.
"[ERR] Unable to insert instance of (md_module_t *) into a balanced tree.
Error: Failed to initialize module dependencies context."

Am I missing any else pull request? Our opinion is that the installation of the second revision of module-a corrupts something.

Thanks a lot
fabio

**Comment by michalvasko** [comment] 2017-04-21 10:02
Hi Fabio,
the last error is definitely something that should never happen, but I will not fix this right now. We have just now discovered that the whole `implemented` flag problem is yet again more complex than we thought meaning it is still not correct even with the pull requests. This may also be the root cause for this problem, so it would be a waste of time to fix it now, if it still occurs after our (hopefully) final fix, I will look into it.

Regards,
Michal

**Comment by fabioantonini** [comment] 2017-04-21 10:12
Hi Michal

thanks a lot for your feedback

I look forward to your final fix

regards

fabio

**Comment by michalvasko** [comment] 2017-04-25 08:14
Hi,
so all the promised changes should be in the pull request #810, please try it out, best if both of you could. @fabioantonini Your *sysrepoctl* problem should be also solved (yes, you cannot install 2 same modules in different revisions, one of them can only be imported by another module, which is `module-b` in this case).

Regards,
Michal

**Comment by darshana-jk** [comment] 2017-04-25 12:29
Hi,

I tried it and I can now successfully load the startup config for ietf-interfaces while augmented modules exists ( bbf-fastdsl & bbf-vdsl). Please close the issue when @fabioantonini has tested.

Thank you for the fix.
Darshana.

**Comment by fabioantonini** [comment] 2017-04-26 06:26
Hi

I have fetched #810 patches, do I need to fetch any other patch to do 
the test?

thanks

fabio

**Comment by michalvasko** [comment] 2017-04-26 06:47
Hi Fabio,
no, that is all you should need.

Regards,
Michal

**Comment by fabioantonini** [comment] 2017-04-26 06:58
Hi Michal
I can confirm what you said. The problem has been fixed on my side too. I cannot install two modules with different revisions but one of them has been imported by another module (module-b in my case).
So the issue can be closed.
Thanks
fabio

**Closed** 2017-04-26 07:04 UTC
