### ISSUE TITLE
Yang model is installed failed when there is list  node containing grouping and the list is nested in rpc.

### ISSUE THREAD

**Issue by niuzhiquan** [sysrepo/sysrepo#487] opened 2016-11-01 12:14 UTC
Hi
When my yang model contains list node containing grouping and the list is nested in rpc, it can not be installed. Here is my yang model:

```YANG
module Me {
    yang-version "1";
    namespace "urn:zte:params:xml:ns:yang:ran:me";
	prefix me;
	
	grouping group {		 
		 leaf name {
			type string;
		}

         leaf f1 {
            type uint64;
        }                 
    }

    rpc mo {
        input {
	    leaf-list f2 {
                type uint64;
            }		
        }
        output {
			container childMo{         
				list lst{
					key name;			 
					uses group;
				}
			}      
		}
	}	
}
```
and the error message is:
```
[root@e949c9ac82e6 build]# sysrepoctl -i -g /root/z-conf/data/alarm/model2.yang 
Installing a new module from file '/root/z-conf/data/alarm/model2.yang'...
[ERR] (srctl_ly_log_cb:479) libyang: The "config" value of the "name" key differs from its list config value.
[ERR] (srctl_ly_log_cb:479) libyang: Module "Me" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.
```

However, when  the list is nested in a container, the yang model can be installed successfully. The yang model like:
```YANG
module Me {
    yang-version "1";
    namespace "urn:zte:params:xml:ns:yang:ran:me";
	prefix me;
	
	grouping group {		 
		 leaf name {
			type string;
		}

         leaf f1 {
            type uint64;
        }                 
    }
	container mo{
		container childMo{         
			list lst{
				key name;					 
				uses group;
			}
		}      
    }   
}
```

**Comment by lukasmacko** [comment] 2016-11-02 15:15
The issue is fixed in the latest devel branch of libyang. Yang model can be installed into sysrepo.

**Closed by lukasmacko** 2016-11-02 15:15 UTC
Labels: external issue
