### ISSUE TITLE
Client applications are not notified when their connection gets dropped

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#643] opened 2016-12-20 14:04 UTC
When a callback gets stuck for some reason (pausing in a debugger is one possibility), sysrepo detects that situation, logs an error on both sides of the connection, and eventually closes the connection. This is from the client's log:
```
[error] (cl_sm_conn_out_buff_flush:414) Error by writing data to fd 7: Broken pipe.
[error] (cl_sm_conn_in_buff_process:1088) Error by processing of the message.
[warning] (cl_sm_fd_read_data:1171) Error by processing of the input buffer of fd=7, closing the connection.
```
However, my SR-client application is not notified about this failure in any way. There's no return code because the callback doesn't really *call* anything.

If the CB is a ``module_change_cb``, chances are that the client has already fetched the data through sysrepo client API and got stuck for some reason when e.g. configuring a local daemon, or when talking to a piece of weird HW.

If the CB is a ``dp_get_items_cb``, the client is probably just writing something via ``sr_val_set_xpath``, and there's again no return code for connection errors.

What about adding yet another callback which gets called upon a dropped connection?

**Comment by joanlandry** [comment] 2016-12-20 14:51
It would be very helpful to have callbacks for when a user connects and disconnects as well.

**Comment by jktjkt** [comment] 2016-12-21 09:57
> It would be very helpful to have callbacks for when a user connects and disconnects as well.

You might want to create a separate issue for that, though -- this one is about error handling within applications that talk to SR, not about getting notified about users' activity.

**Comment by rastislavszabo** [comment] 2016-12-21 10:22
Agreed, this is something that would need to be addressed. 

Just to remark:

For "normal" Sysrepo connections & sessions, you should get `SR_ERR_DISCONNECT` error if the connection is broken and you are trying to use it for a subsequent API call (if not, it is a bug).

For "notification" connections and sessions, if the connection breaks in between of two Sysrepo Engine requests (e.g. in between of two commits), Sysrepo should just reconnect successfully and everything should work as expected.

The issue appears if the connection breaks while handling a callback - this needs to be addressed.

**Comment by rastislavszabo** [comment] 2016-12-21 10:26
> It would be very helpful to have callbacks for when a user connects and disconnects as well.

What is your use case for this? In any case, it is not related to this issue.

**Comment by joanlandry** [comment] 2016-12-21 10:30
we allow other user interfaces to view and know who is connected to the system, currently we have no way to know who is logged in via netconf.

**Comment by lukasmacko** [comment] 2017-02-01 12:02
I've tested couple of scenarios I'll try to summarize my findings (tested on the latest devel branch):

Subscriber is able to successfully handle the restart of daemon among commmits. 
As pointed by @rastislavszabo only issue appears when a daemon (or in general originator of commit) restarts during the callback execution. Despite the fact that currently we "only" log the error, I am not sure if adding an error callback would be helpful. 

My main concerns are: 
1. the recovery of this kind of error is problematic if the orginator of the commit was restarted it doesn't make much sense to retry connecting to him because the commit information was most probably lost, the best that can be done in "error callback" is something like just logging, what is already done (If the logging is main goal, it could be handled somehow in a user set callback by `sr_log_set_cb`).
2. further calls succeeds without any aditional recovery

@jktjkt correct me, if you have been thinking of a different callback purpose

**Comment by jktjkt** [comment] 2017-02-01 12:59
Actually I'm describing a different situation. I have a daemon which talks to some flaky piece of HW. The sole purpose of this daemon is to make the HW's features available over NETCONF. The daemon registers two callbacks, one for a ``module_change_cb``, another for ``dp_get_items_cb``. If any of these two callbacks take too much time to execute (perhaps due to a bug in the daemon code which fails to properly set a timeout for HW communication, but it can be easily triggered by pausing in a debugger), ``sysrepod`` treats this as an error condition, "unpublishes" the relevant YANG module, and it won't talk to my daemon anymore. This is a correct behavior from SR's point of view, but it is a bad outcome for the system as a whole because no corrective action is taken and the fancy piece of HW cannot be configured/monitored/... over NETCONF anymore.

In my specific use case, it would be just fine to have SR client library ``abort()`` within my dameon and rely on a service manager (systemd) to restart the daemon. For other use cases (think Dropbear with a patch to configure over SR), something so drastic would be unacceptable, so they might want to re-register the callbacks through application logic. Either way, the SR client (Dropbear, or my daemon) has to know "hey, that module which I happen to implement is no longer available in SR", and react to that.

**Comment by lukasmacko** [comment] 2017-02-02 08:34
ah, I see. I was able to reproduce unintended removal of subscription when `dp_get_items_cb` takes too much time. Basicly, if the dp_get_items response arrives after the session that issued data provide request is closed, the subscription is removed. I think in this case it is not intentional.

@jktjkt could you give a try to this path?

```patch
diff --git a/src/connection_manager.c b/src/connection_manager.c
index 07feb31..9e5a297 100755
--- a/src/connection_manager.c
+++ b/src/connection_manager.c
@@ -984,7 +984,12 @@ cm_conn_msg_process(cm_ctx_t *cm_ctx, sm_connection_t *conn, uint8_t *msg_data,
         if (SR_ERR_OK != rc) {
             SR_LOG_ERR("Unable to find session context for session id=%"PRIu32" (conn=%p).",
                     msg->session_id, (void*)conn);
-            rc = SR_ERR_INVAL_ARG;
+            if (SR__MSG__MSG_TYPE__RESPONSE == msg->type && SR__OPERATION__DATA_PROVIDE == msg->response->operation) {
+                SR_LOG_DBG_MSG("Ignoring not found session for data provide response");
+                rc = SR_ERR_OK;
+            } else {
+                rc = SR_ERR_INVAL_ARG;
+            }
             goto cleanup;
         }
         if (CM_AF_UNIX_SERVER != conn->type && conn != session->connection) {
```

`module_change_cb` seems to stay in place even if takes too long.

**Comment by jktjkt** [comment] 2017-02-02 16:22
Thanks, this patch makes a difference, it solves the problem with a stuck ``dp_get_items_cb``. And just to confirm, I don't see any issue with a ``module_change_cb``.

**Comment by lukasmacko** [comment] 2017-02-03 11:27
ok, great! The patch is applied in the devel branch, closing the issue.

**Closed by lukasmacko** 2017-02-03 11:27 UTC
Labels: enhancement
