### ISSUE TITLE
Client registration sr_session_refresh function causes timeout

### ISSUE THREAD

**Issue by dongyangf** [sysrepo/sysrepo#1214] opened 2018-07-07 02:02 UTC
Modify sysrepo/example/application_example.c and sysrepo/example/sr_set_item_example.c file.  Registration sr_session_refresh  in sr_set_item_example.c  and loop set value. 

Step 1, start ./sysrepod -d
Step 2, start ./application_example  ietf-interfaces
Step 3, start ./sr_set_item_example

### source file
[sr_set_item_example_sysrepo_timeout.zip](https://github.com/sysrepo/sysrepo/files/2172527/sr_set_item_example_sysrepo_timeout.zip)

When sr_set_item_example loop count >1000, sysrepod output timeout log "[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=`543963805`."
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1215071185.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=2004798600.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1365670137.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=543963805.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1236429003.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=2001550166.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=2021789464.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=815909225.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=255988400.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=603510189.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=504321440.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1414672993.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=934570216.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1076504883.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1763423402.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1925153035.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1232410200.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=815687008.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1800310448.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=510546061.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=613173864.

**Comment by michalvasko** [comment] 2018-07-09 12:13
Hi,
thanks for the modified files so that our use-case is exactly the same. I have tested it and it worked (almost) as expected. There was a problem with storing notifications (which I finally safely reproduced now, thanks for that) that should be fixed now (update *libyang* and *sysrepo*).

Except for that, there is a significant performance slowdown every 10 minutes after which it becomes fast again. The cause of this are notifications, more specifically their ineffective storage implementation. The commit can be so slow after a few minutes that on slower machines it can time out, which I suspect is the problem in your case. You can try disabling config-change notifications (sysrepo `cmake -DSTORE_CONFIG_CHANGE_NOTIF=OFF`) and re-running your test. Having tested it without these notifications I have noticed no performance degradation, no sysrepo errors, and have reached `count = 40 000` before terminating the test.

Regarding the notifications, we will improve them in the future but we are currently focusing on optimizing other sysrepo operations.

Regards,
Michal

**Comment by dongyangf** [comment] 2018-07-10 03:16
Hi Michalvasko,

Thanks for you help.

I checkout sysrepo devel branch and libyang master branch lasted source. 
sysrepo:
commit a8675651bbf6b1745f23e9864601fa61c2abba0e
Merge: a1df2ec fbb2d97
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Mon Jul 9 14:34:39 2018 +0200

    Merge pull request #1217 from michalvasko/devel
    
    Proper namespace extraction from identityrefs

Libyang:
commit 54565783b15741b2421b03c1531ae552b0d6d680
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Mon Jul 9 13:56:45 2018 +0200

    VERSION bump to version 0.15.139


[examples.zip](https://github.com/sysrepo/sysrepo/files/2178708/examples.zip)

### Use attached example test again, the sysrepo already output timeout.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1725091110.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1170699736.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=760906763.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=487020648.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1127930290.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=790222925.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=68882403.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1037035700.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1853747452.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1471999939.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=295804448.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1749273458.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=476090289.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=2096314560.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=247915498.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=122303485.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1835609176.



Thanks, Dongyang

**Comment by michalvasko** [comment] 2018-07-10 06:58
Hi Dongyang,
this is the original issue we started with, so did you try what I suggested, to compile sysrepo with `-DSTORE_CONFIG_CHANGE_NOTIF=OFF`? You can also try to increase the request timeout with `-DREQUEST_TIMEOUT=60`, for example.

Regards,
Michal

**Comment by dongyangf** [comment] 2018-07-11 00:35
Hi Michalvasko,

Thanks for you information.
CMakeList.txt config as :

set(STORE_CONFIG_CHANGE_NOTIF 0 CACHE BOOL
    "Save config-change notifications (RFC 6470) in the notification store (slows down the commit process).")

set(REQUEST_TIMEOUT 60 CACHE INTEGER
    "Timeout (in seconds) for Sysrepo API requests. Set to 0 for no timeout.")

But sysrepod still timeout.  Could you try  run my example?

Thanks, Dongyang

**Comment by michalvasko** [comment] 2018-07-11 07:01
Hi Dongyang,
I have tried to run your example several times and no timeout occurred for me. What is the exact behaviour of *sysrepod*, when does it start to time out? Does it gradually get slower until you get a timeout? After how many iterations does it happen?

Regards,
Michal

**Comment by dongyangf** [comment] 2018-07-12 05:53
Hi Michalvasko,
### system Environmental 
fandy@shasta-1:~/sysrepo$ git branch 
* devel
  master
fandy@shasta-1:~/sysrepo$ git log
commit 66971af07c47164622bb9fda8fae4bdf2b9a08fb
Merge: e788ae9 88e8ccf
Author: Mislav Novakovic <mislav.novakovic@gmail.com>
Date:   Wed Jul 11 17:04:15 2018 +0200

    Merge pull request #1226 from sartura/swig_refactor
    
    Swig refactor

fandy@shasta-1:~/sysrepo$ ls -l /usr/local/lib/libyang*
lrwxrwxrwx 1 root root      15 7月  10 02:57 /usr/local/lib/libyang.so -> libyang.so.0.15
lrwxrwxrwx 1 root root      19 7月  10 02:57 /usr/local/lib/libyang.so.0.15 -> libyang.so.0.15.139
-rw-r--r-- 1 root root 2033008 7月  10 02:56 /usr/local/lib/libyang.so.0.15.139

/usr/local/lib/libyang:
total 8
drwxr-xr-x 2 root root 4096 7月  10 02:57 extensions
drwxr-xr-x 2 root root 4096 7月  10 02:57 user_types
fandy@shasta-1:~/sysrepo$ ls -l /usr/local/lib/libsysrepo.*
-rw-r--r-- 1 root root 6693556 7月  12 05:46 /usr/local/lib/libsysrepo.a
lrwxrwxrwx 1 root root      17 7月  12 05:48 /usr/local/lib/libsysrepo.so -> libsysrepo.so.0.7
lrwxrwxrwx 1 root root      19 7月  12 05:48 /usr/local/lib/libsysrepo.so.0.7 -> libsysrepo.so.0.7.4
-rw-r--r-- 1 root root 3183192 7月  12 05:46 /usr/local/lib/libsysrepo.so.0.7.4


### sysrepo information
fandy@shasta-1:~/sysrepo/build/src$ sudo ./sysrepod -d
[WRN] (dm_apply_persist_data_for_model:948) Persist file for module ietf-netconf-acm does not exist.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1713385552.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=2077889640.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1712159096.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=2007797506.


### application_example

 ========== CONFIG HAS CHANGED, CURRENT RUNNING CONFIG /ietf-interfaces:interfaces/interface: ==========



 ========== CONFIG HAS CHANGED, CURRENT RUNNING CONFIG /ietf-interfaces:interfaces/interface: ==========



 ========== CONFIG HAS CHANGED, CURRENT RUNNING CONFIG /ietf-interfaces:interfaces/interface: ==========



### sr_set_item information
fandy@shasta-1:~/sysrepo/build/examples$ sudo ./sr_set_item_example 
[sudo] password for fandy: 

count = 100
count = 200
count = 300
count = 400
count = 500
count = 600
count = 700
count = 800
count = 900
count = 1000
count = 1100
count = 1200
count = 1300
count = 1400
count = 1500

**Comment by michalvasko** [comment] 2018-07-12 08:05
Hi,
I have tried it again, with no problems. Anyway, this is obviously very dependent on the machine you are testing it so I will not be able to reproduce it. We are not moving with the issue anywhere so I am closing it, it should get solved once we get to notification and some other optimizations.

Regards,
Michal

**Closed by michalvasko** 2018-07-12 08:05 UTC

**Comment by dongyangf** [comment] 2018-07-17 05:53
Hi michalvasko,

I tried the test case in the new environment, and there will still be timeout.
Can you tell me the shared libraries that need to check the environment?  
fandy@:~$ ls -l /usr/local/lib/libyang*
lrwxrwxrwx 1 root root      15 6月  21 08:33 /usr/local/lib/libyang.so -> libyang.so.0.15
lrwxrwxrwx 1 root root      19 6月  21 08:33 /usr/local/lib/libyang.so.0.15 -> libyang.so.0.15.130
-rw-r--r-- 1 root root 2029152 7月  10 13:48 /usr/local/lib/libyang.so.0.15.130

/usr/local/lib/libyang:
total 8
drwxr-xr-x 2 root root 4096 7月  10 13:49 extensions
drwxr-xr-x 2 root root 4096 7月  10 13:49 user_types
fandy@:~$ ls -l /usr/local/lib/libsysrepo.*
-rw-r--r-- 1 root root 3464740 7月  17 10:57 /usr/local/lib/libsysrepo.a
lrwxrwxrwx 1 root root      17 6月  21 08:36 /usr/local/lib/libsysrepo.so -> libsysrepo.so.0.7
lrwxrwxrwx 1 root root      19 6月  21 08:36 /usr/local/lib/libsysrepo.so.0.7 -> libsysrepo.so.0.7.4
-rw-r--r-- 1 root root 1696360 7月  17 10:57 /usr/local/lib/libsysrepo.so.0.7.4
fandy@:~$ ls -l /usr/local/lib/libssh*
lrwxrwxrwx 1 root root     11 11月  7  2017 /usr/local/lib/libssh.so -> libssh.so.4
lrwxrwxrwx 1 root root     15 11月  7  2017 /usr/local/lib/libssh.so.4 -> libssh.so.4.4.2
-rw-r--r-- 1 root root 604256 11月  7  2017 /usr/local/lib/libssh.so.4.4.2
lrwxrwxrwx 1 root root     19 11月  7  2017 /usr/local/lib/libssh_threads.so -> libssh_threads.so.4
lrwxrwxrwx 1 root root     23 11月  7  2017 /usr/local/lib/libssh_threads.so.4 -> libssh_threads.so.4.4.2
-rw-r--r-- 1 root root   8872 11月  7  2017 /usr/local/lib/libssh_threads.so.4.4.2

~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.10' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 

Branch: devel  v- 66971af
Run result 
./sr_set_item_example 

count = 100
count = 200
count = 300
count = 400
count = 500Error by sr_commit: Timeout has expired

count = 600
count = 700
count = 800
count = 900
count = 1000
count = 1100
count = 1200Error by sr_commit: Timeout has expired

count = 1300
count = 1400
count = 1500
count = 1600
count = 1700
count = 1800Error by sr_commit: Timeout has expired

count = 1900
count = 2000
count = 2100
count = 2200
count = 2300
count = 2400
count = 2500
count = 2600
count = 2700
count = 2800Error by sr_commit: Timeout has expired

Sysrepo

[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1831044700.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1787087731.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1773254120.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1454217755.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1712588357.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1349003774.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1370127656.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=781793233.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1548523690.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1549928900.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1792437309.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=336320172.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=678076545.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=244407734.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1698625489.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1263730198.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=848458589.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1333396408.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=272324568.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=403947048.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=392553610.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1732836790.
