### ISSUE TITLE
Cannot install modules with if-feature in enum definition

### ISSUE THREAD

**Issue by avazquezrd** [sysrepo/sysrepo#3028] opened 2023-03-22 14:54 UTC
I am experiencing some errors during installation of different YANG models. The error is always very similar, here is an example:

```
sysrepoctl -i bbf-qos-classifiers.yang -s .
[ERR] Enumeration type of node "bac-color" without any (or all disabled) valid values. (Schema location "/bbf-qos-classifiers:classifiers/system-default-actions/bac-color".)
sysrepoctl error: Failed to install modules (libyang error)
```

This `bac-color` leaf mentioned in error has this definition:

```yang
      leaf bac-color {
        type union {
          type write-bac-color;
          type enumeration {
            enum discard {
              description
                "The BAC color 'discard' means that frames will not
                 get a BAC color by default. When the processing of
                 the frame comes to a moment that a BAC color is
                 needed, and none is assigned through having applied
                 the QoS profiles, then the system shall discard the
                 frame.";
            }
          }
        }
        description
          "Defines the frame's BAC color for when color-aware
           classification and/or actions are needed in the processing
           of a frame. More specific, when the frame is to be queued
           using a color aware BAC method.";
      }
```

And the `write-bac-color` type:

```yang
  typedef write-bac-color {
    type union {
      type bbf-qos-t:qos-color;
      type enumeration {
        enum copy-from-flow-color {
          if-feature "qos-bac-color-from-flow-color";
          description
            "The BAC color of a frames is the same as its flow
             color.";
        }
      }
    }
    description
      "The BAC color to be written. Either this is a specific BAC
       color value, or it indicates where to take the BAC color
       from.";
  }
```

So, I assume that the error is related with that feature not being enabled (but I cannot enable the feature without installing the module first, and I also do not want to enable that specific feature).

YANG models used for this examples are attached.

[yang.zip](https://github.com/sysrepo/sysrepo/files/11041378/yang.zip)

**Comment by michalvasko** [comment] 2023-03-23 07:10
Fair enough, I have not seen such a use of `enumeration` before but makes sense, should be fixed in latest *libyang*.

> but I cannot enable the feature without installing the module first

Not true, you can enable features right when you are installing a module.

**Comment by avazquezrd** [comment] 2023-03-23 07:27
Thanks! I didn't know that I could install a module and enable features at the same time. In any case, I will test with the latest _libyang_ version.

**Comment by michalvasko** [comment] 2023-03-23 07:41
Okay and note that not only that, you can also install several modules at once and especially if you have lots of them, it can speed up the installation greatly so I suggest you use it. You should always be able to see all these features in `sysrepoctl -h`.

**Comment by avazquezrd** [comment] 2023-03-23 11:46
With latest devel branch I am having this error in different modules, not sure if this is a known issue:

```
root@9c53c54d5a2c:/opt/bisdn/yang/bbf# sysrepoctl -i bbf-qos-classifiers.yang -s .
[ERR] JSON DS file: Opening "/etc/sysrepo/data/bbf-xpon-types.factory-default" failed (No such file or directory).
[ERR] Callback "load" of plugin "JSON DS file" for module "bbf-xpon-types" failed.
sysrepoctl error: Failed to install modules (System function call failed)
For more details you may try to increase the verbosity up to "-v3".
```

**Comment by michalvasko** [comment] 2023-03-23 12:53
I am not able to reproduce, the module installs just fine. Can you please provide all the steps up until this one? Best starting with `make sr_clean`.

**Comment by avazquezrd** [comment] 2023-03-23 14:03
I have tried again a clean install and I found out that the problem may be in some old modules I was mixing; now it works fine, sorry for the mistake.

However, you mentioned that I could install several modules at once, which would speed up the installation. Actually, I have +300 modules (including dependencies), and I have tried what you mention, by using:

```
sysrepoctl --install <module_1> --install <module_N> -s .
```

This throws an error due to "already installed" modules (I guess that a module is installed when it is imported by another one and then it fails when it attempts to install the module again). Do you have any suggestion about a good way to implement this?

Currently I use this simple script to install modules (I skip submodules):

```bash
for i in *.yang; do
  [ "$(sed -n '/module/{/submodule/!p;q}' "$i")" ] && sysrepoctl -i $i -s .
done
```

To follow your advice, I tried this (and it throws the error I mention above):

```bash
MODULES=""

for i in *.yang; do
  if [ "$(sed -n '/module/{/submodule/!p;q}' "$i")" ]; then
    MODULES+="--install $i "
  fi
done

sysrepoctl $MODULES -s .
```

Output (if then I list modules, it has not installed anything):

```
./install.sh 
[ERR] Module "ietf-interfaces" is already in sysrepo.
```

**Comment by michalvasko** [comment] 2023-03-24 07:09
Alright, try it with the latest *sysrepo*. As long as you do not need to enable any features (or you do that after installing everything), it should work.

**Comment by avazquezrd** [comment] 2023-03-24 09:47
Now, instead of an error I get a warning, but also a `segmentation fault`:

```
./install.sh 
[INF] Connection 4 created.
[WRN] Module "ietf-interfaces" is already in sysrepo.
./install.sh: line 9:   402 Segmentation fault      sysrepoctl $MODULES -s . -v3
```

I have checked that `MODULES` contains all the modules I want to install. If I install the modules individually, everything works fine.

**Comment by michalvasko** [comment] 2023-03-24 09:56
I have tested with some ~100 BBF modules I found locally, worked fine. Can you please provide the modules so I can reproduce the crash?

**Comment by avazquezrd** [comment] 2023-03-24 09:59
Of course, I attach them here.

[yang.zip](https://github.com/sysrepo/sysrepo/files/11060718/yang.zip)

**Comment by avazquezrd** [comment] 2023-03-24 10:48
Running `make sr_clean` works fine.

Additional steps I had after installing _libyang_ and _sysrepo_ (_devel_ branch in both of them) is installing _libnetconf2_ and _netopeer2_ (tested with latest _devel_). I have noticed that if I do not install _netopeer2_, modules are installed without errors, except that missing `iana-crypt-hash` error you mention (I guess it is added when _netopeer2_ is installed).

**Comment by michalvasko** [comment] 2023-03-24 10:55
Thanks, that reproduced it, will work correctly now, I hope.

**Comment by avazquezrd** [comment] 2023-03-24 11:04
It does, thanks!

**Closed** 2023-03-24 11:05 UTC
Labels: is:bug, status:completed
