### ISSUE TITLE
New sysrepo: leafref pointed to an augmented leaf can't be resolved

### ISSUE THREAD

**Issue by huw305** [sysrepo/sysrepo#1684] opened 2019-11-21 02:58 UTC
### Description
Hello, please help to analyze my problem below.
My test case has 3 yang models: "mytest.yang", "mytest-augment.yang" and "myref.yang".
"myref" defined a notification which referenced an augmented leaf in "mytest-augment".
```
module: mytest
  +--rw test-state
     +--rw test-case* [name]
        +--rw name                    string
        +--ro result*
        |  +--ro x?   uint32
        |  +--ro y?   uint32
        |  +--ro z?   uint32
        +--rw mytest-augment:index?   uint16

module: myref
  notifications:
    +---n test-done
    |  +--ro test-result* [index]
    |     +--ro index    -> /mytest:test-state/mytest:test-case/mytest-augment:index
    |     +--ro x?       uint32
    |     +--ro y?       uint32
    |     +--ro z?       uint32
    +---n test-fail
```
The configuration xml for "mytest" yang model is:
```
<test-state xmlns="urn:sysrepo:mytest">
  <test-case>
    <name>one</name>
    <index xmlns="urn:sysrepo:mytest-augment">1</index>
  </test-case>
  <test-case>
    <name>two</name>
  </test-case>
  <test-case>
    <name>three</name>
  </test-case>
</test-state>
```
And my user code to generate the notification for "myref":
```
static void prepare_notification_data()
{
	sr_val_t *vals;
	size_t vals_cnt;
	char node_path[256];
	const char *fmt = "/myref:test-done/test-result[index='1']/%s";

	vals_cnt = 3;
	if (sr_new_values(vals_cnt, &vals) != SR_ERR_OK) {
		return;
	}

	sprintf(node_path, fmt, "x");
	sr_val_set_xpath(&vals[0], node_path);
	vals[0].type = SR_UINT32_T;
	vals[0].data.uint32_val = 101;

	sprintf(node_path, fmt, "y");
	sr_val_set_xpath(&vals[1], node_path);
	vals[1].type = SR_UINT32_T;
	vals[1].data.uint32_val = 102;

	sprintf(node_path, fmt, "z");
	sr_val_set_xpath(&vals[2], node_path);
	vals[2].type = SR_UINT32_T;
	vals[2].data.uint32_val = 103;
	sr_event_notif_send(sess, "/myref:test-done", vals, vals_cnt);
}
```

**Expected behavior:**
The notification can be reported

**Actual behavior:**
The leafref can't be resolved, the log is as below:
```
Nov  7 05:28:07 sysrepo-plugind[1120]: [INF] Published event "operational" with ID 6.
Nov  7 05:28:07 sysrepo-plugind[1120]: [INF] Processing "operational" "mytest" event with ID 6.
Nov  7 05:28:07 sysrepo-plugind[1120]: [WRN] mytest state callback: mod=mytest, path=/mytest:test-state
Nov  7 05:28:07 sysrepo-plugind[1120]: [INF] Finished processing "operational" event with ID 6.
Nov  7 05:28:07 sysrepo-plugind[1120]: [INF] Event "operational" with ID 6 succeeded.
Nov  7 05:28:07 sysrepo-plugind[1120]: [ERR] Leafref "/mytest:test-state/mytest:test-case/mytest-augment:index" of value "1" points to a non-existing leaf.
Nov  7 05:28:07 sysrepo-plugind[1120]: [ERR] Notification validation failed.
```

### Versions
libyang.so.1.3.6
libsysrepo.so.4.0.10
libnetconf2.so.1.1.0
netopeer2-server 1.1.1

### Attachments
[mytest.zip](https://github.com/sysrepo/sysrepo/files/3872572/mytest.zip)

Thanks!

**Comment by michalvasko** [comment] 2019-11-21 16:05
Most likely a duplicate of #1685.

**Comment by huw305** [comment] 2019-11-22 06:23
Agree with you it's a duplicate of #1685 but maybe the case is a bit different.
I added a subscription to "mytest" operational data and the callback will reply a few state data leaves.
So I can get:
```
> get --filter-xpath /mytest:*
DATA
<test-state xmlns="urn:sysrepo:mytest">
  <test-case>
    <name>one</name>
    <index xmlns="urn:sysrepo:mytest-augment">1</index>
    <result>
      <x>101</x>
      <y>102</y>
      <z>103</z>
    </result>
  </test-case>
  <test-case>
    <name>two</name>
  </test-case>
  <test-case>
    <name>three</name>
  </test-case>
</test-state>
```
But still the leafref can't be resolved and the notification validation failed:
```
Nov  7 16:52:29 sysrepo-plugind[1174]: [INF] Published event "operational" with ID 129.
Nov  7 16:52:29 sysrepo-plugind[1174]: [INF] Processing "operational" "mytest" event with ID 129.
Nov  7 16:52:29 sysrepo-plugind[1174]: [WRN] mytest state callback: mod=mytest, path=/mytest:test-state
Nov  7 16:52:29 sysrepo-plugind[1174]: [INF] Finished processing "operational" event with ID 129.
Nov  7 16:52:29 sysrepo-plugind[1174]: [INF] Event "operational" with ID 129 succeeded.
Nov  7 16:52:29 sysrepo-plugind[1174]: [ERR] Leafref "/mytest:test-state/mytest:test-case/mytest-augment:index" of value "1" points to a non-existing leaf.
Nov  7 16:52:29 sysrepo-plugind[1174]: [ERR] Notification validation failed.
Nov  7 16:52:29 sysrepo-plugind[1174]: [ERR] sr_event_notif_send failed, rc=12(Validation failed).
```
So the presence of "mytest" operational data can't help to resolve the leafref pointed to configuration data of "mytest-augment".

**Closed** 2019-11-25 09:18 UTC
