### ISSUE TITLE
ERR: Locking a mutex failed (sr_shmmain_lock_remap: Connection timed out).

### ISSUE THREAD

**Issue by dwbxm** [sysrepo/sysrepo#1724] opened 2019-12-24 12:15 UTC
hi,
I have encountered the problem. sysrepo-plugind is running in virtual machine, VMware, centos8.

my operations are following:
1、built the sysrepo and installed , then built the examples--oven.
2、installed yang model ,sysrepoctl -i sysrepo/examples/plugin/oven.yang
3、mkdir /usr/lib64/sysrepo/plugins -p,
cp sysrepo/examples/liboven.so /usr/lib64/sysrepo/plugins/
4、sysrepo-plugind -v debug -d . everything is ok.

then , i shutdown the vm when sysrepo-plugind is running.After a day, i start the vm,
sysrepo-plugind -v debug -d, output
**[INF]: Scheduled changes not applied because of other existing connections.
[ERR]: Locking a mutex failed (sr_shmmain_lock_remap: Connection timed out).
sysrepo-plugind error: Failed to connect (Timeout expired).**
****
Then,I want to see whether the oven.yang model is installed or not,
sysrepoctl -l, output
**[ERR]: Locking a mutex failed (sr_shmmain_lock_remap: Connection timed out).
sysrepoctl error: Failed to connect (Timeout expired).**

I think the error is the same as above. Yes?

Regards,
dwbxm

**Comment by michalvasko** [comment] 2020-01-02 08:39
Hi,
the problem is that you are not terminating `sysrepo-plugind` correctly. However, it should still work if you first run `sysrepoctl -R` before starting `sysrepo-plugind`. Please, try it and in case it does not work, please post the output of that command with INF messages (`sysrepoctl -R -v3`).

Regards,
Michal

**Comment by maksimvuleta** [comment] 2020-01-30 13:25
I have the same issue. 
Here is the sysrepoctl -R output: 

devel@ubuntu:~/smb_share$ sudo sysrepoctl -R -v 4
[INF]: Scheduled changes not applied because of other existing connections.
[ERR]: Waiting on a conditional variable failed (sr_shmmain_lock_remap: Connection timed out).
sysrepoctl error: Failed to connect (Timeout expired)


Only restart my machine help.

**Comment by michalvasko** [comment] 2020-01-30 13:40
Okay, can you please post the steps from starting the machine (you do not have to reboot, just run `make shm_clean`, it is the same) until you get this error?

Regards,
Michal

**Comment by maksimvuleta** [comment] 2020-01-30 13:53
Boot the machine:
Check is there my 'dummy' yang module installed.

_sudo sysrepoctl -l_
_..._
_dummy                      | 2019-10-18 | I     | root:root   | 600         |            |_
_..._

Run the sysrepo-plugind:
_sudo sysrepo-plugind -d -v 4_

Run the server: 
_sudo netopeer2-server -d -v 9_

Use the netopeer2-cli to connect and get data, the data is there:
_> get --filter-xpath /dummy:*
DATA
<dummy-data xmlns="urn:sysrepo:dummy">
  <dummy-list>
    <index>5</index>
    <list-object-a>5</list-object-a>
  </dummy-list>
</dummy-data>_

 Try to edit 'dummy' data and got an "Segmentation fault" on the sysrepo-plugind side.

Try to run the sysrepo-plugind again:
_devel@ubuntu:~/smb_share$ sudo sysrepo-plugind -d -v 4
[INF]: Scheduled changes not applied because of other existing connections.
[ERR]: Waiting on a conditional variable failed (sr_shmmain_lock_remap: Connection timed out).
sysrepo-plugind error: Failed to connect (Timeout expired)_


Then try to recover:
_devel@ubuntu:~/smb_share$ sudo sysrepoctl -R -v 4
[INF]: Scheduled changes not applied because of other existing connections.
[ERR]: Waiting on a conditional variable failed (sr_shmmain_lock_remap: Connection timed out).
sysrepoctl error: Failed to connect (Timeout expired)_

**Comment by michalvasko** [comment] 2020-01-30 14:07
Okay, before I investigate further, what *sysrepo* version are you using?

Regards,
Michal

**Comment by maksimvuleta** [comment] 2020-01-30 14:13
devel@ubuntu:~$ sysrepoctl -V
sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.21 (SO v4.1.8)

**Comment by michalvasko** [comment] 2020-01-30 14:28
Right, the `master`. Please switch to `devel` (as mentioned here) and try again.

Regards,
Michal

**Comment by maksimvuleta** [comment] 2020-01-31 09:43
Ok, I will try.

When do you expect to make a new release on the master branch?

**Comment by michalvasko** [comment] 2020-01-31 09:45
Soon, the beginning of next week I hope.

Regards,
Michal

**Comment by maksimvuleta** [comment] 2020-01-31 09:46
That will be great. 
Thanks for the help and informations.

Best regards,
Maksim.

**Comment by maksimvuleta** [comment] 2020-01-31 10:07
Just one more question.
Which versions of the libyang, libnetconf2, netopeer2-server do you recommend to use with the sysrepo latest devel branch?

**Comment by michalvasko** [comment] 2020-01-31 10:11
It is quite simple, the policy is the same on all projects. Using `devel` (or `devel-server`) on all the branches should always work, otherwise there is a bug. Similarly, `master` of all the projects must work together (compile) even though there may be some bugs that were fixed only in `devel`.

Regards,
Michal

**Closed** 2022-05-27 13:04 UTC
