### ISSUE TITLE
Default value for config=false leafs

### ISSUE THREAD

**Issue by yank0vy3rdna** [sysrepo/sysrepo#3317] opened 2024-06-10 06:45 UTC
Hello, Michal.

Please, explain for me, why default value for config=true leafs in the list is visible in operational datastore,
```
# cat r.yang
module examples {
  yang-version 1.1;
  namespace "urn:examples";
  prefix e;

  container test {
    list test2 {
      key "id";
      min-elements 2;
      leaf id {
        type string;
      }
      leaf test3 {
	type string;
        config true;
	default "test";
      }
    }
  }
}
# cat r.xml
<test xmlns="urn:examples">
	<test2>
		<id>3</id>
	</test2>
	<test2>
		<id>4</id>
	</test2>
</test>
# sysrepoctl -i r.yang -I r.xml
# ./subscribe_on_examples_module_to_make_list_elements_visible_in_oper_datastore &
# sysrepocfg -X -d operational -m examples -e report-all
<test xmlns="urn:examples">
  <test2>
    <id>3</id>
    <test3>test</test3>
  </test2>
  <test2>
    <id>4</id>
    <test3>test</test3>
  </test2>
</test>
```
but if it is config=false parameters, default value is ignored:
```
# cat r.yang
module examples {
  yang-version 1.1;
  namespace "urn:examples";
  prefix e;

  container test {
    list test2 {
      key "id";
      min-elements 2;
      leaf id {
        type string;
      }
      leaf test3 {
	type string;
        config false;
	default "test";
      }
    }
  }
}
# cat r.xml
<test xmlns="urn:examples">
	<test2>
		<id>3</id>
	</test2>
	<test2>
		<id>4</id>
	</test2>
</test>
# sysrepoctl -i r.yang -I r.xml
# ./subscribe_on_examples_module_to_make_list_elements_visible_in_oper_datastore &
# sysrepocfg -X -d operational -m examples -e report-all
<test xmlns="urn:examples">
  <test2>
    <id>3</id>
  </test2>
  <test2>
    <id>4</id>
  </test2>
</test>
```

Seems like default value shouldn't be ignored for config=false leafs, considering that if they are not inside the list element, but inside the container, then it is not ignored:
```
root@cb1:~# cat r.yang
module examples {
  yang-version 1.1;
  namespace "urn:examples";
  prefix e;

  container test {
    leaf test1 {
      type string;
      config false;
      default "test";
    }
  }
}
# sysrepoctl -i r.yang
# sysrepocfg -X -d operational -m examples -e report-all
<test xmlns="urn:examples">
  <test1>test</test1>
</test>
```

Tested on libsysrepo v2.2.150 (SO v7.23.1).

Thanks in advance!

**Comment by michalvasko** [comment] 2024-06-12 07:30
This is very implementation-dependent, works as intended, and is the result of different handling of configuration and state data. Default configuration data are populated "automatically" while any state data need to be provided by one of the [methods](https://netopeer.liberouter.org/doc/sysrepo/devel/html/index.html#oper_data).

**Comment by Gris87** [comment] 2024-06-18 19:06
Do you want to say that it is always works this way or we can just change method `pull` to `push`?

**Comment by michalvasko** [comment] 2024-06-19 05:47
I only said that if you want to get default state nodes in the operational datastore, you can use `pull` or `push` method of populating the operational datastore.

**Comment by yank0vy3rdna** [comment] 2024-06-21 15:52
If any state data need to be provided by one of the [methods](https://netopeer.liberouter.org/doc/sysrepo/devel/html/index.html#oper_data), why in example below sysrepo works like this?
There are no providers of data, so i didn't get why can I see default value of test1 leaf this way?

```
root@cb1:~# cat r.yang
module examples {
  yang-version 1.1;
  namespace "urn:examples";
  prefix e;

  container test {
    leaf test1 {
      type string;
      config false;
      default "test";
    }
  }
}
# sysrepoctl -i r.yang
# sysrepocfg -X -d operational -m examples
<test xmlns="urn:examples">
  <test1>test</test1>
</test>
```

**Comment by michalvasko** [comment] 2024-06-26 06:28
You are right about that, not sure how the code got wrong, should be fixed, though.

**Closed** 2024-12-02 12:28 UTC
Labels: is:bug, status:completed
