### ISSUE TITLE
Sometimes got  Internal errorInternal error (sysrepo-1.4.58/src/shm_sub.c:1223).

### ISSUE THREAD

**Issue by qjwu888** [sysrepo/sysrepo#1992] opened 2020-05-21 02:42 UTC
Hi Michal,
netopeer2 devel-server 1.1.20
libnetconf2 devel
sysrepo devel    2020.0318 
libyang devel

Callhome mode ,**sometimes** got error log and configuration failure,hope to get your help, thanks!

For some reasion, i can't update the last version now.
I am on MTK7621 mips platform .

rc = sr_module_change_subscribe(session, "gwtt-ietf-ipsec", "/gwtt-ietf-ipsec:ikev2/ike-global-configuration", ike_global_subtree_change_cb, *private_ctx,100,SR_SUBSCR_DEFAULT,&ipsec_plugin->subscription);
rc = sr_module_change_subscribe(session, "gwtt-ietf-ipsec", "/gwtt-ietf-ipsec:ikev2/ike-peer", ike_peer_subtree_change_cb, *private_ctx,99, SR_SUBSCR_CTX_REUSE, &ipsec_plugin->subscription);
rc = sr_module_change_subscribe(session, "gwtt-ietf-ipsec", "/gwtt-ietf-ipsec:ikev2/proposal", ike_proposal_subtree_change_cb, *private_ctx,98, SR_SUBSCR_CTX_REUSE, &ipsec_plugin->subscription);
rc = sr_module_change_subscribe(session, "gwtt-ietf-ipsec", "/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal",ipsec_subtree_change_cb,*private_ctx,97,SR_SUBSCR_CTX_REUSE,&ipsec_plugin>subscription);

I found the error in  shm_sub.c    
FUNCTION: sr_shmsub_change_notify_change_abort 
    /* unreachable unless the failed subscription was not found */
    SR_ERRINFO_INT(&err_info);

[09-26-29][INF]: LY: Resolving unresolved data nodes and their constraints...
[09-26-29][INF]: LY: All data nodes and constraints resolved.
[09-26-29][INF]: LY: Resolving unresolved data nodes and their constraints...
[09-26-29][INF]: LY: All data nodes and constraints resolved.
[09-26-29][INF]: SR: Published event "rpc" with ID 228 priority 0 for 1 subscribers.
[09-26-29][INF]: SR: Processing "/ietf-netconf:lock" "rpc" event with ID 228 priority 0 (remaining 1 subscribers).
[09-26-29][INF]: SR: Successful processing of "rpc" event with ID 228 priority 0 (remaining 0 subscribers).
[09-26-29][INF]: SR: Event "rpc" with ID 228 priority 0 succeeded.
[09-26-29][INF]: NP: Session 1: thread 0 event new RPC.
[09-26-29][INF]: LY: Resolving unresolved data nodes and their constraints...
[09-26-29][INF]: LY: All data nodes and constraints resolved.
[09-26-29][INF]: LY: Resolving unresolved data nodes and their constraints...
[09-26-29][INF]: LY: All data nodes and constraints resolved.
[09-26-29][INF]: SR: Published event "rpc" with ID 228 priority 0 for 1 subscribers.
[09-26-29][INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 228 priority 0 (remaining 1 subscribers).
[09-26-29][INF]: SR: Published event "change" with ID 92 priority 100 for 1 subscribers.
**[09-26-29][INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 92 priority 100 (remaining 1 subscribers).
[09-26-29][INF]: Successful processing of "change" event with ID 92 priority 100 (remaining 0 subscribers).**
**[09-26-29][INF]: SR: Event "change" with ID 92 priority 100 succeeded.
[09-26-29][INF]: SR: Published event "change" with ID 92 priority 99 for 1 subscribers.
[09-26-29][INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 92 priority 99 (remaining 1 subscribers).
[09-26-30][INF]: SR: Processing "notif" "gwtt-alarm" event with ID 130.
[09-26-30][INF]: SR: Successful processing of "notif" event with ID 130 priority 0 (remaining 0 subscribers).
[09-26-34][ERR]: SR: Callback event "change" with ID 92 processing timed out.
[09-26-34][WRN]: SR: Event "change" with ID 92 priority 99 failed (Timeout expired).
[09-26-34][INF]: SR: Published event "abort" with ID 92 priority 100 for 1 subscribers.
[09-26-34][ERR]: SR: Internal error (sysrepo-1.4.2/src/shm_sub.c:1118).**
**[09-26-34][INF]: SR: Failed processing of "rpc" event with ID 228 priority 0 (remaining 1 subscribers).
[09-26-34][ERR]: SR: Internal error (sysrepo-1.4.2/src/shm_sub.c:1118).
[09-26-34][WRN]: SR: Event "rpc" with ID 228 priority 0 failed (User callback failed).
[09-26-34][ERR]: NP: Failed to send an RPC (User callback failed).**
[09-26-34][INF]: NP: Session 1: thread 0 event new RPC.
[09-26-34][INF]: NP: Session 1: thread 0 event reply error.
[09-26-34][INF]: LY: Resolving unresolved data nodes and their constraints...
[09-26-34][INF]: LY: All data nodes and constraints resolved.

The following commit patched, sometimes still got error.
* sub shm BUGFIX SHM re-lock checking
Whenever subscriber locked the SHM,
started processing an event, unlocked
it, and then locked again, it must be
checked that no unexpected changes occured
such as another subscriber writing an
error or simply a timeout from the originator.
Also, write lock is needed when remapping
the SHM to a specific size as it can be shrinked
effectively removing some data from its end.
Fixes #1949

**Comment by michalvasko** [comment] 2020-05-21 06:30
Hi,
could you please use at least the latest releases? Or current `devel`. And please always specify the project versions (like you did for *netopeer2*), I do not know what `2020.0318` is supposed to mean. Anyway, if you reproduce it with the versions I mentioned, please let us know.

Regards,
Michal

**Comment by qjwu888** [comment] 2020-05-21 06:51
Hi Michal,
Thanks for your reply.
sysrepo devel  VERSION bump to version 1.4.26
We have another processe to send notif to ODL，could you chack the following log again,
**when** processing "gwtt-ietf-ipsec" "change" event with ID 92 priority 99 (remaining 1 subscribers).
**another processe** processing "notif" "gwtt-alarm" event with ID 130.
**then**  Callback event "change" with ID 92 processing timed out.

[09-26-29][INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 92 priority 100 (remaining 1 subscribers).
[09-26-29][INF]: Successful processing of "change" event with ID 92 priority 100 (remaining 0 subscribers).
[09-26-29][INF]: SR: Event "change" with ID 92 priority 100 succeeded.
[09-26-29][INF]: SR: Published event "change" with ID 92 priority 99 for 1 subscribers.
[09-26-29][INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 92 priority 99 (remaining 1 subscribers).
[09-26-30][INF]: SR: Processing "notif" "gwtt-alarm" event with ID 130.
[09-26-30][INF]: SR: Successful processing of "notif" event with ID 130 priority 0 (remaining 0 subscribers).
[09-26-34][ERR]: SR: Callback event "change" with ID 92 processing timed out.
[09-26-34][WRN]: SR: Event "change" with ID 92 priority 99 failed (Timeout expired).
[09-26-34][INF]: SR: Published event "abort" with ID 92 priority 100 for 1 subscribers.
[09-26-34][ERR]: SR: Internal error (sysrepo-1.4.2/src/shm_sub.c:1118).
[09-26-34][INF]: SR: Failed processing of "rpc" event with ID 228 priority 0 (remaining 1 subscribers).
[09-26-34][ERR]: SR: Internal error (sysrepo-1.4.2/src/shm_sub.c:1118).
[09-26-34][WRN]: SR: Event "rpc" with ID 228 priority 0 failed (User callback failed).
[09-26-34][ERR]: NP: Failed to send an RPC (User callback failed).

**Comment by qjwu888** [comment] 2020-05-21 08:30
Hi Michal,
I'll try to use the last version to test.
But i found ,the same code, X86 CPU device ,not meet this issue.
Could you give me some suggestions?

[13-15-42][INF]: LY: Resolving unresolved data nodes and their constraints...
[13-15-42][INF]: LY: All data nodes and constraints resolved.
[13-15-42][INF]: LY: Resolving unresolved data nodes and their constraints...
[13-15-42][INF]: LY: All data nodes and constraints resolved.
[13-15-42][INF]: SR: Published event "rpc" with ID 1719 priority 0 for 1 subscribers.
[13-15-42][INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 1719 priority 0 (remaining 1 subscribers).
[13-15-42][INF]: LY: Resolving unresolved data nodes and their constraints...
[13-15-42][INF]: LY: All data nodes and constraints resolved.
[13-15-42][INF]: SR: Published event "change" with ID 637 priority 100 for 1 subscribers.
[13-15-42][INF]: SR: Processing "notif" "gwtt-alarm" event with ID 837.
[13-15-42][INF]: SR: Successful processing of "notif" event with ID 837 priority 0 (remaining 0 subscribers).
[13-15-42][INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 637 priority 100 (remaining 1 subscribers).
[13-15-42][INF]: Successful processing of "change" event with ID 637 priority 100 (remaining 0 subscribers).
[13-15-42][INF]: SR: Event "change" with ID 637 priority 100 succeeded.
[13-15-42][INF]: SR: Published event "change" with ID 637 priority 99 for 1 subscribers.
[13-15-42][INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 637 priority 99 (remaining 1 subscribers).
[13-15-42][INF]: SR: Processing "notif" "gwtt-alarm" event with ID 838.
[13-15-42][INF]: Successful processing of "change" event with ID 637 priority 99 (remaining 0 subscribers).
[13-15-42][INF]: SR: Successful processing of "notif" event with ID 838 priority 0 (remaining 0 subscribers).
[13-15-42][INF]: SR: Event "change" with ID 637 priority 99 succeeded.
[13-15-42][INF]: SR: Published event "change" with ID 637 priority 98 for 1 subscribers.
[13-15-42][INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 637 priority 98 (remaining 1 subscribers).
[13-15-42][INF]: Successful processing of "change" event with ID 637 priority 98 (remaining 0 subscribers).
[13-15-42][INF]: SR: Event "change" with ID 637 priority 98 succeeded.
[13-15-42][INF]: SR: Published event "change" with ID 637 priority 97 for 1 subscribers.
[13-15-42][INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 637 priority 97 (remaining 1 subscribers).
[13-15-42][DBG]: plugin: ipsec_subtree : get ipsec_subtree changes all successfully, xpath=/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal, line=2705
[13-15-42]
[13-15-42][INF]: Successful processing of "change" event with ID 637 priority 97 (remaining 0 subscribers).
[13-15-42][INF]: SR: Event "change" with ID 637 priority 97 succeeded.

**Comment by michalvasko** [comment] 2020-05-21 08:33
Okay, then please test it with the latest version. It makes sense that it works on x86 because the problem is triggered by a callback being too slow and its timeout running out. However, even if that happens, you should not see any internal errors so that is what I would fix if reproducible in the current version.

Regards,
Michal

**Comment by qjwu888** [comment] 2020-05-25 02:37
Hi Michal,
1. The last version is testing ,if get the resault ,will give you reply.
2. I think ,my callback isn't slow. it is not the cause of the timeout.
3. The internal error just happen in my mips CPU device.
4. I found every internal error happended with the same following info.
**If processing "gwtt-ietf-ipsec" "change" event with ID xxx priority 99, almost the same time , another processe  "gwtt-alarm" processing of "notif" event . internal error happended**
5. Is there some other timeout parameters that can be adjusted？
example:
set(RPC_TIMEOUT 6 CACHE STRING "Timeout in seconds of the global RPC callback, that calls all the other specific RPC callbacks. This timeout should always be higher than that of other RPCs")
set(POLL_IO_TIMEOUT 50 CACHE STRING "Timeout in milliseconds of polling sessions for new data. It is also used for synchronization of low level IO such as sending a reply while a notification is being sent")
To fix a bug in mips cpu, have chenged  POLL_IO_TIMEOUT 50ms.
In my now code is :
```diff
-        rc = nc_ps_poll(np2srv.nc_ps, 10, &ncs);
+        rc = nc_ps_poll(np2srv.nc_ps, 50, &ncs);
```

[13-15-41][INF]: SR: Published event "change" with ID 393 priority 100 for 1 subscribers.
[13-15-41][INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 393 priority 100 (remaining 1 subscribers).
[13-15-41][INF]: Successful processing of "change" event with ID 393 priority 100 (remaining 0 subscribers).
[13-15-41][INF]: SR: Event "change" with ID 393 priority 100 succeeded.
[13-15-41][INF]: SR: Published event "change" with ID 393 priority 99 for 1 subscribers.
[13-15-41][INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 393 priority 99 (remaining 1 subscribers).
[13-15-42][INF]: SR: Processing "notif" "gwtt-alarm" event with ID 492.
[13-15-42][INF]: SR: Successful processing of "notif" event with ID 492 priority 0 (remaining 0 subscribers).
[13-15-46][ERR]: SR: Callback event "change" with ID 393 processing timed out.
[13-15-46][WRN]: SR: Event "change" with ID 393 priority 99 failed (Timeout expired).
[13-15-46][INF]: SR: Published event "abort" with ID 393 priority 100 for 1 subscribers.
[13-15-46][ERR]: SR: Internal error (sysrepo-1.4.2/src/shm_sub.c:1118).
[13-15-46][INF]: SR: Failed processing of "rpc" event with ID 958 priority 0 (remaining 1 subscribers).
[13-15-46][ERR]: SR: Internal error (sysrepo-1.4.2/src/shm_sub.c:1118).
[13-15-46][WRN]: SR: Event "rpc" with ID 958 priority 0 failed (User callback failed).
[13-15-46][ERR]: NP: Failed to send an RPC (User callback failed).

**Comment by michalvasko** [comment] 2020-05-25 07:51
Hi,
what exactly is your setup? I see messages prefixed with `SR/NP/...` from *netopeer2* mixed with messages without it, is this log from `syslog`? But generally it should not matter that a change and notification are being processed at the same time. Please, post the output with the latest version (if the problem is still there) so that at least the lines match and hopefully that will help.

Regards,
Michal

**Comment by qjwu888** [comment] 2020-05-26 11:59
Hi Michal,

libnetconf2-1.1.24
netopeer2-1.1.27
libyang-1.0.167
sysrepo-1.4.58    with   commit  7aeace4

![image](https://user-images.githubusercontent.com/50397234/82894499-3eb90100-9f85-11ea-9d6f-d59b1909ee47.png)

**Still found this error.**
**Callhome mode ,device connect to ODL via 4G net.
I am on  mips platform .**
As i said,
The internal error just happen in  mips CPU device with internet .mean Connect to ODL via internet. 
I found every internal error happended with the same following info.
If processing "gwtt-ietf-ipsec" "change" event with ID xxx priority 99, almost the same time , another processe "gwtt-alarm" processing of "notif" event . internal error happended

**The following is my subscribe code.**
rc = sr_module_change_subscribe(session, "gwtt-ietf-ipsec", "/gwtt-ietf-ipsec:ikev2/ike-global-configuration", ike_global_subtree_change_cb, *private_ctx,100,SR_SUBSCR_DEFAULT,&ipsec_plugin->subscription);
rc = sr_module_change_subscribe(session, "gwtt-ietf-ipsec", "/gwtt-ietf-ipsec:ikev2/ike-peer", ike_peer_subtree_change_cb, *private_ctx,99, SR_SUBSCR_CTX_REUSE, &ipsec_plugin->subscription);
rc = sr_module_change_subscribe(session, "gwtt-ietf-ipsec", "/gwtt-ietf-ipsec:ikev2/proposal", ike_proposal_subtree_change_cb, *private_ctx,98, SR_SUBSCR_CTX_REUSE, &ipsec_plugin->subscription);
rc = sr_module_change_subscribe(session, "gwtt-ietf-ipsec", "/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal",ipsec_subtree_change_cb,*private_ctx,97,SR_SUBSCR_CTX_REUSE,&ipsec_plugin>subscription);

**The following is my callback code.**
I found 2654 line print OK, but  **sr_get_change_next** timeout. my function **ike_subtree_set_change** no exec.


![image](https://user-images.githubusercontent.com/50397234/82898056-34016a80-9f8b-11ea-896b-5a0b4461208b.png)


static int ike_subtree_to_model(sr_session_ctx_t *session, const char *xpath)
{
	syslog(LOG_ERR,"====ike_peer_subtree_change_cb==ike_subtree_to_model====start==\n");
	sr_change_iter_t *it = NULL;
	int rc = SR_ERR_OK;
	int ret = SR_ERR_OK;
	sr_change_oper_t oper;
	sr_val_t *old_value = NULL;
	sr_val_t *new_value = NULL;
	char change_path[XPATH_MAX_LEN] = {
		0,
	};
	syslog(LOG_ERR,"====ike_peer_subtree_change_cb==ike_subtree_to_model====%d==\n",__LINE__);
	snprintf(change_path, XPATH_MAX_LEN, "%s//.", xpath);
	rc = sr_get_changes_iter(session, change_path, &it);
	if (SR_ERR_OK != rc)
	{
		ERR("ike_subtree: get changes iter fail, line=%d, xpath=%s, rc=%s\n",
			__LINE__, xpath, sr_strerror(rc));
		goto cleanup;
	}
	syslog(LOG_ERR,"====ike_peer_subtree_change_cb==ike_subtree_to_model====%d==\n",__LINE__);
	while (SR_ERR_OK == (ret = sr_get_change_next(session, it, &oper, &old_value, &new_value)))
	{
		ipsec_oper = oper;
		rc = ike_subtree_set_change(oper, old_value, new_value);
		sr_free_val(old_value);
		sr_free_val(new_value);
		if (SR_ERR_OK != rc)
		{
			ERR("ike_subtree : get ike_subtree change fail, op=%d, xpath=%s, old_xpath=%s, new_xpath=%s, line=%d\n",
				xpath, oper, old_value->xpath, new_value->xpath, __LINE__);
			sr_free_change_iter(it);
			return rc;
		}
	}
	syslog(LOG_ERR,"====ike_peer_subtree_change_cb==ike_subtree_to_model====end000==\n");
	gwtt_system("uci commit ipsec");
cleanup:
	sr_free_change_iter(it);
	syslog(LOG_ERR,"====ike_peer_subtree_change_cb==ike_subtree_to_model====end222==\n");
	return SR_ERR_OK;
}

**The detail log:**
[17-39-18]Tue May 26 17:38:28 2020 user.err : ====ike_peer_subtree_change_cb==SR_EV_CHANGE====start==
[17-39-18]Tue May 26 17:38:28 2020 user.err : ====ike_peer_subtree_change_cb==ike_subtree_to_model====start==
[17-39-18]Tue May 26 17:38:28 2020 user.err : ====ike_peer_subtree_change_cb==ike_subtree_to_model====2645==
[17-39-18]Tue May 26 17:38:28 2020 user.err : ====ike_peer_subtree_change_cb==ike_subtree_to_model====2654==
[17-39-18]Tue May 26 17:38:28 2020 daemon.notice netifd: Interface 'vxlan6554' is now down
[17-39-18]Tue May 26 17:38:28 2020 authpriv.info ipsec: 07[IKE] deleting IKE_SA Ikev2Peer_6554-TsName_6554[51] between 100.13.175.5[6554]...111.207.49.217[111.207.49.217]
[17-39-18]Tue May 26 17:38:28 2020 daemon.info ipsec: 07[IKE] deleting IKE_SA Ikev2Peer_6554-TsName_6554[51] between 100.13.175.5[6554]...111.207.49.217[111.207.49.217]
[17-39-18]Tue May 26 17:38:28 2020 user.debug : ALARM: parse_msg start
[17-39-18]Tue May 26 17:38:28 2020 user.debug : ALARM: parse_msg end
[17-39-18]Tue May 26 17:38:28 2020 user.debug : ALARM: queue_push_alarm start
[17-39-18]Tue May 26 17:38:28 2020 user.debug : ALARM: queue_push_alarm end
[17-39-18]Tue May 26 17:38:30 2020 user.debug : ALARM: print alarm params...
[17-39-18]Tue May 26 17:38:30 2020 user.debug : ALARM:     alarm code        : 10
[17-39-18]Tue May 26 17:38:30 2020 user.debug : ALARM:     alarm timestamp   : 643829908
[17-39-18]Tue May 26 17:38:30 2020 user.debug : ALARM:     alarm sequenceNo  : 10
[17-39-18]Tue May 26 17:38:30 2020 user.debug : ALARM:     alarm severity    : critical
[17-39-18]Tue May 26 17:38:30 2020 user.debug : ALARM:     alarm status      : occurred
[17-39-18]Tue May 26 17:38:30 2020 user.debug : ALARM:     alarm description : interface vxlan6554 DOWN
[17-39-18]Tue May 26 17:38:30 2020 user.debug : ALARM:     alarm resource id : vxlan6554
[17-39-18]Tue May 26 17:38:30 2020 user.debug : ALARM:     alarm esn         : 000fe9000015
[17-39-18]Tue May 26 17:38:30 2020 user.debug : ALARM: send alarm(vxlan6554 occurred 000fe9000015) to controller successfully!
[17-39-18]Tue May 26 17:38:33 2020 daemon.err netopeer2-server[5813]: Callback event "change" with ID 253 processing timed out.
[17-39-18]Tue May 26 17:38:33 2020 daemon.err netopeer2-server[5813]: Internal error (sysrepo-1.4.58/src/shm_sub.c:1223).
[17-39-18]Tue May 26 17:38:33 2020 daemon.err netopeer2-server[5813]: Internal error (sysrepo-1.4.58/src/shm_sub.c:1223).
[17-39-18]Tue May 26 17:38:33 2020 daemon.err netopeer2-server[5813]: Failed to send an RPC (User callback failed).

**Comment by qjwu888** [comment] 2020-05-26 12:23
![image](https://user-images.githubusercontent.com/50397234/82900229-c8210100-9f8e-11ea-8157-2a5ab45e92f1.png)

**Comment by qjwu888** [comment] 2020-05-26 12:24
![image](https://user-images.githubusercontent.com/50397234/82900229-c8210100-9f8e-11ea-8157-2a5ab45e92f1.png)

**Comment by qjwu888** [comment] 2020-05-27 01:49
Hi Michal,
**The following is netopeer2 、sysrepo-plugind  debug info.**

[09-24-27][INF]: NP: Session 2: thread 4 event new RPC.
[09-24-27][INF]: LY: Resolving unresolved data nodes and their constraints...
[09-24-27][INF]: LY: All data nodes and constraints resolved.
[09-24-27][INF]: LY: Resolving unresolved data nodes and their constraints...
[09-24-27][INF]: LY: All data nodes and constraints resolved.
[09-24-27][INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 635 priority 0 for 1 subscribers.
[09-24-27][INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 635 priority 0 (remaining 1 subscribers).
[09-24-27][INF]: Successful processing of "done" event with ID 106 priority 0 (remaining 0 subscribers).
[09-24-27][INF]: SR: Published event "change" "gwtt-ietf-ipsec" with ID 263 priority 100 for 1 subscribers.
[09-24-27][INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 263 priority 100 (remaining 1 subscribers).
[09-24-27][INF]: Successful processing of "change" event with ID 263 priority 100 (remaining 0 subscribers).
[09-24-27][INF]: SR: Event "change" with ID 263 priority 100 succeeded.
[09-24-27][INF]: SR: Published event "change" "gwtt-ietf-ipsec" with ID 263 priority 99 for 1 subscribers.
[09-24-27][INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 263 priority 99 (remaining 1 subscribers).
[09-24-28][INF]: SR: Processing "notif" "gwtt-alarm" event with ID 40.
[09-24-28][INF]: SR: Successful processing of "notif" event with ID 40 priority 0 (remaining 0 subscribers).
[09-24-32][ERR]: SR: Callback event "change" with ID 263 processing timed out.
[09-24-32][WRN]: SR: Event "change" with ID 263 priority 99 failed (Timeout expired).
[09-24-32][INF]: SR: Published event "abort" "gwtt-ietf-ipsec" with ID 263 priority 100 for 1 subscribers.
[09-24-32][ERR]: SR: Internal error (sysrepo-1.4.58/src/shm_sub.c:1223).
[09-24-32][INF]: SR: Failed processing of "rpc" event with ID 635 priority 0 (remaining 1 subscribers).
[09-24-32][ERR]: SR: Internal error (sysrepo-1.4.58/src/shm_sub.c:1223).
[09-24-32][WRN]: SR: Event "rpc" with ID 635 priority 0 failed (User callback failed).
[09-24-32][ERR]: NP: Failed to send an RPC (User callback failed).
[09-24-32][INF]: NP: Session 2: thread 2 event new RPC.
[09-24-32][INF]: NP: Session 2: thread 2 event reply error.

**The following is openwrt syslog**
[09-25-17]Wed May 27 09:24:27 2020 daemon.info netopeer2-server[22145]: Resolving unresolved data nodes and their constraints...
[09-25-17]Wed May 27 09:24:27 2020 daemon.info netopeer2-server[22145]: All data nodes and constraints resolved.
[09-25-17]Wed May 27 09:24:27 2020 daemon.info netopeer2-server[22145]: Resolving unresolved data nodes and their constraints...
[09-25-17]Wed May 27 09:24:27 2020 daemon.info netopeer2-server[22145]: All data nodes and constraints resolved.
[09-25-17]Wed May 27 09:24:27 2020 daemon.info netopeer2-server[22145]: Published event "rpc" "/ietf-netconf:edit-config" with ID 635 priority 0 for 1 subscribers.
[09-25-17]Wed May 27 09:24:27 2020 daemon.info netopeer2-server[22145]: Processing "/ietf-netconf:edit-config" "rpc" event with ID 635 priority 0 (remaining 1 subscribers).
[09-25-17]Wed May 27 09:24:27 2020 kern.info kernel: [67369.774700] device vxlan6554 left promiscuous mode
[09-25-17]Wed May 27 09:24:27 2020 daemon.info netopeer2-server[22145]: Published event "change" "gwtt-ietf-ipsec" with ID 263 priority 100 for 1 subscribers.
[09-25-17]Wed May 27 09:24:27 2020 daemon.info netopeer2-server[22145]: Event "change" with ID 263 priority 100 succeeded.
[09-25-17]Wed May 27 09:24:27 2020 daemon.info netopeer2-server[22145]: Published event "change" "gwtt-ietf-ipsec" with ID 263 priority 99 for 1 subscribers.
[09-25-17]Wed May 27 09:24:27 2020 user.err : ====ike_peer_subtree_change_cb==SR_EV_CHANGE====start==
[09-25-17]Wed May 27 09:24:27 2020 user.err : ====ike_peer_subtree_change_cb==ike_subtree_to_model====start==
[09-25-17]Wed May 27 09:24:27 2020 user.err : ====ike_peer_subtree_change_cb==ike_subtree_to_model====2645==
[09-25-17]Wed May 27 09:24:27 2020 user.err : ====ike_peer_subtree_change_cb==ike_subtree_to_model====2654==
[09-25-17]Wed May 27 09:24:27 2020 daemon.notice netifd: Interface 'vxlan6554' is now down
[09-25-17]Wed May 27 09:24:27 2020 authpriv.info ipsec: 13[IKE] deleting IKE_SA Ikev2Peer_6554-TsName_6554[104] between 100.13.175.5[6554]...111.207.49.217[111.207.49.217]
[09-25-17]Wed May 27 09:24:27 2020 daemon.info ipsec: 13[IKE] deleting IKE_SA Ikev2Peer_6554-TsName_6554[104] between 100.13.175.5[6554]...111.207.49.217[111.207.49.217]
[09-25-17]Wed May 27 09:24:27 2020 user.debug : ALARM: parse_msg start
[09-25-17]Wed May 27 09:24:27 2020 user.debug : ALARM: parse_msg end
[09-25-17]Wed May 27 09:24:27 2020 user.debug : ALARM: queue_push_alarm start
[09-25-17]Wed May 27 09:24:27 2020 user.debug : ALARM: queue_push_alarm end
[09-25-17]Wed May 27 09:24:29 2020 user.debug : ALARM: print alarm params...
[09-25-17]Wed May 27 09:24:29 2020 user.debug : ALARM:     alarm code        : 10
[09-25-17]Wed May 27 09:24:29 2020 user.debug : ALARM:     alarm timestamp   : 643886667
[09-25-17]Wed May 27 09:24:29 2020 user.debug : ALARM:     alarm sequenceNo  : 10
[09-25-17]Wed May 27 09:24:29 2020 user.debug : ALARM:     alarm severity    : critical
[09-25-17]Wed May 27 09:24:29 2020 user.debug : ALARM:     alarm status      : occurred
[09-25-17]Wed May 27 09:24:29 2020 user.debug : ALARM:     alarm description : interface vxlan6554 DOWN
[09-25-17]Wed May 27 09:24:29 2020 user.debug : ALARM:     alarm resource id : vxlan6554
[09-25-17]Wed May 27 09:24:29 2020 user.debug : ALARM:     alarm esn         : 000fe9000015
[09-25-17]Wed May 27 09:24:29 2020 user.debug : ALARM: send alarm(vxlan6554 occurred 000fe9000015) to controller successfully!
[09-25-17]Wed May 27 09:24:29 2020 daemon.info netopeer2-server[22145]: Processing "notif" "gwtt-alarm" event with ID 40.
[09-25-17]Wed May 27 09:24:29 2020 daemon.info netopeer2-server[22145]: Successful processing of "notif" event with ID 40 priority 0 (remaining 0 subscribers).
[09-25-17]Wed May 27 09:24:32 2020 daemon.err netopeer2-server[22145]: Callback event "change" with ID 263 processing timed out.
[09-25-17]Wed May 27 09:24:32 2020 daemon.warn netopeer2-server[22145]: Event "change" with ID 263 priority 99 failed (Timeout expired).
[09-25-17]Wed May 27 09:24:32 2020 daemon.info netopeer2-server[22145]: Published event "abort" "gwtt-ietf-ipsec" with ID 263 priority 100 for 1 subscribers.
[09-25-17]Wed May 27 09:24:32 2020 daemon.err netopeer2-server[22145]: Internal error (sysrepo-1.4.58/src/shm_sub.c:1223).
[09-25-17]Wed May 27 09:24:32 2020 daemon.info netopeer2-server[22145]: Failed processing of "rpc" event with ID 635 priority 0 (remaining 1 subscribers).
[09-25-17]Wed May 27 09:24:32 2020 daemon.err netopeer2-server[22145]: Internal error (sysrepo-1.4.58/src/shm_sub.c:1223).
[09-25-17]Wed May 27 09:24:32 2020 daemon.warn netopeer2-server[22145]: Event "rpc" with ID 635 priority 0 failed (User callback failed).
[09-25-17]Wed May 27 09:24:32 2020 daemon.err netopeer2-server[22145]: Failed to send an RPC (User callback failed).
[09-25-17]Wed May 27 09:24:32 2020 daemon.info netopeer2-server[22145]: Session 2: thread 2 event new RPC.
[09-25-17]Wed May 27 09:24:32 2020 daemon.info netopeer2-server[22145]: Session 2: thread 2 event reply error.

**Comment by qjwu888** [comment] 2020-05-27 06:05
Hi Michal,
I found that our callback sometimes blocked， sorry for this.

**Comment by michalvasko** [comment] 2020-05-27 06:16
Hi,
okay, I see. I have not yet had the time to look at this so no harm done. So if it now works as expected, please close this issue.

Regards,
Michal

**Closed** 2020-05-27 11:08 UTC
