### ISSUE TITLE
sr_commit failed when module has a state data with default

### ISSUE THREAD

**Issue by fanchanghu** [sysrepo/sysrepo#326] opened 2016-09-18 10:04 UTC
Hi,
I got failed when I used this module:
```
module a {
  namespace "aaa:1";
  prefix a;
  
  container aa
  {
    leaf f1{
      type int8;
    }
    leaf f2{
      type int8;
      config false;
      default 10;
    }
  }
}
```
then the code like this:
```
int main(void)
{
    sr_conn_ctx_t *sr_conn;
    sr_session_ctx_t *srs; /* SYSREPO session */
    int rc;
    sr_subscription_ctx_t *subscription = NULL;
    sr_val_t value;

    sr_log_set_cb(log_for_sr);

    /* connect to the sysrepo */
    rc = sr_connect("test", SR_CONN_DEFAULT, &sr_conn);
    if (rc != SR_ERR_OK) {
        printf("Unable to connect to sysrepo (%s).\n", sr_strerror(rc));
        return -1;
    }

    rc = sr_session_start(sr_conn, SR_DS_RUNNING, SR_SESS_DEFAULT, &srs);
    if (rc != SR_ERR_OK) {
        printf("Unable to create Netopeer session with sysrepod (%s).\n", sr_strerror(rc));
        return -2;
    }

    rc = sr_module_change_subscribe(srs, "a", handle_module_change, NULL, 0, SR_SUBSCR_DEFAULT, &subscription);
    if (rc != SR_ERR_OK) {
        printf("Failed to subscribe 'a' module (%s).\n", sr_strerror(rc));
        return -3;
    }

    value.xpath = "/a:aa/f1";
    value.type = SR_INT8_T;
    value.data.int8_val = 2;
    rc = sr_set_item(srs, value.xpath, &value, 0);
    if (rc != SR_ERR_OK) {
        printf("Failed to set value (%s).\n", sr_strerror(rc));
        return -4;
    }

    rc = sr_commit(srs);
    if (rc != SR_ERR_OK) {
        printf("Failed to commit (%s).\n", sr_strerror(rc));
        return -5;
    }

    return 0;
}
```
result:
```
(sr_connect:382) Sysrepo daemon not detected. Connecting to local Sysrepo Engine.
(rp_dt_commit:690) Data validation failed: Unknown element "f2".
(sr_commit:1111) Error by processing of commit request.
Failed to commit (Validation of the changes failed).
```
It seems that the state data is in the data tree but `lyd_validate` with `LYD_OPT_CONFIG` in sr_commit caused this problem.

**Comment by fanchanghu** [comment] 2016-09-19 01:50
When I changed a line in "dm_validate_session_data_trees" function like this, it works now.
`if (NULL != info->node && 0 != lyd_validate(&info->node, LYD_OPT_STRICT | LYD_OPT_NOAUTODEL | LYD_OPT_DATA | LYD_OPT_NOSIBLINGS)) {`
is there any other problem for changing like above?

**Comment by lukasmacko** [comment] 2016-09-19 06:17
Hi,

if we changed it like you suggest it would work in your case however it would fail in cases where there are mandatory leaves in state data.
Anyway, thanks for reporting. We'll figure something out.

Regards,
Lukas

**Comment by lukasmacko** [comment] 2016-09-19 08:25
Hi,

I've been investigating further. This is non trivial issue related to validation of default nodes. The issue is already addressed in devel branch (requires libyang devel). Since we plan to merge devel branch into master in two weeks it's not worth fixing in master.

Until devel is merged into master you can either use your workaround or try devel branch.

Regards,
Lukas

**Comment by rastislavszabo** [comment] 2016-10-06 12:23
Fix merged into master branch.

**Closed by rastislavszabo** 2016-10-06 12:23 UTC
Labels: known issue
