### ISSUE TITLE
./netopeer2-server -d ? Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [sysrepo/sysrepo#2022] opened 2020-06-15 10:41 UTC
![image](https://user-images.githubusercontent.com/60098441/84648608-d764f000-af37-11ea-9d9e-54f7fb426361.png)
[ERR]: NP: Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.
[ERR]: NP: Server init failed.

**Comment by michalvasko** [comment] 2020-06-15 11:29
Duplicate of cesnet/netopeer2#652

**Closed by michalvasko** 2020-06-15 11:29 UTC
