### ISSUE TITLE
yang installation causing SIGSEGV in next yang installation

### ISSUE THREAD

**Issue by mdoshi-com** [sysrepo/sysrepo#2172] opened 2020-10-06 14:42 UTC
Hi,
I am trying to install o-ran-aggregation-base.yang using command

`sysrepoctl -i /usr/local/cuduyang/o-ran-aggregation-base.yang -s /usr/local/cuduyang`

This command works fine, but any command after this results in **SIGSEGV**
ex
```
sysrepoctl -i /usr/local/cuduyang/_3gpp-nr-nrm-bwp.yang -s /usr/local/cuduyang
Segmentation fault (core dumped)
```

If i dont install o-ran-aggregation-base.yang and then try installing _3gpp-nr-nrm-bwp.yang, it works fine.

Can you help us figure out what is wrong with o-ran-aggregation-base.yang (zip of the yang file is attached)

[o-ran-aggregation-base.zip](https://github.com/sysrepo/sysrepo/files/5334592/o-ran-aggregation-base.zip)

**Comment by michalvasko** [comment] 2020-10-07 07:17
Hi,
please include all the files you are installing with all their imports, I am not able to reproduce this without them.

**Comment by mdoshi-com** [comment] 2020-10-08 06:05
Hi,
Please find attached zip of folder containing all the dependent yang files.

Regards,
Meghna
[yang.zip](https://github.com/sysrepo/sysrepo/files/5345629/yang.zip)

**Comment by michalvasko** [comment] 2020-10-08 06:25
I failed to reproduce this with the current `devel`, what version of *sysrepo* are you using?

**Comment by mdoshi-com** [comment] 2020-10-08 07:10
Hi,
Following is the version output (yes we are on devel branch)
```
sysrepocfg --version
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v1.4.38 (SO v5.3.5)

Regards,
Meghna

```

**Comment by michalvasko** [comment] 2020-10-08 07:13
This is the current version
```
sysrepocfg --version
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v1.4.87 (SO v5.6.3)
```
Please update it and try again.

**Comment by mdoshi-com** [comment] 2020-10-08 09:46
Hi Michal,
Ok will update and try. Thanks.

Regards,
Meghna

**Comment by mdoshi-com** [comment] 2020-10-14 08:39
Hi Michael,
I am yet to upgrade to latest version and try but i realized that i did not send proper yang.zip folder earlier.
Attached again. Can you please try it once and confirm that it works with the latest devel branch version.

[yang.zip](https://github.com/sysrepo/sysrepo/files/5376806/yang.zip)

**Comment by michalvasko** [comment] 2020-10-15 08:26
I did reproduce the problem with these modules, should now be fixed in `devel`.

**Comment by mdoshi-com** [comment] 2020-10-16 07:25
Hi,
Ok thanks. Will upgrade the version and check.

Regards,
Meghna

**Closed** 2021-01-27 15:18 UTC
