### ISSUE TITLE
Not found node "diffserv-markings" in path 

### ISSUE THREAD

**Issue by raman-in** [sysrepo/sysrepo#3169] opened 2023-10-01 13:44 UTC
I want to install  "o-ran-processing-element.yang" file in sysrepo. It has below leaf "upv4-dscp-name" which is causing error to install.
o-ran-processing-element.yang:
....
case ipv4 {
            when "(../../transport-session-type = 'UDPIP-INTERFACE')";
            leaf upv4-dscp-name {
              type leafref {
                path "/if:interfaces/if:interface/ip:ipv4/o-ran-int:diffserv-markings/o-ran-int:enhanced-uplane-markings/o-ran-int:up-marking-name";
              }
              description "the IPv4 U-plane transport marking as defined in o-ran-interfaces";
            }
          }
          case ipv6 {
            when "(../../transport-session-type = 'UDPIP-INTERFACE')";
            leaf upv6-dscp-name {
              type leafref {
                path "/if:interfaces/if:interface/ip:ipv6/o-ran-int:diffserv-markings/o-ran-int:enhanced-uplane-markings/o-ran-int:up-marking-name";
              }
              description "the IPv6 U-plane transport marking as defined in o-ran-interfaces";
            }
          }
...
I even installed "o-ran-interfaces.yang" to sysrepo which is successful and able to see the reference "diffserv-markings" available.
root@hawking-pc2:/home/netopeer2/build# sysrepoctl --install /home/o-ran-interfaces.yang

o-ran-interfaces.yang:
grouping dscp-marking {
    description
      "Configuration data for CU Plane DSCP marking";
    container diffserv-markings {
      description
        "DSCP Configuration";
      leaf u-plane-marking {
        type inet:dscp;
        default 46;
        description
          "Marking used for default u-plane flows.
          46 represents expedited forwarding";
      }
      leaf c-plane-marking {
        type inet:dscp;
        default 46;
        description "46 represents expedited forwarding";
      }
    ...
}

Error:
root@hawking-pc2:/home/netopeer2/build# sysrepoctl --install /home/o-ran-processing-element.yang -v3
[INF] Connection 33 created.
[ERR] Not found node "diffserv-markings" in path. (Schema location "/o-ran-processing-element:processing-elements/enhanced-uplane-mapping/uplane-mapping/up-markings/ipv4/upv4-dscp-name".)
[ERR] Target of leafref "upv4-dscp-name" cannot be referenced because it is disabled. (Schema location "/o-ran-processing-element:processing-elements/enhanced-uplane-mapping/uplane-mapping/up-markings/ipv4/upv4-dscp-name".)
sysrepoctl error: Failed to install modules (libyang error)

Can you please guide what is missing?

Thanks.

**Comment by michalvasko** [comment] 2023-10-02 06:49
Duplicate of #3022.

**Closed by michalvasko** 2023-10-02 06:49 UTC
