### ISSUE TITLE
sr_set_item_str() fails if called two times for same leaf

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1746] opened 2020-01-13 09:42 UTC
$ yanglint --version
yanglint SO 1.5.13
$ sysrepoctl --version
sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.40 (SO v4.1.26)

Our app is trying to create an openconfig-interface object by using sr_set_item_str() to set several leafs and then calling sr_apply_changes() to commit all changes together.

Things looks working fine if we just fill necessary leaf values once.

However calling sr_set_item_str() twice for the same leaf fails. Say, we first sr_set_item_str() the "enabled" field to "false" and later change our mind and set it to "true". In such case the second call fails with following messages:

```
[ERR]: Node already exists. (path: /openconfig-interfaces:interfaces/interface[name='eth-1/0/1.3']/config/enabled)
[ERR]: Invalid datastore edit.
```

The example application is attached, please compile and run like:

```
$ ./sr_set_item_example 3 3
Started
[ERR]: No data found for "/openconfig-interfaces:interfaces/interface[name='eth-1/0/1.3']/config/name".
[ERR]: Node already exists. (path: /openconfig-interfaces:interfaces/interface[name='eth-1/0/1.3']/config/enabled)
[ERR]: Invalid datastore edit.
$
```
Note that the first error message "No data found..." is expected here, it comes from sr_get_item().

Could you please take a look?
This used to work in sysrepo 0.7.x.
Did I miss something?

**Comment by iljatab** [comment] 2020-01-13 09:45
[app.tar.gz](https://github.com/sysrepo/sysrepo/files/4052882/app.tar.gz)

**Comment by michalvasko** [comment] 2020-01-13 13:52
Hi,
this is actually expected and mostly a feature of the new *sysrepo*, not a bug. You see, these operations were stored as a simple array before but now they are represented as an `edit-config`. By trying to set the leaf to another value, it is being created in the edit-config data tree but since it is already there, it fails. So, you cannot simply "change your mind". However, such a situation can be easily fixed by calling `sr_discard_changes()` that will remove all these prepared changes and you can create then anew. Is that fine?

Because this new mechanism is not worse in (almost) any way and additionally allows to join several operations into a single edit tree which can impact performance for larger edits. Because of that is done by default and the problem here is that your use-case cannot be joined into one tree but could be kept separately in another edit. But such an operation is not really available in API (you an always use `sr_edit_batch` but then you must really know what you are doing) mostly because I could not think of a simple way. Now it seems to me an option `SR_EDIT_ISOLATE` or something similar could cause the edit to be isolated and hence always possible to create, it would be user's responsibility not to overuse this option. But at the same time this seems a bit complex and I am not sure there is an actual use-case.

Regards,
Michal

**Comment by iljatab** [comment] 2020-01-13 14:11
Hi Michal,

Thanks for explanation.

Regrettably this issue bans us from switching to sysrepo 1.3.x.

We populate sysrepo database from sources, other that netconf (say, from CLI).
With CLI the user is free to change his mind as often as he wishes, until committing the whole set of changes. Naturally, sr_discard_changes() is not an option in that.case because it would discard all the changes.

We could build some intermediate layer that would internally accumulate all changes before it is time to commit. Like building a tree for sr_edit_batch(). But in that case we would loose the diagnostic from sysrepo/libyang that comes from incremental sr_set_item_str() calls.

Do you have any other possible suggestions?

**Comment by michalvasko** [comment] 2020-01-14 10:34
Hi,
please try using the new `SR_EDIT_ISOLATE` edit option. It is not yet available for `sr_move_item()` because that would be a non-backwards compatible change, I will add it before the next release.

Regards,
Michal

**Closed** 2020-04-30 07:35 UTC
