### ISSUE TITLE
Create-subscription rpc and subscribe operation fails with ssh poll error

### ISSUE THREAD

**Issue by Neeraj0019** [sysrepo/sysrepo#2267] opened 2020-12-24 11:10 UTC
Hi,
I am trying to subscribe for o-ran-supervision notifications using below 2 approaches and both of them fails with same error.
```
subscribe --filter-xpath /o-ran-supervision:supervision-notification
nc ERROR: Session 1: SSH channel poll error (Socket error: disconnected).
cli_send_recv: Failed to receive a reply.
```
```xml
<create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
<stream>NETCONF</stream>
</create-subscription>
```
This behaviour is seen when we try to add one of our own plugin to handle o-ran-supervision yang model which doesn't handle and notification. below is the snapshot of plugin init cb.
```C
int
sr_plugin_init_cb(sr_session_ctx_t *session, void **private_data)
{
	int rc;
	(void)private_data;
	const char path_rpc_sub[] = "/o-ran-supervision:supervision-watchdog-reset";
	const char path_rpc_notif_sub[] = "/notifications:create-subscription";

	supSess = session;

	rc = sr_rpc_subscribe_tree(session, path_rpc_notif_sub, create_subscription_cb, NULL, 0, SR_SUBSCR_DEFAULT, &supSubscrn);
	if (rc != SR_ERR_OK) 
	{
		goto error;
	}

	rc = sr_rpc_subscribe_tree(session, path_rpc_sub, watchdog_cb, NULL, 0, SR_SUBSCR_CTX_REUSE, &supSubscrn);
	if (rc != SR_ERR_OK) 
	{
		goto error;
	}
	SRP_LOG_DBGMSG("SUPERVISION: plugin initialized successfully.");
	return SR_ERR_OK;

error:
	SRP_LOG_ERR("SUPERVISION: Supervision plugin initialization failed: %s.", sr_strerror(rc));
	sr_unsubscribe(supSubscrn);
	return rc;
}
```

Not getting why this plugin having impact on the subscription behaviour.

Br,
Neeraj

**Comment by michalvasko** [comment] 2021-01-04 08:26
I think it may be caused by a bug in the current *sysrepo* (latest release/`master`) which should be fixed in `devel`. So you can change the branch you are using (but also for *libyang*/*libnetconf2*/*netopeer2*) or wait a few weeks for the next release.

**Closed** 2022-05-30 09:46 UTC
