### ISSUE TITLE
No NP commit context 

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1133] opened 2018-05-22 10:19 UTC
Hi Michal,

I am getting the (No NP commit context for commit ID ..)  error in a specific case scenario followed by 
"Loading of modified models failed" etc.

In this case 2 threads are there and following is the scenario..
Thread1:
Issue commit:-
SR_EV_VERIFY -> return ok. (rpc-reply ok has already been got by the client)
SR_EV_APPLY -->>Got the event and in the middle of  processing the same..
     Before it returns SR_ERR_OK,  In Thread2  another sr_commit() is executed..
  And then immediately in the thread1 again gets the control and it returns the SR_ERR_OK for the event SR_EV_APPLY.

For the 2nd config commit, I could see from the log that SR_EV_VERIFY has been triggered.. but later I am getting the "No NP commit context for commit ID" error followed by "Requested resource is already locked." etc..

 Commit the changes on thread2..
 netopeer2-server: Data from unknown module ((null)session-id) received in sysrepo notification "/ietf-netconf-notifications:netconf-config-change"
Got Event for module1 [verify]:return SR_ERR_OK ==>> For config2
 No NP commit context for commit ID .....
Got Event for module2 [verify]:return SR_ERR_OK ==>> For config2...

 sysrepod[2981]: [ERR] Failed to lock ietf-interfaces in running ds
 sysrepod[2981]: [ERR] Module ietf-interfaces can not be locked
 sysrepod[2981]: [ERR] Loading of modified models failed
netopeer2-server[5970]: Error by processing of the commit request (session id=1704774423): Requested resource is already locked.
netopeer2-server[5970]: Error by processing of commit request.

As per the sysrepo document, each commit request is a blocking call but we can trigger multiple commit request in the same session. Here also once user gets the rpc-reply OK for the 1st config, it triggers the 2nd commit.  But by that time the SR_EVENT_APPLY for the 1st config has not been completed yet.

But still sysrepo process the 2nd config commit request.. and if it processed then why we are getting this issue.

Please let me know if i am missing something here.

Regard's
Rosy

**Comment by michalvasko** [comment] 2018-05-23 11:31
Hi Rosy,
I am not sure I managed to reproduce the problem (I have used just a simple sysrepo application) but the commit did fail on `Resource already locked` error. However, it was actually correct but was not handled correctly so I added some retries in *netopeer2* when this happens. Could you please try it out, whether it is fixed now or what changed? Thanks.

Regards,
Michal

**Comment by rosy8** [comment] 2018-05-23 15:15
Hi Michal,
 Thanks for replying back. I did not get what  you meant by "however it was actually correct ..". Would you please let me know about the same in detail.
Thanks in advance.
Regards
Rosy

**Comment by michalvasko** [comment] 2018-05-24 06:44
Hi Rosy,
I will try to elaborate. Probably, the expected behaviour in this scenario would be that while a commit is happening, any other commits will be blocked until the first one is finished and then be performed serially one-by-one. However, *sysrepo* API calls are never blocking so, instead, an error is returned. What I meant is that this error is correct because the commit cannot be finished because a required resource is already locked (that is exactly the error displayed). So, my change was to simply try to commit again after waiting for a bit so that hopefully the resource will be available by then.

Regards,
Michal

**Comment by rosy8** [comment] 2018-05-24 08:53
Hi Michal,

 Ok. Got it. Thanks for elaborating . 
Yeah in the sysrepo documentation, its clearly mentioned that each  call is a blocking call. 
So even I was expecting the same as you have written above . 

 I had dropped one mail to  the sysrepo community  mentioning about this specific case but have not  got any reply . Please do let me know if  there any other alternative ways to contact to sysrepo ppl to know about this .

I have not been able to test your changes..but hoping that it would have resolve the issue.

Thanks in advance.  

Regards,
Rosy

**Comment by michalvasko** [comment] 2018-05-25 06:36
Hi Rosy,
could you please provide a link (docs in [here](http://www.sysrepo.org/static/doc/html/index.html)) to the text mentioning blocking sysrepo calls?

Did you write to `sysrepo-devel@sysrepo.org`? That is our mailing list (which I am also subscribed to) and we try to reply to every email (even though we may have missed yours somehow).

Regards,
Michal

**Comment by michalvasko** [comment] 2018-06-06 07:38
Hi Rosy,
okay, that is good to hear-

Regards,
Michal

**Closed by michalvasko** 2018-06-06 07:38 UTC
