### ISSUE TITLE
Netopeer2 server not receiving all configured Callhome client's configurations

### ISSUE THREAD

**Issue by senrajib** [sysrepo/sysrepo#758] opened 2017-03-27 10:04 UTC
Hi Antonio

I had configured three callhome clients at a time by writing into sysrepo datastore using sysrepo APIs. Repeated this test several times. Observed Netopeer2 server able to connect to only one client or sometime two clients but not to all. Further investigation of Netopeer2 log shows , Netopeer2 isn't receiving all configured netconf clients configurations. When i configured them individually , Netopeer2 server was able to establish connection to all of them.Configuration as below

[ietf-netconf-server.zip](https://github.com/sysrepo/sysrepo/files/872075/ietf-netconf-server.zip)
[debuglog.zip](https://github.com/sysrepo/sysrepo/files/872076/debuglog.zip)

-Rajib

**Comment by michalvasko** [comment] 2017-04-07 14:12
Duplicate of netopeer2 issue.

**Closed by michalvasko** 2017-04-07 14:12 UTC
Labels: duplicate
