### ISSUE TITLE
netopeer2-cli establish-sub command failed with specifying argument "out" as a file 

### ISSUE THREAD

**Issue by yajing111** [sysrepo/sysrepo#2940] opened 2022-10-20 05:34 UTC
hi,

Netopeer2 version: [v2.1.23], netopeer2-cli establish-sub command failed with specifying argument "out" as a file when recv notification
I am using "sysrepocfg --notification=/run/nokia-oven-test.json -f json" to send a notification, and the file content as below.
```
cat /run/nokia-oven-test.json
{"nokia-oven-test:oven-ready": {}}
```

```
> establish-sub --stream nokia-oven-test --out=/tmp/out.log
DATA
<id xmlns="urn:ietf:params:xml:ns:yang:ietf-subscribed-notifications">8</id>

ly ERROR: ly_vprint_: writing data failed (Bad file descriptor).
>
ly ERROR: ly_vprint_: writing data failed (Bad file descriptor).
>
ly ERROR: ly_vprint_: writing data failed (Bad file descriptor).
```

```
ls -al /tmp/out.log
-rw-r--r-- 1 root root 0 Oct 20 05:18 /tmp/out.log
```

**but if out is stdout, it is OK**

```
> establish-sub --stream nokia-oven-test
DATA
<id xmlns="urn:ietf:params:xml:ns:yang:ietf-subscribed-notifications">10</id>

notification (2022-10-20T05:26:48.203962650+00:00)
<oven-ready xmlns="urn:nokia:rcp:nokia-oven-test"/>
```

Can you please have a look? thank you.

**Comment by michalvasko** [comment] 2022-10-20 06:06
Stop creating duplicate issues, it does not really matter in which project you put it. Duplicate of cesnet/netopeer2#1283

**Closed by michalvasko** 2022-10-20 06:06 UTC
