### ISSUE TITLE
change value of state parameters in ietf-routing yang model

### ISSUE THREAD

**Issue by ashishsaxenahsc** [sysrepo/sysrepo#2305] opened 2021-02-02 12:06 UTC
Hi All,

I am using yang model ietf-routing@2018-03-13.yang , and need to populate value in the following data tree:
+--rw ribs
| +--rw rib* [name]
| +--rw name string
| +--rw address-family identityref
| +--ro default-rib? boolean {multiple-ribs}?
| +--ro routes
| | +--ro route*
| | +--ro route-preference? route-preference
| | +--ro next-hop
| | | +--ro (next-hop-options)
| | | +--:(simple-next-hop)
| | | | +--ro outgoing-interface?
| | | | | if:interface-ref
| | | | +--ro v4ur:next-hop-address?
| | | | | inet:ipv4-address
| | | | +--ro v6ur:next-hop-address?
| | | | inet:ipv6-address
| | | +--:(special-next-hop)
| | | | +--ro special-next-hop? enumeration
| | | +--:(next-hop-list)
| | | +--ro next-hop-list
| | | +--ro next-hop*
| | | +--ro outgoing-interface?
| | | | if:interface-ref
| | | +--ro v4ur:address?
| | | | inet:ipv4-address
| | | +--ro v6ur:address?
| | | inet:ipv6-address
| | +--ro source-protocol identityref
| | +--ro active? empty
| | +--ro last-updated? yang:date-and-time
| | +--ro v4ur:destination-prefix? inet:ipv4-prefix
| | +--ro v6ur:destination-prefix? inet:ipv6-prefix
| +---x active-route
| | +---w input
| | | +---w v4ur:destination-address? inet:ipv4-address
| | | +---w v6ur:destination-address? inet:ipv6-address
| | +--ro output
| | +--ro route
| | +--ro next-hop
| | | +--ro (next-hop-options)
| | | +--:(simple-next-hop)
| | | | +--ro outgoing-interface?
| | | | | if:interface-ref
| | | | +--ro v4ur:next-hop-address?
| | | | | inet:ipv4-address
| | | | +--ro v6ur:next-hop-address?
| | | | inet:ipv6-address
| | | +--:(special-next-hop)
| | | | +--ro special-next-hop?
| | | | enumeration
| | | +--:(next-hop-list)
| | | +--ro next-hop-list
| | | +--ro next-hop*
| | | +--ro outgoing-interface?
| | | | if:interface-ref
| | | +--ro v4ur:next-hop-address?
| | | | inet:ipv4-address
| | | +--ro v6ur:next-hop-address?
| | | inet:ipv6-address
| | +--ro source-protocol identityref
| | +--ro active? empty
| | +--ro last-updated?
| | | yang:date-and-time
| | +--ro v4ur:destination-prefix?
| | | inet:ipv4-prefix
| | +--ro v6ur:destination-prefix?
| | inet:ipv6-prefix

I need to add value for name, address-family, next-hop-address, destination-prefix and source-protocol in the above data tree.
I tried by preparing xml file and using that with edit-config, but this didn't work .
How can I add these values in the data tree ? What is the correct way of doing this?
Thanks and Regards,
Ashish

**Comment by michalvasko** [comment] 2021-02-04 12:58
Duplicate of cesnet/netopeer2#820

**Closed by michalvasko** 2021-02-04 12:58 UTC
