### ISSUE TITLE
The client can not receive the server's notify event msg sometimes, and the server abort the set-item operation

### ISSUE THREAD

**Issue by ostack** [sysrepo/sysrepo#507] opened 2016-11-03 09:31 UTC
The client can not receive the server's notify event msg sometimes, and the server abort the set-item operation. 

I found when this occur , the client always print log : **" (cl_message_recv:201) errno: 11, try again."**,
as  i do not know which direction to check the problem ,so i wonder is any can do me a favor.

thanks a lot

by the way, In my app,my modle change call back function  called **"sr_event_notif_send"** to sent data change msg  to other client when i receive apply notify event .is this function call relate to this issue 

================**Log of sysreop server**=============
[DBG] (rp_set_item_req_process:887) Processing set_item request.
[INF] (rp_dt_set_item_wrapper:559) Set item request running datastore, xpath: /ME:ME/TR:TR/Sctp[id='8']
[DBG] (dm_load_data_tree_file:658) Loaded module ME: mtime sec=1478161322 nsec=388000000
[DBG] (dm_load_data_tree_file:685) Usage count ME incremented (value=8)
[INF] (dm_load_data_tree_file:691) Data file /ostack/etc/sysrepo/data/ME.running loaded successfully
[DBG] (dm_get_data_info:1753) Module ME has been loaded
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=9, current count=1.
[DBG] (rp_worker_thread_execute:2747) Thread id=140253523900160 will wait.
[DBG] (cm_msg_enqueue_cb:1648) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=0, count=0.
[DBG] (cm_conn_out_buff_flush:487) Sending 30 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 30 bytes of data sent.
[DBG] (cm_conn_read_cb:1041) fd 6 readable
[DBG] (cm_conn_read_cb:1054) 28 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1064) fd 6 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 24 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=2, current count=1.
[DBG] (rp_msg_process:3031) Threads: active=0/4, 1 requests in queue
[DBG] (rp_worker_thread_execute:2759) Thread id=140253515507456 signaled.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=3, count=0.
[DBG] (rp_commit_req_process:1093) Processing commit request.
[DBG] (rp_dt_commit:688) Commit (1/9): process started
[DBG] (dm_validate_session_data_trees:2138) Validation succeeded for 'ME' module
[DBG] (rp_dt_commit:697) Commit (2/9): validation succeeded
[DBG] (sr_locking_set_lock_fd:734) File /ostack/etc/sysrepo/data/ME.persist has been locked
[DBG] (pm_load_data_tree:174) Persist data successfully loaded from file '/ostack/etc/sysrepo/data/ME.persist'.
[DBG] (sr_locking_set_unlock_close_fd:803) File /ostack/etc/sysrepo/data/ME.persist (fd = 13) has been unlocked
[DBG] (pm_get_subscriptions:813) Returning 0 subscriptions found in 'ME' persist file.
[DBG] (sr_locking_set_lock_fd:734) File /ostack/etc/sysrepo/data/ME.persist has been locked
[DBG] (pm_load_data_tree:174) Persist data successfully loaded from file '/ostack/etc/sysrepo/data/ME.persist'.
[DBG] (sr_locking_set_unlock_close_fd:803) File /ostack/etc/sysrepo/data/ME.persist (fd = 13) has been unlocked
[DBG] (pm_get_subscriptions:813) Returning 1 subscriptions found in 'ME' persist file.
[DBG] (dm_commit_prepare_context:2707) Commit: In the session there are 1 / 1 modified models
[DBG] (sr_locking_set_lock_file_open:670) File /ostack/etc/sysrepo/data/ME.running.lock has been locked
[DBG] (dm_lock_module:859) Usage count ME incremented (value=9)
[DBG] (dm_is_info_copy_uptodate:2205) Session copy ME: mtime sec=1478161322 nsec=388000000
[DBG] (dm_is_info_copy_uptodate:2208) Loaded module ME: mtime sec=1478161322 nsec=388000000
[DBG] (dm_is_info_copy_uptodate:2211) Current time: mtime sec=1478161322 nsec=457158199
[DBG] (dm_is_info_copy_uptodate:2220) Module ME will be refreshed
[DBG] (dm_load_data_tree_file:658) Loaded module ME: mtime sec=1478161322 nsec=388000000
[DBG] (dm_load_data_tree_file:685) Usage count ME incremented (value=10)
[INF] (dm_load_data_tree_file:691) Data file /ostack/etc/sysrepo/data/ME.running loaded successfully
[DBG] (dm_insert_data_info_copy:298) Usage count ME incremented (value=11)
[DBG] (rp_dt_commit:713) Commit (3/9): all modified models loaded successfully
[DBG] (dm_get_data_info:1725) Module ME already loaded
[DBG] (rp_dt_commit:720) Commit (4/9): replay of operation succeeded
[DBG] (dm_validate_session_data_trees:2138) Validation succeeded for 'ME' module
[DBG] (rp_dt_commit:730) Commit (5/9): merged models validation succeeded
[DBG] (dm_commit_notify:3046) Sending verify notifications about the changes made in running datastore...
[DBG] (dm_commit_notify:3103) Created: /ME:ME/TR:TR/Sctp[id='8']
[DBG] (np_subscription_notify:824) Sending module-change notification to '/tmp/sysrepo-subscriptions/ME/130.3NMxM6.sock' @ 1735608829.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=0, current count=1.
[DBG] (np_commit_notif_cnt_increment:282) Creating a new NP commit context for commit ID 1157283207.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=1, current count=2.
[DBG] (np_commit_notifications_sent:954) Set up commit timeout for commit id=1157283207.
[DBG] (rp_dt_commit:738) Commit (6/9): verify phase done
**[DBG] (rp_dt_commit:741) Commit 1157283207 processing paused waiting for replies from verifiers
[DBG] (rp_commit_req_process:1124) Request paused, waiting for verifiers
[DBG] (rp_worker_thread_execute:2747) Thread id=140253515507456 will wait.
[DBG] (cm_msg_enqueue_cb:1648) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=1, count=1.
[DBG] (cm_out_notif_process:1312) Sending a notification to '/tmp/sysrepo-subscriptions/ME/130.3NMxM6.sock'.
[DBG] (cm_out_notif_process:1324) Reusing existing connection on fd=9 for the notification destination '/tmp/sysrepo-subscriptions/ME/130.3NMxM6.sock'
[DBG] (cm_conn_out_buff_flush:487) Sending 128 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 128 bytes of data sent.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=2, count=0.
[DBG] (cm_delayed_msg_process:308) Scheduling a delayed request for 10.000000 seconds.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=3, current count=1.
[DBG] (rp_msg_process:3031) Threads: active=0/4, 1 requests in queue
[DBG] (cm_delayed_request_cb:279) Delayed request sent to the Request Processor.
[DBG] (rp_worker_thread_execute:2759) Thread id=140253507114752 signaled.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=4, count=0.
[DBG] (rp_commit_timeout_req_process:2157) Processing commit-timeout request.
[DBG] (np_commit_notifications_complete:1032) Releasing commit id=1745887733.
[DBG] (np_commit_notifications_complete:1048) Commit id=1745887733 notifications complete.
[ERR] (np_commit_notifications_complete:1051) Commit timeout for commit id=1745887733.**
[DBG] (rp_resume_commit:3075) Commit context in state 10
[INF] (rp_resume_commit:3113) Commit id 1745887733 received all notifications
[DBG] (dm_data_info_free:224) Usage count ME decremented (value=10)
[INF] (dm_unlock_datastore:1012) Unlock datastore request
[DBG] (dm_data_info_free:224) Usage count ME decremented (value=9)
[DBG] (dm_remove_commit_context:2607) Commit context with id 1745887733 removed
[DBG] (rp_worker_thread_execute:2747) Thread id=140253507114752 will wait.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=4, current count=1.
[DBG] (rp_msg_process:3031) Threads: active=0/4, 1 requests in queue
[DBG] (cm_delayed_request_cb:279) Delayed request sent to the Request Processor.
[DBG] (rp_worker_thread_execute:2759) Thread id=140253532292864 signaled.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=5, count=0.
[DBG] (rp_commit_timeout_req_process:2157) Processing commit-timeout request.
[DBG] (rp_worker_thread_execute:2747) Thread id=140253532292864 will wait.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=5, current count=1.
[DBG] (rp_msg_process:3031) Threads: active=0/4, 1 requests in queue
[DBG] (cm_delayed_request_cb:279) Delayed request sent to the Request Processor.
[DBG] (rp_worker_thread_execute:2759) Thread id=140253523900160 signaled.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=6, count=0.
[DBG] (rp_commit_timeout_req_process:2157) Processing commit-timeout request.
[DBG] (np_commit_notifications_complete:1048) Commit id=1157283207 notifications complete.
[ERR] (np_commit_notifications_complete:1051) Commit timeout for commit id=1157283207.
[DBG] (rp_resume_commit:3075) Commit context in state 6
[INF] (rp_resume_commit:3080) Resuming commit with id 1157283207 continue with abort
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=6, current count=1.
[DBG] (rp_msg_process:3031) Threads: active=1/4, 1 requests in queue
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=7, count=0.
[DBG] (rp_commit_req_process:1093) Processing commit request.
[DBG] (dm_commit_notify:3046) Sending abort notifications about the changes made in running datastore...
[DBG] (dm_commit_notify:3103) Deleted: /ME:ME/TR:TR/Sctp[id='8']
[DBG] (np_subscription_notify:824) Sending module-change notification to '/tmp/sysrepo-subscriptions/ME/130.3NMxM6.sock' @ 1735608829.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=2, current count=1.
[INF] (dm_unlock_datastore:1012) Unlock datastore request
[DBG] (dm_unlock_datastore:1020) Module_name ME
[DBG] (dm_unlock_datastore:1023) Usage count ME decremented (value=8)
[DBG] (sr_locking_set_unlock_close_file:777) File /ostack/etc/sysrepo/data/ME.running.lock has been unlocked
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=3, current count=2.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=4, current count=3.
[DBG] (np_commit_notifications_sent:954) Set up commit timeout for commit id=1157283207.
[DBG] (rp_dt_commit:765) Commit (8/9): abort notifications sent
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=5, current count=4.
[DBG] (rp_worker_thread_execute:2747) Thread id=140253523900160 will wait.
[DBG] (cm_msg_enqueue_cb:1648) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=3, count=3.
[DBG] (cm_out_notif_process:1312) Sending a notification to '/tmp/sysrepo-subscriptions/ME/130.3NMxM6.sock'.
[DBG] (cm_out_notif_process:1324) Reusing existing connection on fd=9 for the notification destination '/tmp/sysrepo-subscriptions/ME/130.3NMxM6.sock'
[DBG] (cm_conn_out_buff_flush:487) Sending 128 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 128 bytes of data sent.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=4, count=2.
[DBG] (cm_out_notif_process:1312) Sending a notification to '/tmp/sysrepo-subscriptions/ME/130.3NMxM6.sock'.
[DBG] (cm_out_notif_process:1324) Reusing existing connection on fd=9 for the notification destination '/tmp/sysrepo-subscriptions/ME/130.3NMxM6.sock'
[DBG] (cm_conn_out_buff_flush:487) Sending 108 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 108 bytes of data sent.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=5, count=1.
[DBG] (cm_delayed_msg_process:308) Scheduling a delayed request for 10.000000 seconds.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=6, count=0.
[DBG] (cm_conn_out_buff_flush:487) Sending 30 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 30 bytes of data sent.
[DBG] (cm_conn_read_cb:1041) fd 6 readable
[DBG] (cm_conn_read_cb:1054) 28 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1064) fd 6 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 24 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=7, current count=1.
[DBG] (rp_msg_process:3031) Threads: active=0/4, 1 requests in queue
[DBG] (rp_worker_thread_execute:2759) Thread id=140253515507456 signaled.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=8, count=0.
[DBG] (rp_discard_changes_req_process:1164) Processing discard_changes request.
[DBG] (dm_data_info_free:224) Usage count ME decremented (value=7)
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=6, current count=1.
[DBG] (rp_worker_thread_execute:2747) Thread id=140253515507456 will wait.
[DBG] (cm_msg_enqueue_cb:1648) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=7, count=0.
[DBG] (cm_conn_out_buff_flush:487) Sending 30 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 30 bytes of data sent.
[DBG] (cm_conn_read_cb:1041) fd 6 readable
[DBG] (cm_conn_read_cb:1054) 27 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1064) fd 6 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 23 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=8, current count=1.
[DBG] (rp_msg_process:3031) Threads: active=0/4, 1 requests in queue
[DBG] (rp_worker_thread_execute:2759) Thread id=140253507114752 signaled.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=9, count=0.
[DBG] (rp_session_refresh_req_process:1246) Processing session_data_refresh request.
[INF] (rp_dt_refresh_session:837) Refresh session request running datastore
[INF] (rp_dt_refresh_session:849) No operation has been performed on this session so far
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=7, current count=1.
[DBG] (rp_worker_thread_execute:2747) Thread id=140253507114752 will wait.
[DBG] (cm_msg_enqueue_cb:1648) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=8, count=0.
[DBG] (cm_conn_out_buff_flush:487) Sending 29 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 29 bytes of data sent.
[DBG] (cm_conn_read_cb:1041) fd 6 readable
[DBG] (cm_conn_read_cb:1054) 109 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1064) fd 6 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 105 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=9, current count=1.
[DBG] (rp_msg_process:3031) Threads: active=0/4, 1 requests in queue
[DBG] (rp_worker_thread_execute:2759) Thread id=140253532292864 signaled.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=0, count=0.
[DBG] (rp_delete_item_req_process:949) Processing delete_item request.
[INF] (rp_dt_delete_item_wrapper:586) Delete item request running datastore, xpath: /ME:ME/TR:TR/Sctp[id='8']
[DBG] (dm_load_data_tree_file:658) Loaded module ME: mtime sec=1478161322 nsec=388000000
[DBG] (dm_load_data_tree_file:685) Usage count ME incremented (value=8)
[INF] (dm_load_data_tree_file:691) Data file /ostack/etc/sysrepo/data/ME.running loaded successfully
[DBG] (dm_get_data_info:1753) Module ME has been loaded

**Comment by ostack** [comment] 2016-11-03 12:39
======================add app log==============

12:38:48:586999  sysrepo_data_repository.cpp:60 : (cl_sm_fd_read_data:1113) fd 0 readable 
12:38:48:587613  sysrepo_data_repository.cpp:51 : (cl_sm_fd_read_data:1141) Error by reading data on fd 0: Invalid argument. 
12:38:48:587675  sysrepo_data_repository.cpp:60 : (cl_sm_connection_cleanup:283) Closing subscriber connection on fd=0. 
12:38:58:595268  sysrepo_data_repository.cpp:60 : (cl_sm_accept_server_connections:1246) New connection on fd 0 
12:38:58:596075  sysrepo_data_repository.cpp:60 : (cl_sm_fd_read_data:1113) fd 0 readable 
12:38:58:596124  sysrepo_data_repository.cpp:60 : (cl_sm_conn_buffer_expand:368) Input buffer for fd=0 expanded to 1024 bytes. 
12:38:58:596146  sysrepo_data_repository.cpp:60 : (cl_sm_fd_read_data:1127) 240 bytes of data received on fd 0 
12:38:58:596166  sysrepo_data_repository.cpp:60 : (cl_sm_fd_read_data:1137) fd 0 would block 
12:38:58:596184  sysrepo_data_repository.cpp:60 : (cl_sm_conn_in_buff_process:1063) New message of size 126 bytes received. 
12:38:58:596223  sysrepo_data_repository.cpp:60 : (cl_sm_notif_process:637) Received a notification for subscription id=509256248 (source address='/tmp/sysrepod.sock'). 
12:38:58:596251  sysrepo_data_repository.cpp:60 : (cl_sm_get_data_session:461) Connecting to the notification originator at '/tmp/sysrepod.sock'. 
12:38:58:596286  sysrepo_data_repository.cpp:60 : (cl_socket_connect:373) Connecting to socket=/tmp/sysrepod.sock 
12:38:58:596336  sysrepo_data_repository.cpp:60 : (cl_sm_get_data_session:495) Creating a new data session at '/tmp/sysrepod.sock'. 
12:38:58:596363  sysrepo_data_repository.cpp:60 : (cl_request_process:417) Sending session-start request. 
12:38:58:596396  sysrepo_data_repository.cpp:60 : (cl_request_process:439) session-start request sent, waiting for response. 
12:38:58:598617  sysrepo_data_repository.cpp:60 : (cl_request_process:461) session-start response received, processing. 
12:38:58:598674  sysrepo_data_repository.cpp:60 : (cl_sm_notif_process:690) Calling module-change callback for subscription id=509256248. 
12:38:58:598705  sysrepo_data_repository.cpp:60 : (cl_sm_conn_buffer_expand:368) Output buffer for fd=0 expanded to 1024 bytes. 
12:38:58:598726  sysrepo_data_repository.cpp:60 : (cl_sm_conn_out_buff_flush:391) Sending 140 bytes of data. 
12:38:58:598750  sysrepo_data_repository.cpp:60 : (cl_sm_conn_out_buff_flush:397) 140 bytes of data sent. 
12:38:58:598771  sysrepo_data_repository.cpp:60 : (cl_sm_conn_in_buff_process:1063) New message of size 106 bytes received. 
12:38:58:598791  sysrepo_data_repository.cpp:60 : (cl_sm_notif_process:637) Received a notification for subscription id=509256248 (source address='/tmp/sysrepod.sock'). 
12:38:58:598828  sysrepo_data_repository.cpp:60 : (cl_sm_notif_process:709) COMMIT-END notification received on subscription id=509256248. 
12:38:58:598856  sysrepo_data_repository.cpp:60 : (cl_request_process:417) Sending session-stop request. 
12:38:58:598881  sysrepo_data_repository.cpp:60 : (cl_request_process:439) session-stop request sent, waiting for response. 
12:38:58:599062  sysrepo_data_repository.cpp:60 : (cl_request_process:461) session-stop response received, processing.

**Comment by milanlenco** [comment] 2016-11-04 12:40
Hi,

the effect of the problem can be seen already on the top of the application log:

```
12:38:48:586999 sysrepo_data_repository.cpp:60 : (cl_sm_fd_read_data:1113) fd 0 readable
12:38:48:587613 sysrepo_data_repository.cpp:51 : (cl_sm_fd_read_data:1141) Error by reading data on fd 0: Invalid argument. 
```

Actually the messages prior to this could be interesting and help us to find the root cause. Would it be possible for you to re-produce the issue and provide _full_ logs of both server and client?

At the moment we are unable to tell what is the source of the issue, but one thing that comes to mind is the restriction on the session passed to module-change callback: it cannot be used to call RPC, send event notification or edit configuration. If this is your case, you will need to create a separate session for notifications.

**Comment by ostack** [comment] 2016-11-08 04:24
yes,  we used a new session to sent event notify,not the session passed to module-change callback

**Comment by milanlenco** [comment] 2016-11-11 12:32
Hi,

the issue should be fixed by this commit: https://github.com/lukasmacko/sysrepo/commit/ba2db5cea8d4b4ff45a2211c10ed76c57c1bf523
It was merged to both master and devel.

**Closed by milanlenco** 2016-11-11 12:32 UTC

**Comment by ostack** [comment] 2016-11-12 01:55
Thanks
May be issue #530 is caused by the same reason,i will check it
