### ISSUE TITLE
yang node is augment and when

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#2854] opened 2022-06-28 09:14 UTC
Hi @michalvasko
When the Yang node is augment and when, the callback function sr_module_change_subscribe cannot receive data
but why?

**Comment by michalvasko** [comment] 2022-07-13 15:41
I will need much more details than that. What YANG module are you using exactly? What data changes are you making? What is the actual behavior versus the expected one?

**Comment by hi-Mr-ye** [comment] 2022-07-15 06:19
This is the Yang file:
[och-yang.zip](https://github.com/sysrepo/sysrepo/files/9118351/och-yang.zip)

And data returned by running the get command:
![image](https://user-images.githubusercontent.com/90752673/179162523-6356c4b7-9a9e-46ad-9e83-0743f6f852ca.png)

I run edit-config using netopeer2-cli. But display errors

![image](https://user-images.githubusercontent.com/90752673/179163265-ae046169-a0db-4a3c-94e8-646b527b5434.png)
![image](https://user-images.githubusercontent.com/90752673/179163289-ba7b7c12-fce6-49dc-aa6a-f6e0ef0990f2.png)

**Comment by michalvasko** [comment] 2022-07-15 12:30
Duplicate of #2868

**Closed by michalvasko** 2022-07-15 12:30 UTC
Labels: is:bug
