### ISSUE TITLE
The copy-config from running to startup always report "Request could not be completed because the requested operation failed for a non-specific reason."

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1349] opened 2018-11-13 02:17 UTC
Hi,

After startup the netopeer2-server/sysrepo, the ```get-config, edit-config``` for running datastore are both working well, but when I do the copy-config from the running datastore to startup with netopeer2-cli or some other netconf client, following errors are reported.
Whether there is some missing for my configuration?

```
> copy-config --target startup --source running 
ly VERBOSE: Resolving unresolved data nodes and their constraints...
ly VERBOSE: All data nodes and constraints resolved.
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Request could not be completed because the requested operation failed for a non-specific reason.
```
But though the above error is reported, the copy-config was succeed in fact, and the startup datastore is the same with the running datastore.

Here is the example:
```
> get-config --source running
ly VERBOSE: Resolving unresolved data nodes and their constraints...
ly VERBOSE: All data nodes and constraints resolved.
DATA
<users xmlns="http://qingdao_cnet.com/ns/normal/example">
  <user>
    <name>darcy</name>
    <number>1</number>
    <role>aaa</role>
  </user>
  <user>
    <name>hunter</name>
    <number>3</number>
    <role>aaa</role>
  </user>
  <user>
    <name>jerry</name>
    <number>4</number>
    <role>ccc</role>
  </user>
</users>
```
The yang file is:
```
# cat normal.yang 
module normal {
  namespace "http://qingdao_cnet.com/ns/normal/example";
  prefix users;

  container users {
    list user {
      key name;
      leaf name {
        type string;
      }
      leaf number {
        type uint8;
        mandatory true;
      }
      leaf role {
        type string{
            length 1..15;
            }
                must ".!=../name" {
                    error-message "The role couldn't be the same with the name!";
                }
      }
    }
  }
}
```

The XML is:
```
# cat normal.xml 
<users xmlns="http://qingdao_cnet.com/ns/normal/example">
    <user>
        <name>darcy</name>
        <number>1</number>
        <role>aaa</role>
    </user>
    <user>
        <name>hunter</name>
        <number>3</number>
        <role>aaa</role>
    </user>
    <user>
        <name>jerry</name>
        <number>4</number>
        <role>ccc</role>
    </user>
  </users>
```
Thanks
Darcy

**Comment by michalvasko** [comment] 2018-11-13 07:42
Hi Darcy,
should work now, duplicate of cesnet/netopeer2#351.

Regards,
Michal

**Closed** 2018-11-13 07:42 UTC
