### ISSUE TITLE
bug for yang augment handling

### ISSUE THREAD

**Issue by GuoyouZhang** [sysrepo/sysrepo#1338] opened 2018-11-01 08:26 UTC
Hi,
i'm trying to load ietf-interfaces model and ietf-microwave-radio-link.  ietf-microwave-radio-link has augment to the interface defined in ietf-interfaces. 
```yang
  augment "/if:interfaces/if:interface" {
    when "derived-from-or-self(if:type,"
       + "'mw-types:radio-link-terminal')";
...
    choice freq-or-distance {
      leaf rx-frequency {
        type uint32;
        units "kHz";
        description
          "Selected receiver frequency.";
      }
      leaf duplex-distance {
        type int32;
        units "kHz";
        description
          "Distance between transmitter and receiver frequencies.";
      }
      mandatory true;
      description
        "A choice to configure rx-frequency directly or by computing
         it as tx-frequency subtracted with the configured
         duplex-distance." ;
    }
...
```
it means only when interface type is mw-types:radio-link-terminal, the interface will contain the radio-link  related attribute.  

The test result is that, even i create other type of interface, the sysrepo still check radio-link (mandatory)attribute. i think the code didn't handle the augment condition dynamically. i mean it should check the attribute based on "when ..."

**Comment by GuoyouZhang** [comment] 2018-11-01 08:30
maybe it didn't handle the choice type well for augment

**Comment by GuoyouZhang** [comment] 2018-11-01 09:34
it looks like libyang issue

2018-10-25 10:18:00,407 DEBG 'sysrepod' stdout output:
[ERR] libyang error: Mandatory choice "freq-or-distance" missing a case branch.
[ERR] Loaded data tree '/etc/sysrepo/data/ietf-interfaces.running' is not valid
[ERR] Getting data tree for ietf-interfaces failed.
[ERR] Get data info failed for module ietf-interfaces
[ERR] Failed to append data tree ietf-interfaces
[ERR] Loading dependant modules failed for ietf-microwave-radio-link
[WRN] Validation of module with instance_id or cross-module deps ietf-microwave-radio-link failed

**Comment by michalvasko** [comment] 2018-11-01 09:46
Hi,
please provide a specific example I could test. I have used the attached files and the validation succeeded in both `yanglint` and `sysrepocfg` import. Once I changed the value of `l` to `1`, it failed as it should have.

```yang
module test {
    prefix t;
    namespace "urn:test";

    container cont {
        leaf l {
            type uint8;
        }
    }
}
```
```yang
module test2 {
    prefix t2;
    namespace "urn:test2";

    import test {
        prefix t;
    }

    augment "/t:cont" {
        when "l = '1'";

        leaf augleaf {
            type string;
            mandatory true;
        }
    }
}
```
```xml
<cont xmlns="urn:test">
    <l>2</l>
</cont>
```

Regards,
Michal

**Comment by michalvasko** [comment] 2018-11-01 12:05
Duplicate of cesnet/libyang#651.

**Closed by michalvasko** 2018-11-01 12:05 UTC
